### ISSUE TITLE
Dotplot hover broken in Firefox

### ISSUE THREAD

**Issue by ewels** [MultiQC/MultiQC#1063]
The hover behaviour for the dot plot works fine in Chrome:

![image](https://user-images.githubusercontent.com/465550/69527671-16682f80-0f6d-11ea-810f-be01cd38f967.png)

But is unresponsive in Firefox:

![image](https://user-images.githubusercontent.com/465550/69527707-254ee200-0f6d-11ea-9871-99c201ebe3d0.png)

**Comment by ewels** [comment]
Reported by @jamigo via email ✉️

**Comment by daler** [comment]
In case it changes anything, just chiming in to say this is still an issue, where hovering over dotplots is unresponsive in Firefox. From my understanding of the code and your responses on other related issues I suspect it's a lot of effort to fix, so using Chrome is a reasonable workaround!
