### ISSUE TITLE
Qualimap: Option to disable auto x-max limit

### ISSUE THREAD

**Issue by lczech** [MultiQC/MultiQC#1280]
**Description of bug:**
Several modules produce plots where the x-axis is not scaled properly, to the point where the plots cannot be used in any way.

![qualimap_genome_fraction](https://user-images.githubusercontent.com/4741887/91121609-05a82f80-e64d-11ea-91f2-41d7493f4b2c.png)
![qualimap_coverage_histogram (3)](https://user-images.githubusercontent.com/4741887/91121611-05a82f80-e64d-11ea-8abc-b987ab66182a.png)
![fastqc_adapter_content_plot](https://user-images.githubusercontent.com/4741887/91121608-04770280-e64d-11ea-93b4-649a71672292.png)

**MultiQC Error log:**
```
[WARNING]         multiqc : MultiQC Version v1.9 now available!
[INFO   ]         multiqc : This is MultiQC v1.8 (43cb2f9)
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /home/lczech/Projects/grenepipe/1735-734/qc/dedup
[INFO   ]         multiqc : Searching   : /home/lczech/Projects/grenepipe/1735-734/qc/samtools-stats
[INFO   ]         multiqc : Searching   : /home/lczech/Projects/grenepipe/1735-734/trimmed
[INFO   ]         multiqc : Searching   : /home/lczech/Projects/grenepipe/1735-734/qc/qualimap
[INFO   ]         multiqc : Searching   : /home/lczech/Projects/grenepipe/1735-734/qc/fastqc
[INFO   ]         multiqc : Searching   : /home/lczech/Projects/grenepipe/1735-734/qc/samtools-flagstats
[INFO   ]        qualimap : Found 48 BamQC reports
[INFO   ]          picard : Found 48 MarkDuplicates reports
[INFO   ]        samtools : Found 48 stats reports
[INFO   ]        samtools : Found 48 flagstat reports
[INFO   ]          skewer : Found 48 reports
[INFO   ]          fastqc : Found 48 reports
[INFO   ]         multiqc : Compressing plot data
[WARNING]         multiqc : Deleting    : qc/multiqc_data   (-f was specified)
[INFO   ]         multiqc : Report      : qc/multiqc.html
[INFO   ]         multiqc : Data        : qc/multiqc_data
[INFO   ]         multiqc : MultiQC complete
```

**File that triggers the error:**
This is just the `qualimap` files, for which the error is most prominent. If the `fastqc` files are also needed, I'll supply them on demand.
[qualimap.zip](https://github.com/ewels/MultiQC/files/5121282/qualimap.zip)

**MultiQC run details (please complete the following):**
* Command used to run MultiQC: [run via snakemake] `multiqc  --force -o qc -n multiqc.html qc/qualimap qc/dedup trimmed qc/samtools-stats qc/samtools-flagstats qc/fastqc  > logs/multiqc.log 2>&1`
* MultiQC Version: MultiQC v1.8
* Operating System: Ubuntu 18.04
* Python Version: Not sure what is run from within snakemake, but: `python --version` yields Python 2.7.17 (so, probably not what snakemake is using)
* Method of MultiQC installation: conda within snakemake

**Additional context**
Run from within snakemake. I have tried several browsers (Chrome, Chromium, Firefox), all exhibit the same error.

**Comment by lczech** [comment]
Just updated to MultiQC v1.9 (which by the way does not work with Python 3.6.7 - crashes due to `click`, but works with Python 3.7). The plots are identical to the ones above - that is, the bug has not been resolved in v1.9 yet.

**Comment by lczech** [comment]
Probably I should also specify this bit of detail: The main issue I have with these plots is that they are cut off too early on the x-axis. They seem to capture most of the data, as can be seen in the plot below, where I manually specified the x-axis maximum. But from just looking that the plots, this is not obvious. I think these plots should extend further along the x-axis.

![qualimap_coverage_histogram](https://user-images.githubusercontent.com/4741887/91127336-e1534f80-e65a-11ea-83d7-224c603f86a8.png)

**Comment by ewels** [comment]
Hi @lczech,

Sorry for the slow response. This isn't a bug as such, but a feature 😉 Most Qualimap reports I've worked with have been much higher coverage with a nice bump (eg. around 30X) and a long tail up to ridiculously high coverage. So as a result we made the MultiQC module automatically trim off that very long tail as it makes the rest of the plot unreadable.

Here it's working against you because of the profile of your data - no particularly long tail and the majority of sites with 0X coverage.

I don't really want to change the default behaviour as I think that it's the right thing to do for most people. However we could add a config option to disable this. Would that be of interest?

Phil

**Comment by lczech** [comment]
Hi @ewels ,

thank you for the clarification, that absolutely makes sense! And fully agreed, for non-pathological data, this is a good way to handle the tail. As you can guess from the plots above, my data had some issues, which I tried to resolve and understand using MultiQC. And for such pathological cases only, the trail-trimming breaks down.

So, while the default that you described is reasonable, how about this: a slight increase in the minimum x-axis range, maybe to 5X instead of 2X as shown above. For normal cases, this would not come into play anyway, as they have higher coverage, but for pathological cases such as mine, it would clearly show that there is no data beyond ~3X.

Just a suggestion - now that I understand the rational behind the current feature, it can also be left as-is ;-)

Cheers
Lucas

**Comment by ewels** [comment]
The trimming of the x-axis isn't hardcoded currently, it just keeps plotting x-axis points until 99% of the data has been represented:

https://github.com/ewels/MultiQC/blob/a342077c23ae164c53d1c780dfed557335d88f6e/multiqc/modules/qualimap/QM_BamQC.py#L313-L324

But yes, maybe we could add some code to check that this doesn't happen before 20 data points have been plotted or something, or a certain minimum coverage has been reached.

**Comment by vladsavelyev** [comment]
I addressed the QualiMap long trail over-trimming with: https://github.com/MultiQC/MultiQC/pull/2431

I'm not sure about the FastQC plot though. We are not trimming long tails there, however, we hide samples with almost no data:

https://github.com/MultiQC/MultiQC/blob/8965075ce4641dd2172a0abfb543c3b5fbe1e076/multiqc/modules/fastqc/fastqc.py#L1064-L1066

@lczech, it would be helpful if you could share your FastQC example to see if that's the issue and come up with a better solution here.

**Comment by lczech** [comment]
Hi @vladsavelyev,

> @lczech, it would be helpful if you could share your FastQC example to see if that's the issue and come up with a better solution here.

Sorry, I'm afraid that was some test data or something that I don't have any more... I looked for the files I used there, but no luck. But it seems the issue is solved already anyway?

Cheers
Lucas
