### ISSUE TITLE
Switching between log10 and counts in HTML report reverts to stacked bar graph

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [MultiQC/MultiQC#1320]
**Description of bug:**
Switching from `log10` scale to `counts` in the HTML report reverts plot back to stacked bar graph.

**MultiQC Error log:**
There is no error log

**File that triggers the error:**
I've attached an example html file that causes the bug, in the CCS section. Switch from `counts` to `log10`, and then back to `counts` again to see the bug. 
[multiqc_report.zip](https://github.com/ewels/MultiQC/files/5399749/multiqc_report.zip)

**MultiQC run details (please complete the following):**
* Command used to run MultiQC:  `multiqc -f --data-format json ccs`
* MultiQC Version: multiqc, version 1.10.dev0 (3cfaa4d)
* Operating System: Ubuntu 20.04
* Python Version: Python 3.8.5
* Method of MultiQC installation: local pip install, working on my version of the [CCS branch](https://github.com/Redmar-van-den-Berg/MultiQC/blob/3cfaa4d2398e54e2db0f1f8e18773a74f38f4e46/multiqc/modules/ccs/ccs.py#L83)

**Additional context**
I was working on the CCS module which isn't part of the mainline MultiQC yet, when I encountered this bug. I did not reproduce it in the main version of MultiQC because I believe it to be a bug in the javascript, and I don't know if there are any other modules that use unstacked plots in combination with log10.

**Comment by ewels** [comment]
Good spot, thanks for reporting 👍🏻 Very few modules use side-by-side bar plots instead of stacked which I guess is why this has gone unnoticed for as long as it has.

Note that the reason that so few modules use it is that I think that stacked bar plots are nearly always better 😅 In your example it's almost impossible to compare samples (you have to tab through each one and remember what the previous profiles looked like). Comparing samples was the main motivation for writing MultiQC.

Phil

**Comment by mbahin** [comment]
Hi @ewels,

We just ran into this use case (unstacked barplots getting stacked after playing with the tabs `counts` <->`log`).
Do you know if someone made an attempt to fix this bug?

Cheers,
Mathieu

**Comment by ewels** [comment]
Not yet, no sorry. I dislike unstacked bar plots so there are not many to be found within MultiQC, so it's not a super high priority sorry. It would be good to fix though..

**Comment by mbahin** [comment]
Ok, thanks for your quick answer! :)

**Comment by vladsavelyev** [comment]
This works with new Plotly backend 💪
