### ISSUE TITLE
seqwho

### ISSUE THREAD

**Issue by vsmalladi** [MultiQC/MultiQC#1388]
**Tool Details**

- Name of tool: seqwho
- Tool homepage: https://git.biohpc.swmed.edu/s181649/seqwho
- Tool description: Type Sequence files for species and assay
- Data suitable for MultiQC plot(s): fastqc like plots
- Most interesting data for General Stats table: Inferred Sequence Type, Inferred Species

**Tool output:**
TSV file of stats
PDF file of figures

- Log filename pattern: 
- File contents:

**Comment by vsmalladi** [comment]
Graphs simiarl to fastqc: 

1) %GC content 
2) Average Read quality 
3) Number of reads in the file 
4) sequence/adapter content

**Comment by ewels** [comment]
Hi @vsmalladi,

Please attach some example output files and answer the template questions about standardised filenames.

Many thanks,

Phil

**Comment by vsmalladi** [comment]
log files are SeqWho_call.json or SeqWho_call.tsv

Attached is the tsv example version 
[SeqWho_call_example.txt](https://github.com/ewels/MultiQC/files/6851381/SeqWho_call_example.txt)
