### ISSUE TITLE
Add to troubleshooting docs - `UnicodeEncodeError` with missing `PYTHONIOENCODING`

### ISSUE THREAD

**Issue by braveagle0** [MultiQC/MultiQC#1443]
Hi, ewels

I am trying to install multiQC with conda command. My python version is 3.6. I generated a new env as instructed.  The install failed in the end with the following message

```
Proceed ([y]/n)?
Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge::colorama-0.4.4-pyh9f0ad1d_0'.
FileNotFoundError(2, "No such file or directory: '/home/guans/bin/anaconda3/envs/multiqc/bin/python3.6'")
Attempting to roll back.

Rolling back transaction: done

FileNotFoundError(2, "No such file or directory: '/home/guans/bin/anaconda3/envs/multiqc/bin/python3.6'")
```

Would you please give me some suggestions?
Thanks!

**Comment by matthdsm** [comment]
Hi @braveagle0 

This seems to be a conda issue instead of a multiqc issue.

Try installing using the following command

```bash
conda create -n multiqc python=3.6 multiqc
```

This will create a new env named `multiqc` containing `python 3.6` and `multiqc`
Also see https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#id1

M

**Comment by braveagle0** [comment]
Hi, @matthdsm 

Thanks for your advice. It seems that I was able to complete the installation. However, when I tried to run the program with "multiqc .", the program quits prematurely with the following msg

...
 File "/home/guans/bin/anaconda3/envs/multiqc/lib/python3.6/site-packages/rich/console.py", line 767, in _exit_buffer
    self._check_buffer()
  File "/home/guans/bin/anaconda3/envs/multiqc/lib/python3.6/site-packages/rich/console.py", line 1748, in _check_buffer
    self.file.write(text)
  File "/home/guans/bin/anaconda3/envs/multiqc/lib/python3.6/encodings/iso8859_15.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u280b' in position 20: character maps to <undefined>
*** You may need to add PYTHONIOENCODING=utf-8 to your environment ***

Would you please provide me some solutions? Thanks a lot!

**Comment by ewels** [comment]
Have you tried doing what it suggests in the error message?

```bash
export PYTHONIOENCODING=utf-8
```

**Comment by matthdsm** [comment]
Hi Phil,

I've just noticed this error too. Funny thing is, it only appeared after installing `v1.10.1`. Were there some new check's introduced?
M

PS: `export PYTHONIOENCODING=utf-8` does fix it, but it's weird MultiQC didn't throw this error on a previous version.

**Comment by braveagle0** [comment]
The export command works for me. Thanks1

**Comment by ewels** [comment]
Great that it fixed it 👍🏻 

I can't see anything new in [the diff](https://github.com/ewels/MultiQC/compare/v1.10...v1.10.1#diff-e37f615e3d08e0950c5c68cf25fe74f8bafc98d5fe427d6f0346743b9ca903b1) between versions 1.10 and 1.10.1, except for bumping the minimum required version for the `rich` library (which is the dependency that is raising this error).

Not really sure what I can do about this one - suggestions welcome!

Phil

**Comment by matthdsm** [comment]
Seems to be a system issue. Can either be fixed user side, or by explicitly setting the encoding to "utf-8" at the beginning of the script IMO.

M

**Comment by ewels** [comment]
> or by explicitly setting the encoding to "utf-8" at the beginning of the script IMO.

Would this work? I thought it was to do with the terminal encoding, not the script encoding.. Happy to add that to the script if it would fix it.

Not sure how to test this locally sorry, which makes it a bit tricky for me to try stuff.

**Comment by matthdsm** [comment]
I haven't tested it either, but it seems to be some kind of locale issue I think.
According to stackoverflow we can set the encoding to predefined default
https://stackoverflow.com/questions/2276200/changing-default-encoding-of-python

**Comment by ewels** [comment]
Yeah, I think I might have seen this before when I've been fighting with `LC_ALL` locale stuff on bioconda. I'm a bit put off by this though:

> *This is not a safe thing to do**, though: this is obviously a hack, since `sys.setdefaultencoding()` is purposely removed from `sys` when Python starts.

https://anonbadger.wordpress.com/2015/06/16/why-sys-setdefaultencoding-will-break-code/

**Comment by matthdsm** [comment]
agreed, best thing to do is the let the users set their locale correctly

**Comment by ewels** [comment]
I will add this to the documentation under troubleshooting 👍🏻

**Comment by ewels** [comment]
Turns out that I already do the nasty hack in MultiQC, but only for Python 2:

https://github.com/ewels/MultiQC/blob/e8f36ee7afab19ec281b2684a40da3fc7fd42fa5/multiqc/multiqc.py#L38-L40

Not sure it changes anything here. I am planning to remove all Python-2 hacks pretty soon as it's no longer supported and the modules codebase is slowly becoming less py2k compatible. This workaround will be removed with it I think..

**Comment by vladsavelyev** [comment]
All python 2 stuff was removed, so shouldn't be an issue I believe
