### ISSUE TITLE
NanoStat: Parse file from NanoComp with multiple samples

### ISSUE THREAD

**Issue by schorlton** [MultiQC/MultiQC#1630]
### Description of feature

As per title, NanoComp can produce a NanoStats file for multiple files where it just puts the stats in columns. This seems to be a generalization of the current MultiQC expected format where it only expects one column/sample. Would be really nice to run NanoComp on all files (so I can generate its plots) and pass the single `NanoStats.txt`file into MultiQC instead of having to run `NanoPlot`/`NanoStat` on each file to get the summary.

I'm attaching an example NanoComp output NanoStats file: 
[NanoStats.txt](https://github.com/ewels/MultiQC/files/8063802/NanoStats.txt)

Thanks for your consideration!!

**Comment by lianov** [comment]
Indeed, I would love to see this module for multiple samples. We just tried to add it to our ongoing development of nf-core/scnanoseq and encountered this same issue. Thanks for looking into this!

**Comment by lianov** [comment]
@ewels : any idea if this is something that may be fixed in the near future? We would love to have this feature for the MultiQC report from nf-core/scnanoseq. But if it is not doable in the meantime, not a big deal at all (we do have aggregated reports from `nanocomp` in the mean time.

**Comment by ewels** [comment]
Sounds easy enough - I've added it to the milestone for the next release 👍🏻

**Comment by vladsavelyev** [comment]
I added a support for the file attached in https://github.com/MultiQC/MultiQC/pull/2852, however, it looks like it's an old format that is probably deprecated now. I wonder if you have multi-sample examples of the most recent report, so I can address it too?
