### ISSUE TITLE
Enable multiqc to pull nextclade quality results from nextclade csv output file

### ISSUE THREAD

**Issue by mabvakureb** [MultiQC/MultiQC#1708]
### Name of the tool

Nextclade

### Tool homepage

https://clades.nextstrain.org/

### Tool description

Clade assignment, mutation calling, and sequence quality checks.

### Tool output

[nextclade_results.csv](https://github.com/ewels/MultiQC/files/8919372/nextclade_results.csv)

### Log filename pattern

*nextclade.csv

### Data suitable for MultiQC plot(s)

**Data output most important:** qc.overallScore, qc.overallStatus, totalSubstitutions, totalDeletions, totalInsertions, totalFrameShifts, totalAminoacidSubstitutions, totalAminoacidDeletions, totalAminoacidInsertions, totalMissing, totalNonACGTNs, totalPcrPrimerChanges, deletions, insertions, privateNucMutations.totalReversionSubstitutions, privateNucMutations.totalLabeledSubstitutions, privateNucMutations.totalUnlabeledSubstitutions, privateNucMutations.totalPrivateSubstitutions, frameShifts, alignmentScore, alignmentStart, alignmentEnd, qc.missingData.missingDataThreshold, qc.missingData.score, qc.missingData.status, qc.missingData.totalMissing, qc.mixedSites.mixedSitesThreshold, qc.mixedSites.score, qc.mixedSites.status, qc.mixedSites.totalMixedSites, qc.privateMutations.cutoff, qc.privateMutations.excess, qc.privateMutations.score, qc.privateMutations.status, qc.privateMutations.total, qc.snpClusters.clusteredSNPs, qc.snpClusters.score, qc.snpClusters.status, qc.snpClusters.totalSNPs, qc.frameShifts.frameShifts, qc.frameShifts.totalFrameShifts, qc.frameShifts.frameShiftsIgnored, qc.frameShifts.totalFrameShiftsIgnored, qc.frameShifts.score, qc.frameShifts.status, qc.stopCodons.stopCodons, qc.stopCodons.totalStopCodons, qc.stopCodons.score, qc.stopCodons.status, errors

**Output :** table

### Most interesting data for the General Stats table

totalSubstitutions
totalDeletions
totalInsertions
totalFrameShifts
totalAminoacidSubstitutions
totalAminoacidDeletions
totalAminoacidInsertions
totalMissing
totalNonACGTNs
totalPcrPrimerChanges
privateNucMutations.totalPrivateSubstitutions

**Comment by vladsavelyev** [comment]
nextclade is supported now 👍
