### ISSUE TITLE
Always save plot data to files, even if flat-image plots.

### ISSUE THREAD

**Issue by ramay** [MultiQC/MultiQC#1750]
### Description of bug

I ran mutliqc v1.12 on fastqc files and if I have more than 100 I get the following output files in multiqc_data folder

```
mqc_fastqc_adapter_content_plot_1.txt
mqc_fastqc_overrepresented_sequences_plot_1.txt
mqc_fastqc_per_base_n_content_plot_1.txt
mqc_fastqc_per_base_sequence_quality_plot_1.txt
mqc_fastqc_per_sequence_gc_content_plot_Counts.txt
mqc_fastqc_per_sequence_gc_content_plot_Percentages.txt
mqc_fastqc_per_sequence_quality_scores_plot_1.txt
mqc_fastqc_sequence_counts_plot_1.txt
mqc_fastqc_sequence_duplication_levels_plot_1.txt
mqc_fastqc_sequence_length_distribution_plot_1.txt
multiqc.log
multiqc_citations.txt
multiqc_data.json
multiqc_fastqc.txt
multiqc_sources.txt
```
while when I have < 100 I don't get any of the mqc files
```
multiqc.log
multiqc_data.json
multiqc_general_stats.txt
multiqc_citations.txt
multiqc_fastqc.txt
multiqc_sources.txt
```
Is there a reason to do this? I was using the mqc_fastqc  to generate per base qc information in my reports but I can't get this information out when samples are < 100. Is there a command line option I can use to generate these files for <100 samples?

Thanks!
Hena

**Comment by ramay** [comment]
I figured out that in the config_defaults.yaml there is a variable called plots_flat_numseries and changing that can solve this problem. Is that correct?
Thanks!

**Comment by ewels** [comment]
Indirectly, yes. That config option changes whether plots in the HTML report should be interactive or flat (see the [docs](https://multiqc.info/docs/#flat--interactive-plots)).

I guess that the plot code isn't exported when MultiQC generates flat image plots. I should probably look into tweaking this behaviour.

**Comment by ramay** [comment]
Thanks @ewels ! It will be great to have an option to get consistent output.

**Comment by vladsavelyev** [comment]
This should be fixed now 👍
