### ISSUE TITLE
Samtools: add markdup

### ISSUE THREAD

**Issue by bernt-matthias** [MultiQC/MultiQC#1862]
### Name of the tool

samtools markdup

### Tool homepage

https://www.htslib.org/doc/samtools-markdup.html

### Tool description

mark duplicate alignments in a coordinate sorted file

### Tool output

```
COMMAND: samtools markdup -@ 0 -s coordsort.sam /tmp/tmpea8lprdd/files/2/2/4/dataset_224df993-f6bf-4c7d-99a1-2e9dd51c2a57.dat
READ: 16
WRITTEN: 16
EXCLUDED: 3
EXAMINED: 13
PAIRED: 10
SINGLE: 3
DUPLICATE PAIR: 4
DUPLICATE SINGLE: 2
DUPLICATE PAIR OPTICAL: 0
DUPLICATE SINGLE OPTICAL: 0
DUPLICATE NON PRIMARY: 0
DUPLICATE NON PRIMARY OPTICAL: 0
DUPLICATE PRIMARY TOTAL: 6
DUPLICATE TOTAL: 6
ESTIMATED_LIBRARY_SIZE: 4
```

### Data suitable for MultiQC plot(s)

Details here: https://www.htslib.org/doc/samtools-markdup.html#STATISTICS

### Most interesting data for the General Stats table

I guess at least the data that has been presented for `rmdup`.

**Comment by ewels** [comment]
Thanks! If you could attach a zipped file that's best, as GitHub comments can mess with the whitespace which is often important. So generally I prefer the original files if possible.

**Comment by bernt-matthias** [comment]
[stats.txt](https://github.com/ewels/MultiQC/files/10685301/stats.txt)

**Comment by matthdsm** [comment]
Seconded! This would be very useful!

**Comment by a-frantz** [comment]
Thirded! We'd love to have this integration.

**Comment by matthdsm** [comment]
@vladsavelyev, is there a timeline on this?

**Comment by vladsavelyev** [comment]
@matthdsm, @clintval is working on this: https://github.com/MultiQC/MultiQC/pull/2254 not sure what the status of it.
