### ISSUE TITLE
Non-HighChart plots return an error when trying to export

### ISSUE THREAD

**Issue by robsyme** [MultiQC/MultiQC#1872]
### Description of bug

When a multiQC report include plots that are not the basic HighChart variety, plot export throws a potentially confusing error:

![image](https://user-images.githubusercontent.com/31576/222827327-9d2c8367-b04c-4d8c-ab81-c9a7509e2b6c.png)

When a report contains many plots, it is difficult to track down which plot/plots are causing the issue without going through the list one by one.

I have not included a full MultiQC log as this is a front-end javascript problem. I have checked the `I have included a full MultiQC log` box regardless. Forgive me Phil ❤️ 

### File that triggers the error

[5_multiqc_report.html.zip](https://github.com/ewels/MultiQC/files/10886015/5_multiqc_report.html.zip)

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/#troubleshooting-1).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by ewels** [comment]
The alert here is not really the problem - the custom FastQC heatmap can't be exported. Fix is to not make this a blocker for exporting _other_ plots though. Instead, alert / warn about the problem and keep going..

**Comment by ewels** [comment]
- FastQC custom heatmap
- Dragen custom heatmap
- Table scatter plots when columns not selected

**Comment by ewels** [comment]
Is this fixed by https://github.com/ewels/MultiQC/pull/1976 @vladsavelyev ?
