### ISSUE TITLE
Consider using `orjson`

### ISSUE THREAD

**Issue by ewels** [MultiQC/MultiQC#1920]
Possible alternative for handling JSON structures: https://github.com/ijl/orjson

Could be quite a lot faster and require fewer type hacks.

**Comment by rhpvorderman** [comment]
I happened to test orjson as Sequali outputs JSON reports and the majority of report processing time is spent in the json module. 

Unfortunately orjson does not allow the use of filehandles. But using filehandles can lead to enormous memory savings. See:  #2510. 

So I do not think orjson is a good fit for MultiQC, as MultiQC already uses quite a lot of memory when a substantial number of reports is analysed. In fact, I think MultiQC should stick to the Python buitin JSON module for the following reasons:

- Less dependencies is always better
- The extra speed gained by orjson is not significant. We are talking about tenths of seconds for the multiqc test-data repo. For extensive JSON reports as generated by sequali, it does make a difference when parsing. But now we are talking about 30 seconds of runtime for 800+ reports. When I have a workflow of 400+ samples, 30 seconds is not really concerning. I am much more likely to run out of memory in this case than I am running out of time. (On our cluster that is)
- Many of the tools are written using Python. Python does not have a standards-compliant encoder/decoder. Using the builtin json module of Python in MultiQC will prevent some issues with interoperability.

**Comment by ewels** [comment]
Compelling enough points for me 👍🏻
