### ISSUE TITLE
Parse Cutadapt JSON Output

### ISSUE THREAD

**Issue by NanoCoreUSA** [MultiQC/MultiQC#1933]
### Description of feature

Since version 3.5, cutadapt is able to generate a JSON log file (#1482), with the intent that these files could be parsed by MultiQC and possibly provide some improved log info on a per-read basis (#885).

I've created a pull request to upload a sample JSON file from a recent cutadapt run (using latest version, 4.4) to [here](https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/cutadapt). Also happy to generate more if these are missing any information or a specific use case is required.

Obviously it's not a pressing need as MultiQC successfully parses the standard text logs from cutadapt just fine, but just wanted to provide some test data and renew the feature request so it can be implemented in the future.

**Comment by ewels** [comment]
Thanks @NanoCoreUSA ! Yes it would be good to move this forward. We need to be a bit careful about parsing _both_ JSON and traditional logs, but it shouldn't be too difficult to handle that case.
