### ISSUE TITLE
beeswarm plot: add option to plot selected columns, like with the table

### ISSUE THREAD

**Issue by vivekbhr** [MultiQC/MultiQC#1940]
### Description of feature

Hello

In case of tabulating a large number of samples, multiQC switches from table layout to beeswarm plots. This seems logical, but there we loose the ability to optionally plot 2 selected columns against each other, like with tables. It would be very useful if that was possible.

Thanks,
Vivek

**Comment by vladsavelyev** [comment]
This is support now - tables and violins (new beeswarms) now have the same interface
