### ISSUE TITLE
nonpareil module

### ISSUE THREAD

**Issue by fgvieira** [MultiQC/MultiQC#1944]
### Name of the tool

nonpareil

### Tool homepage

https://github.com/lmrodriguezr/nonpareil

### Tool description

Estimate metagenomic coverage and sequence diversity

### Tool output

This is a second attempt to issue #474.

Tool outputs a TSV that needs to be post-processed through some `R` functions to estimate the model.

I've recently created a [snakemake wrapper](https://snakemake-wrappers.readthedocs.io/en/stable/wrappers/nonpareil/plot.html) to plot the results from `nonpareil`, but not sure how to get them into `MultiQC`.

The wrapper outputs the main `R` object as a `.RData` file (example [here](https://github.com/ewels/MultiQC/files/11894162/sample_data.zip) for both single- and multi-sample analysis), but not sure how to import it into `MultiQC`. Maybe a `json`?

### Data suitable for MultiQC plot(s)

In a plot, I think it would be useful to see the same as in [here](http://enve-omics.ce.gatech.edu/nonpareil/results?jid=example1).

Mainly, the observed curve, the model curve (if estimated), and desired threshold (red dotted line).

### Most interesting data for the General Stats table

In the `R` object there are several values that could be interesting to show on the General Stats table:
```
          Redundancy Avg. coverage Seq. effort Model correlation
sample_10       0.60          0.63       12.48                 1
sample_11       0.75          0.77       16.83                 1
sample_12       0.44          0.47        6.45                 1
sample_13       0.50          0.53        9.02                 1
sample_1        0.29          0.32        8.23                 1
sample_2        0.52          0.55       14.48                 1
sample_3        0.38          0.42       12.20                 1
sample_4        0.31          0.35       10.29                 1
sample_5        0.36          0.39        9.92                 1
sample_6        0.35          0.38       10.83                 1
sample_7        0.67          0.69       13.87                 1
sample_8        0.50          0.53        6.63                 1
sample_9        0.55          0.58        8.88                 1
          Required seq. effort Diversity
sample_10               170.47     22.14
sample_11                62.80     21.58
sample_12               171.31     22.53
sample_13               198.09     22.51
sample_1                464.34     23.72
sample_2                182.51     22.98
sample_3                372.83     23.54
sample_4                439.33     23.77
sample_5                370.82     23.48
sample_6                445.06     23.63
sample_7                 82.80     21.97
sample_8                126.29     22.17
sample_9                112.49     22.19
```

### Before submitting

- [X] I have included example data (zipped, not pasted) that can be used to write the module.

**Comment by fgvieira** [comment]
I've been trying to see if I could convert the `curves` object to a `json`, but with partial success:
```
# Get variable names
n <- names(attributes(curves$np.curves[[1]]))[1:29]
# Extract values
d <- sapply(curves$np.curves, function(x) lapply(n, function(v) toJSON(attr(x,v), auto_unbox=TRUE)))
rownames(d) <- n
# Prettify
a <- lapply(apply(d, 2, toJSON, auto_unbox=TRUE), prettify)
```

**Comment by jianshu93** [comment]
Hello @fgvieira ,


Just curious whether the Json can be again formatted into CSV or data frame so that it can directly used for ggplot2. The default R plot engine is not great but ggplot2 is.

thanks,

Jianshu

**Comment by fgvieira** [comment]
Haven't tried it, but it would be quite nice to use ggplot2 for the plots.
if you manage to make `nonpareil` plots with ggplot2, let me know! :smile:
