### ISSUE TITLE
Scatter plot "xPlotBands" and "yPlotBands" do not render in the correct order if custom "data_labels" are provided

### ISSUE THREAD

**Issue by buijt** [MultiQC/MultiQC#1953]
### Description of bug

I encountered an bug when defining xPlotBands and yPlotBands simultaneously while I was developing a plugin module for MultiQC using the scatter plot. This figure rendering bug appears when bands are defined on both axes, and custom "data_label" names are provided to `pconfig`. 

The figure will initially render as expected with the xPlotBands being drawn first, then the yPlotBands drawn on top of the xPlotBands. However, when switching between datasets with a custom data_label, the draw order is reversed, where the yPlotBands are now drawn first and the xPlotBands are drawn on top. When no data_label is defined in `pconfig`, the axis color bands are drawn as expected, consistent to the first render.

The video below demonstrates the inconsistency. The first half of the video shows what happens when the custom data_label names are defined in `pconfig` (data switch names "one" and "two"), whereas the figure is rendered as expected when no data_label is defined (data switch names "1" and "2").

https://github.com/ewels/MultiQC/assets/44679745/913b4c76-535d-464d-853e-c014122e091e

I have observed this behavior occurring regardless of whether the HTML report file is opened in Firefox, Google Chrome, or Microsoft Edge.

### File that triggers the error

Sample plotting code to reproduce the bug:
```
def plot_test(self):
        pconfig = {
            "id": "test",
            "title": "test plot",
            "xPlotBands": [
                {"from": 0, "to": 3, "color": "#fcf4b2"},
                {"from": 3, "to": 10, "color": "#d2f8d2"},
            ],
            "yPlotBands": {"from": 3, "to": 10, "color": "#ffdae0"},
            "data_labels": [{"name": "one"}, {"name": "two"}],       # this line leads to unexpected x/y PlotBands render order
        }
        data = [
            {
                "sample 1": {"x": 1, "y": 5},
                "sample 2": {"x": 5, "y": 3},
            },
            {
                "sample 1": {"x": 2, "y": 2},
                "sample 2": {"x": 7, "y": 4},
            },
        ]
        plot_html = scatter.plot(data, pconfig)
        self.add_section(name="test plot", plot=plot_html)
```

### MultiQC Error log

```console
N/A
```

### Before submitting

- [x] I have read the [troubleshooting documentation](https://multiqc.info/docs/#troubleshooting-1).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Just check how it's looking now after introducing the Plotly backend and major refactroing. This looks consistent! Bad news, the bands functionality was broken for scatter plots (only work for line plots now), which I'm restoring now with https://github.com/MultiQC/MultiQC/pull/2851
