### ISSUE TITLE
Samtools `coverage` output

### ISSUE THREAD

**Issue by MarcNiebel** [MultiQC/MultiQC#2021]
### Description of feature

Recently new to using this tool but love what it can do thus far! I am looking at creating a beeswarm plot using the samtools coverage output. An example command found here [http://www.htslib.org/doc/samtools-coverage.html](url) `samtools coverage -r chr1:1M-12M input.bam`. Looking at getting a quality metric of my alignment. I of course could create this plot in R or similar but thought this might be of benefit to others.

**Comment by vladsavelyev** [comment]
Hi @MarcNiebel,

Could you please share more detail how such plot would look like?

Note that the idea of MultiQC is to do as little computation as possible, and just aggregate the already calculated QC outputs from multiple tools and multiple samples.

**Comment by MarcNiebel** [comment]
Hi @vladsavelyev,

Thanks for responding.

From the above command results are generated with the headers:
`#rname  startpos  endpos    numreads  covbases  coverage  meandepth  meanbaseq  meanmapq`
rname (reference used for mapping), startpos & endpos(chosen by the user) might not be helpful for visualisation. However I was thinking that a beeswarm plot similar to what is already done for samtools samstats within MultiQC with the sample name available on hovering on individual points a possible nice additon. This is to allow users to see the distribution of these calculated parameters.

**Comment by splaisan** [comment]
Hi @vladsavelyev, having samtools coverage in the QC would be great to visualize the sequencing depth per chromosome and spot issues (gender!). Is there any way to push this?
thanks

**Comment by MarcNiebel** [comment]
Thanks a lot @vladsavelyev

**Comment by splaisan** [comment]
Thanks @vladsavelyev , 
Looking forward to test this
