### ISSUE TITLE
Plot both lines and point on the same graph

### ISSUE THREAD

**Issue by fgvieira** [MultiQC/MultiQC#2218]
### Description of feature

I am thinking of make a module for metaDMG, but was wondering it it was possible to to have both lines and points on the same plot? Ideally, I'd like something like:
![image](https://github.com/ewels/MultiQC/assets/1151762/e82a2090-aac9-4638-9b0f-e33e3bb7e41f)

Live demo [here](https://metadmg.onrender.com/.)

**Comment by ewels** [comment]
You can already add additional datasets, such as lines - see https://multiqc.info/docs/development/plots/#additional-data-series

I can't remember off the top of my head whether you can do a variable width area like that though, maybe not. But plots such as the GC FastQC plot do this for example: (see black dotted line)

![fastqc_per_sequence_gc_content_plot](https://github.com/ewels/MultiQC/assets/465550/d18216b3-6588-4c6e-9d2c-e66d96c7f18c)

**Comment by vladsavelyev** [comment]
You can add dots to a line plot, see example in preseq: https://github.com/MultiQC/MultiQC/blob/main/multiqc/modules/preseq/preseq.py#L370-L379

<img width="1126" alt="Screenshot 2024-02-12 at 21 20 48" src="https://github.com/MultiQC/MultiQC/assets/1575412/f729126e-b8a1-4dc1-9759-a3e2a3b70905">

As Phil said, you can also add arbitrary extra lines with `extra_series`, though not fill an area between arbitrary lines (only rectangular areas are supported, [e.g.](https://github.com/MultiQC/MultiQC/blob/cfcf32aa0d2fefe5eb9185e6da7d131d12d02ac0/multiqc/modules/dragen_fastqc/content_metrics.py#L77-L81)). 

Not sure if that's enough to reproduce this kind of plot, but might be helpful!

**Comment by ewels** [comment]
I think this issue is now covered by some alternatives which have narrower scope:

- https://github.com/MultiQC/MultiQC/issues/2214
- https://github.com/MultiQC/MultiQC/issues/2324

Shout if there's anything missing and we can create a new issue to cover that particular case.
