### ISSUE TITLE
BCL Convert module halves the "% Bases ≥ Q30 (PF)" in MultiQC 1.19

### ISSUE THREAD

**Issue by hmontenegro** [MultiQC/MultiQC#2250]
### Description of bug

In MultiQC 1.19, the "% Bases ≥ Q30 (PF)" is halved in relation to the correct figures in the "Sample Statistics" table - the "Lane Statistics" shows the correct percentages. 

MultiQC versions 1.13 and 1.17 show correct numbers.

### File that triggers the error

[Fastq Report_ds.f761a851b8764790a214943eb9752e87.zip](https://github.com/MultiQC/MultiQC/files/13746364/Fastq.Report_ds.f761a851b8764790a214943eb9752e87.zip)

### MultiQC Error log

```console
$ multiqc -ip -n bclconvert -o . ../../basespace/appsession/Fastq\ Report_ds.f761a851b8764790a214943eb9752e87/
/home/program2/bin/MultiQC/1.19/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))

  /// MultiQC 🔍 | v1.19

|           multiqc | Search path : /home/hmontene/runs/Illumina/NextSeq/231213_VH00451_157_AACCMNKHV/basespace/appsession/Fastq Report_ds.f761a851b8764790a214943eb9752e87
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 56/56  
|        bclconvert | 2 lanes and 36 samples found
|           multiqc | Report      : bclconvert.html
|           multiqc | Data        : bclconvert_data
|           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Thank you so much for filing an issue, and sorry for this 🤦  - should be fixed with https://github.com/MultiQC/MultiQC/issues/2250
