### ISSUE TITLE
Bismark's M-bias plot module description includes a broken link

### ISSUE THREAD

**Issue by ryancey1** [MultiQC/MultiQC#2251]
https://github.com/MultiQC/MultiQC/blob/55ffcbc400ca1fc88c9feef310e8fcff850f6385/multiqc/modules/bismark/bismark.py#L460

This link leads to a page that doesn't exist anymore. Perhaps it should be replaced with the following?

https://felixkrueger.github.io/Bismark/bismark/methylation_extraction/#m-bias-plot

**Comment by ewels** [comment]
Yes indeed - good spot! Thanks!

**Comment by ryancey1** [comment]
Thank you for the quick fix @ewels!
