### ISSUE TITLE
Allow user to specify which sample log files belong to

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [MultiQC/MultiQC#2266]
### Description of feature

When writing pipelines, it can be a big struggle to get the folder structure just right, so that MultiQC properly recognizes which sample a log file belongs to for each tool. Usually, this requires reorganizing your entire project by putting the outputs in `{tool}/{sample}`, rather than the more natural way of having all files from each sample together. Although this can be different for different tools

I would love to have a way to either:
- Specify which sample a log file belongs to, either via the command line or a configuration file
- Get at least the full file path (both folders and file name) as "sample name", and modify this via the configuration

When writing automated pipelines, I **know** exactly which log files belong to which samples, but there is no way to relay this information to MultiQC.

**Comment by ewels** [comment]
I think that both of these things are already possible:

> Specify which sample a log file belongs to, either via the command line or a configuration file

You can sample names manually with `--replace-names` / config `sample_names_replace`. See [the docs](https://multiqc.info/docs/reports/customisation/#sample-name-replacement).

> Get at least the full file path (both folders and file name) as "sample name", and modify this via the configuration

Using the full file path is possible using `--fullnames` / `-s`: _Do not clean the sample names (leave as full file name)_ - also via a config file, see [the docs](https://multiqc.info/docs/getting_started/config/#filename-truncation).

Did you have something different in mind? Could you provide a usage example of how your proposed feature would work, if so?

**Comment by Redmar-van-den-Berg** [comment]
For example, I have the following log files:
```
star/sample-28-001/align/Log.final.out
star/sample-31-001/align/Log.final.out
star/sample-30-001/align/Log.final.out
star/sample-32-001/align/Log.final.out
star/sample-29-001/align/Log.final.out
```
All of these will be put under the name `align` in the MultiQC report, even when using the `--fullnames` to MultiQC.

Command:
```bash
multiqc --force --lint --verbose --filename ~/tmp/multiqc_report.html --data-dir multiqc_data --data-format json --fullnames star/
```
MultiQC version:
```bash
$ multiqc --version
multiqc, version 1.20.dev0 (585d6ee)
```

**Comment by ewels** [comment]
If the sample identifier is in the directory path, you can use `--dirs` and `--dirs-depth` to include that ([docs](https://multiqc.info/docs/getting_started/running_multiqc/#directory-prefixes-in-sample-names)). Does that get you anywhere? Maybe in combination with `--replace-names`?

**Comment by Redmar-van-den-Berg** [comment]
Unfortunately, using both `--fullnames` and `--dirs` does not seem to work for all tools. It does the trick for the STAR output files, where I get
```
sample1 | align | Log.final.out
sample2 | align | Log.final.out
```

However, for another tool (UMI-Tools), I only get a single entry, which does not contain the sample name.
```
integration-vanilla | log | Aligned.sortedByCoord.out.bam
```
 The log file this data comes from is `/data/test/test-umi-deduplication-23640/integration-vanilla/log/sample1_umi_dedup.log`. If I let MultiQC parse the file name directly

I'm not sure how this happened, since I pass the log files directly to MultiQC:
```
|           multiqc | Search path : /data/test/test-umi-deduplication-23640/integration-vanilla/humid/sample1/stats.dat
|           multiqc | Search path : /data/test/test-umi-deduplication-23640/integration-vanilla/humid/sample2/stats.dat
|           multiqc | Search path : /data/test/test-umi-deduplication-23640/integration-vanilla/log/sample1_umi_dedup.log
|           multiqc | Search path : /data/test/test-umi-deduplication-23640/integration-vanilla/log/sample2_umi_dedup.log
|           multiqc | Search path : /data/test/test-umi-deduplication-23640/integration-vanilla/sample1/align/Log.final.out
|           multiqc | Search path : /data/test/test-umi-deduplication-23640/integration-vanilla/sample2/align/Log.final.out
```

The exact command I used
```bash
multiqc --force --dirs --dirs-depth 2 --file-list multiqc_filelist.txt --fullnames --filename  /tmp/multiqc_report.html
```

**Comment by ewels** [comment]
Hah, we're really doing a full tour of all MultiQC sample naming options here. The UMI-tools sample name is coming from the input filename, rather than the log filename. MultiQC takes this approach where possible as it's good to track samples from their initial FastQ filename through analysis where possible.

You can tell MultiQC to instead use the log filename with the `--fn_as_s_name` option.

**Comment by Redmar-van-den-Berg** [comment]
I finally got it to work, by basically combining all your suggestions @ewels.

In case anyone else wants to get full control over the sample names:
Run MultiQC with the following parameters
```bash
dir_depth=3  # Change this depending on where the log files are located
multiqc_config=path/to/config.yml
multiqc \
        --force \
        --dirs \
        --dirs-depth ${dir_depth} \
        --fullnames \
        --fn_as_s_name \
        --config ${multiqc_config} 
```

And then in the configuration file, replace the log file paths with sample names, using regex
```yml
sample_names_replace_regex: True
sample_names_replace:
  "(.+) \\| align \\| Log.final.out": "\\1"
  "humid \\| (.+) \\| (.+)": "\\1"
  "(.+) \\| log \\| (.+)_umi_tools.log": "\\2"
```

**Comment by ewels** [comment]
Ok nice, great that you got there in the end - congrats for perseverance! 😅 

Closing this as complete now, but if you have any ideas for (generalisable) config syntax that we could use to make this easier, I'd be happy to discuss (here, or in a new issue).
