### ISSUE TITLE
UMI-Tools: support `extract` command

### ISSUE THREAD

**Issue by mschubert** [MultiQC/MultiQC#2284]
### Description of bug

The regexes provided in the UMI-Tools module

https://github.com/MultiQC/MultiQC/blob/d26af5e19c2ebde308bac339fb1b0c3a2dafa99a/multiqc/modules/umitools/umitools.py#L105-L114

do not match the UMI-Tools log file output when using `--extract_method regex` (exact command via _nf-core/rnaseq_ [here](https://github.com/nf-core/rnaseq/issues/1200)). The corresponding log file looks the following (full file attached):

```
2024-01-25 00:20:39,419 INFO Parsed 10000000 reads
2024-01-25 00:20:40,180 INFO Input Reads: 10077011
2024-01-25 00:20:40,180 INFO regex does not match read1: 9215286
2024-01-25 00:20:40,180 INFO regex matches read1: 861725
2024-01-25 00:20:40,180 INFO regex does not match read2: 752463
2024-01-25 00:20:40,180 INFO regex matches read2: 109262
2024-01-25 00:20:40,180 INFO Reads output: 109262
```

MultiQC version: `1.14` (but regexes are the same in latest)
UMI-Tools version: `1.1.4` (latest)

### File that triggers the error

[RMGI_wt_250_48h-3.umi_extract.log](https://github.com/MultiQC/MultiQC/files/14064916/RMGI_wt_250_48h-3.umi_extract.log)

### MultiQC Error log

```console
No error, but UMI-Tools panel is absent.
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [ ] I am using the latest release of MultiQC.
- [ ] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Thanks for the issue! Indeed, The UMI-Tools MultiQC module [only supports](https://multiqc.info/modules/umitools/) the `dedup` command.

I added some basic support for `extract` now with https://github.com/MultiQC/MultiQC/pull/2296, let me know if you have ideas of any better visualisations for it apart from a simple table.

**Comment by mschubert** [comment]
This is great, thanks!

For the vis, I'd probably suggest a bar graph with colors: (1) mismatched read1, (2) matched read1 but mismatched read 2, (3) matched both reads; total of these is the input read number
