### ISSUE TITLE
Copy Table of Custom Content

### ISSUE THREAD

**Issue by GHAStVHenry** [MultiQC/MultiQC#2293]
### Description of bug

Custom content in table plot_type. Copy table button in log copies the section_name, not the table itself. Built in reports copies the tables properly.

### File that triggers the error

[Archive.zip](https://github.com/MultiQC/MultiQC/files/14184900/Archive.zip)

### MultiQC Error log

```console
docker run -v ~/Desktop/multiqc/:`pwd` -w `pwd` multiqc/multiqc:v1.19 multiqc ./inputs/ -c ./multiqc_config.yaml -f 

  /// MultiQC 🔍 | v1.19

|           multiqc | Search path : /Users/ghenry/Desktop/multiqc/inputs
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 2/2  
|    custom_content | sex: Found 1 samples (table)
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Thanks for the bug report @GHAStVHenry. Could you share the input data as well? Looks like the section `anchor` is identical to the table id, making the "Copy Table" callback pick the section header instead of the table. 

I'll try to find a workaround for that and will implement it, but as a quick fix, please make sure to rename the table ID `sex` to `sex-table` or something distinct from the section anchor.

**Comment by GHAStVHenry** [comment]
[Archive.zip](https://github.com/MultiQC/MultiQC/files/14211232/Archive.zip)
zipped is the input file and the custom config...

so it sounds like until you change the target, I can fix on my side by changing the table id to be unique from the section... Thanks!

**Comment by GHAStVHenry** [comment]
...confirmed changing the id of the report fixed the problem

**Comment by vladsavelyev** [comment]
Nice, glad to hear! And the PR https://github.com/MultiQC/MultiQC/pull/2300 above should also fix it more robustly, once merged :)
