### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by serge2016** [MultiQC/MultiQC#2320]
### Description of bug

Here "https://" is doubled:
https://github.com/MultiQC/MultiQC/blob/main/docs/modules/bamdst.md?plain=1#L3

### File that triggers the error

-

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Thank you! Fixing now...
