### ISSUE TITLE
DRAGEN callability metrics are NA

### ISSUE THREAD

**Issue by asalhab** [MultiQC/MultiQC#2326]
### Description of bug

It seems that DRAGEN 4.2.4 reports callability metrics ("Percent Callability" & "Percent Autosome Callability") in two files vc_metrics.csv  and gvcf_metrics.csv (produced if the user activated GVCF option while running DRAGEN).
In the vc_metrics.csv it seems that these two metrics are always NA. While in the gvcf_metrics.csv file these metrics are not NA. Currently MultiQC parses vc_metrics.csv. So,  NA will always be produced in the variant calling section.
<img width="1031" alt="image" src="https://github.com/MultiQC/MultiQC/assets/24413139/298dfa80-6b91-4be8-ac27-a2efb56227db">

Can you consider the other file gvcf_metrics.csv for the callability metrics extraction.

### File that triggers the error

[0201424131.vc_metrics.csv](https://github.com/MultiQC/MultiQC/files/14260888/0201424131.vc_metrics.csv)

example of gvcf_metrics.csv: 
[0201424131.gvcf_metrics.csv](https://github.com/MultiQC/MultiQC/files/14260930/0201424131.gvcf_metrics.csv)

### MultiQC Error log

```console
No Error.
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Thanks for the issue, and for the test data! 

I added support for `gvcf_metrics` with https://github.com/MultiQC/MultiQC/pull/2327

**Comment by asalhab** [comment]
Thank you @vladsavelyev for the quick fix!
I am wondering if your fix replacing **all** vcf metrics with the ones in gvcf? or only the two callability metrics ("Percent Callability" & "Percent Autosome Callability"). In real life these two files are reporting different values though similar metrics (before/after filtering)

**Comment by asalhab** [comment]
I went through your fix. it is clear to me now that gvcf metrics replaces vc ones whenever gvcf is available.
I am wondering if it is possible to report both vc_metrics and gvcf_metrics as both statistics are important and not replacing each other. 
Many thanks!

**Comment by vladsavelyev** [comment]
@asalhab, we can certainly add a separate table for gvcf_metrics when they are available, separate from vc_metrics.

As for the general stats table, would it make sense to show the stats from the gvcf_metrics whenever they are available, otherwise, show the vc_metrics?

<img width="709" alt="Screenshot 2024-02-19 at 12 58 46" src="https://github.com/MultiQC/MultiQC/assets/1575412/4424b9be-6bd2-4887-86f7-2c884c00bac8">

**Comment by asalhab** [comment]
@vladsavelyev Thanks a lot for implementing the two tables.
As for general stats table: it is enough, I believe, to show only the vc_metrics.
