### ISSUE TITLE
MegaQC upload broken on MultiQC>=1.20

### ISSUE THREAD

**Issue by fgvieira** [MultiQC/MultiQC#2331]
### Description of bug

1. Upload any `json` to `megaqc`
2. See error:

```
Traceback (most recent call last):
  File "lib/python3.11/site-packages/megaqc/scheduler.py", line 60, in upload_reports_job
    ret = handle_report_data(user, data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/megaqc/api/utils.py", line 202, in handle_report_data
    config = json.dumps(report_data["report_plot_data"][plot]["config"])
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'config'
```

On `MultiQC 1.20` the structure of the JSON file changed and there is no `config` under each plot.

PS: not sure if this is a MultiQC or MegaQC bug, so also opened it in ewels/MegaQC#518

### MultiQC Error log

```console
MultiQC finishes fine, but the JSON is not recognized by MegaQC (`config` missing under each plot.).
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Thanks @fgvieira for reporting the issue! It seems like we need to adjust MegaQC as well after the switch to Plotly backend in MultiQC. I'll take a look now 👀

**Comment by fgvieira** [comment]
Or maybe just change the `json` structure, so it retains backwards compatibility.

**Comment by ewels** [comment]
https://github.com/MultiQC/MegaQC/pull/519 should be merged soon, so closing this as it's not something we're going to address in this repo.
