### ISSUE TITLE
MultiQC 1.16+bcl2fastq problems

### ISSUE THREAD

**Issue by Stikus** [MultiQC/MultiQC#2336]
### Description of bug

In `MultiQC 1.16+` (either 1.17, 1.18 or 1.19) `bcl2fastq` module got some problems.

- `Clusters by sample` have the different number of samples (1.20 have bigger number, but not all if we plot 300 samples for example):
![image](https://github.com/MultiQC/MultiQC/assets/41360525/8b41ba06-de5c-48ad-870c-4644d7fbcddf)

- `Undetermined barcodes by lane` have stats from only one data folder and broken sorting:
![image](https://github.com/MultiQC/MultiQC/assets/41360525/4fcf576d-4bea-45dd-9487-b9c9b4c7a437)

### File that triggers the error

[inputs_bcl.zip](https://github.com/MultiQC/MultiQC/files/14298882/inputs_bcl.zip)

### MultiQC Error log

```console
bio@bisa07:/mnt/ubm01-raid10/Stik/biotools/multiqc$ docker run --rm -it -v $PWD/inputs_bcl:/inputs -v $PWD/out_1.16_bcl:/outputs --entrypoint multiqc nexus.cspfmba.ru:8443/multiqc:v1.9.0 -o /outputs /inputs

  /// MultiQC 🔍 | v1.16

|           multiqc | MultiQC Version v1.20 now available!
|           multiqc | Search path : /inputs
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 2/2
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | MultiQC complete

bio@bisa07:/mnt/ubm01-raid10/Stik/biotools/multiqc$ docker run --rm -it -v $PWD/inputs_bcl:/inputs -v $PWD/out_1.20_bcl:/outputs --entrypoint multiqc nexus.cspfmba.ru:8443/multiqc:v2.1.0 -o /outputs /inputs

  /// MultiQC 🔍 | v1.20

|           multiqc | Search path : /inputs
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 2/2
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by serge2016** [comment]
It's a problem for me too...

**Comment by vladsavelyev** [comment]
Thanks for creating the issue, @Stikus, and sorry about the bug! There seem to be 2 unrelated problems with the undetermined plot: 
1. The barcodes were not sorted, so instead _top_ 20 barcodes, it just showed the first 20 barcodes it could find in the data. Fixed in https://github.com/MultiQC/MultiQC/pull/2340 now
2. The Plotly barplot version doesn't keep the order of bars, so `sort_samples: False` was not respected, and `Unknown` ended up alphanumerically on the bottom. Fixed in https://github.com/MultiQC/MultiQC/pull/2339

**Comment by vladsavelyev** [comment]
Regarding the "Clusters by sample" though, it seems to be showing all 49 samples for me? Unless I'm missing something.
Note that for larger datasets, not all labels for all samples will fit on the screen, so Plotly will start skipping every other label. If you expand the plot height by dragging the bar handle below the plot, more labels will become visible. Let me know if that was the problem.

**Comment by Stikus** [comment]
@vladsavelyev Thanks for fast fix, I'll check you suggestion about "Clusters by sample" tomorrow and close issue if zooming out help. Main problem was barcodes anyway.

**Comment by Stikus** [comment]
You were correct, it's just label skipping, all good now, thanks
