### ISSUE TITLE
MultiQC 1.20 wrong labels on FastQC Status Checks plot

### ISSUE THREAD

**Issue by Stikus** [MultiQC/MultiQC#2343]
### Description of bug

In `MultiQC 1.20` `FastQC Status Checks` plot got wrong types - numeric-like labels became numeric:
![image](https://github.com/MultiQC/MultiQC/assets/41360525/c9e50664-23ac-4356-9400-c4d8208a9a2b)
![image](https://github.com/MultiQC/MultiQC/assets/41360525/2bf24716-6cf5-40da-a503-6c68a6b9c6f4)

### File that triggers the error

[inputs_fastqc.zip](https://github.com/MultiQC/MultiQC/files/14309252/inputs_fastqc.zip)

### MultiQC Error log

```console
bio@bisa07:/mnt/ubm01-raid10/Stik/biotools/multiqc$ docker run --rm -it -v $PWD/inputs_fastqc/:/inputs -v $PWD/out_1.20_fastqc:/outputs --entrypoint multiqc multiqc:v2.1.0 -o /outputs /inputs

  /// MultiQC 🔍 | v1.20

|           multiqc | Search path : /inputs
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 17/17
|            fastqc | Found 1 reports
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by serge2016** [comment]
I also have sample IDs like `040000100101`, and files like `040000100101.bam`... It's a problem for me too.

**Comment by vladsavelyev** [comment]
Oh, thanks for pointing at this. Nasty edge case 😬  Fixing now.
