### ISSUE TITLE
Release version / stored hash mismatch in MultiQC wheel?

### ISSUE THREAD

**Issue by RandyHarr** [MultiQC/MultiQC#2345]
### Description of bug

Doing a fresh install via PIP of MultiQC now generates a release version and stored hash mismatch from the MultiQC wheel.

### File that triggers the error

python -m pip install multiqc

### MultiQC Error log

```console
During install. Pip error.

ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.               
kaleido from https://files.pythonhosted.org/packages/f7/9a/0408b02a4bcb3cf8b338a2b074ac7d1b2099e2b092b42473def22f7b625f/kaleido-0.2.1-py2.py3-none-win_amd64.whl (from multiqc):
        Expected sha256 4670985f28913c2d063c5734d125ecc28e40810141bdb0a46f15b76c1d45f23c
             Got        41014e64512c493ba3c5b4eb48c3ec89c39eed386ed62bc9fbd894695890e5d7
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Hmm, I cannot reproduce this... What happens if you try with `--no-cache-dir`?

```sh
python -m pip install --no-cache-dir multiqc
```

Alternatively, install into a clean env. Or try removing `kaleido` and retrying.

**Comment by RandyHarr** [comment]
It seems something got patched because a fresh install today is working just fine. It consistently failed two days ago on two different windows machines (10 Home 22H2 19045.4046 and 11 Pro 23H2 build 22635.3149)

Fresh, clean machine (first installs).
Installs Python 3.10.2 from python.org
Then issues the PIP command to install: Pillow pyliftover pyscreenshot openpyxl pandas psutil multiqc wakepy
(python is installed from a .bat cmd.exe file and pip is run from a cygwin64 BASH shell file that is forked from it.)

$ pip show kaleido:
Name: kaleido
Version: 0.2.1
Summary: Static image export for web-based visualization libraries with zero dependencies
Home-page: UNKNOWN
Author: Jon Mease
Author-email: jon@plotly.com
License: MIT

$ ./pipdeptree
msvc-runtime==14.29.30133
multiqc==1.20
├── click [required: Any, installed: 8.1.7]
│   └── colorama [required: Any, installed: 0.4.6]
├── coloredlogs [required: Any, installed: 15.0.1]
│   └── humanfriendly [required: >=9.1, installed: 10.0]
│       └── pyreadline3 [required: Any, installed: 3.4.1]
├── humanize [required: Any, installed: 4.9.0]
├── importlib-metadata [required: Any, installed: 7.0.1]
│   └── zipp [required: >=0.5, installed: 3.17.0]
├── Jinja2 [required: >=3.0.0, installed: 3.1.3]
│   └── MarkupSafe [required: >=2.0, installed: 2.1.5]
├── kaleido [required: Any, installed: 0.2.1]
├── Markdown [required: Any, installed: 3.5.2]
├── matplotlib [required: >=2.1.1, installed: 3.8.3]
│   ├── contourpy [required: >=1.0.1, installed: 1.2.0]
│   │   └── numpy [required: >=1.20,<2.0, installed: 1.26.4]
│   ├── cycler [required: >=0.10, installed: 0.12.1]
│   ├── fonttools [required: >=4.22.0, installed: 4.49.0]
│   ├── kiwisolver [required: >=1.3.1, installed: 1.4.5]
│   ├── numpy [required: >=1.21,<2, installed: 1.26.4]
│   ├── packaging [required: >=20.0, installed: 23.2]
│   ├── pillow [required: >=8, installed: 10.2.0]
│   ├── pyparsing [required: >=2.3.1, installed: 3.1.1]
│   └── python-dateutil [required: >=2.7, installed: 2.8.2]
│       └── six [required: >=1.5, installed: 1.16.0]
├── networkx [required: >=2.5.1, installed: 3.2.1]
├── numpy [required: Any, installed: 1.26.4]
├── packaging [required: Any, installed: 23.2]
├── pillow [required: >=10, installed: 10.2.0]
├── plotly [required: Any, installed: 5.19.0]
│   ├── packaging [required: Any, installed: 23.2]
│   └── tenacity [required: >=6.2.0, installed: 8.2.3]
├── pyaml-env [required: Any, installed: 1.2.1]
│   └── PyYAML [required: >=5.0,<=7.0, installed: 6.0.1]
├── PyYAML [required: >=4, installed: 6.0.1]
├── requests [required: Any, installed: 2.31.0]
│   ├── certifi [required: >=2017.4.17, installed: 2024.2.2]
│   ├── charset-normalizer [required: >=2,<4, installed: 3.3.2]
│   ├── idna [required: >=2.5,<4, installed: 3.6]
│   └── urllib3 [required: >=1.21.1,<3, installed: 2.2.1]
├── rich [required: >=10, installed: 13.7.0]
│   ├── markdown-it-py [required: >=2.2.0, installed: 3.0.0]
│   │   └── mdurl [required: ~=0.1, installed: 0.1.2]
│   └── pygments [required: >=2.13.0,<3.0.0, installed: 2.17.2]
├── rich-click [required: Any, installed: 1.7.3]
│   ├── click [required: >=7, installed: 8.1.7]
│   │   └── colorama [required: Any, installed: 0.4.6]
│   ├── rich [required: >=10.7.0, installed: 13.7.0]
│   │   ├── markdown-it-py [required: >=2.2.0, installed: 3.0.0]
│   │   │   └── mdurl [required: ~=0.1, installed: 0.1.2]
│   │   └── pygments [required: >=2.13.0,<3.0.0, installed: 2.17.2]
│   └── typing-extensions [required: Any, installed: 4.9.0]
└── spectra [required: >=0.0.10, installed: 0.0.11]
    └── colormath [required: >=3.0.0, installed: 3.0.0]
        ├── networkx [required: >=2.0, installed: 3.2.1]
        └── numpy [required: Any, installed: 1.26.4]
Location: d:\wgsextractv4\python\lib\site-packages
Requires:
Required-by: multiqc

MultiQC is the only package with the kaleido dependency in it.  It also is the only package with more than 3 dependencies in it. Guess not surprising given all it does. But does make it more susceptible to hiccups as those packages get updated and patched. (Not sure what the wheel has set in terms of versions of packages.)

I had not checked the installations on MacOS (various versions) nor Linux (Ubuntu, SUSE, etc) at the time to verify it was working there. They are working today as well.

**Comment by vladsavelyev** [comment]
Thanks for checking again! 🙏
