### ISSUE TITLE
No analysis results found for fastp json files

### ISSUE THREAD

**Issue by pdimens** [MultiQC/MultiQC#2365]
### Description of bug

Multiqc (v1.20) does not recognize fastp json files, resulting in a `No analysis results found` and exiting. 
```
$ tree QC/logs/json
QC/logs/json
├── sample1.json
└── sample2.json

1 directory, 2 files
```

### File that triggers the error

[sample1.json](https://github.com/MultiQC/MultiQC/files/14375561/sample1.json)

### MultiQC Error log

```console
$ multiqc QC/logs/json -m fastp        

  /// MultiQC 🔍 | v1.20 (c0e4873)

|           multiqc | Only using modules: fastp
|           multiqc | Search path : /home/pdimens/Documents/harpy/QC/logs/json
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━ 100% 2/2 
|           multiqc | No analysis results found. Cleaning up..
|           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Thank you for the bug report, and sorry about the issue @pdimens! This should be fixed with https://github.com/MultiQC/MultiQC/pull/2334, will be part of the next release within a few days.

**Comment by vladsavelyev** [comment]
@arupgsh - new release tomorrow!
