### ISSUE TITLE
In Bcftools module add multi allelic sites metrics into the general stats

### ISSUE THREAD

**Issue by solcos** [MultiQC/MultiQC#2383]
### Description of feature

In the bcftools module, add the metric 'number of multiallelic sites' and 'number of multiallelic SNP sites' into the general stats table to also be able to see those metrics. 

Thanks in advance :)

**Comment by vladsavelyev** [comment]
Thanks for the request! Added in https://github.com/MultiQC/MultiQC/pull/2414
