### ISSUE TITLE
Add option for graphs to shift legend back to bottom instead of right

### ISSUE THREAD

**Issue by rarthur-eicc** [MultiQC/MultiQC#2390]
### Description of feature

Hi, since MultiQC 1.20, the graphs output (such as those for fastq-screen, STAR, bowtie2, etc) now have a legend on the right where as before, they were all on the bottom. This does not look as good in slideshows, writeups for manuscripts, et cetera. Is there an option to move graph legends back to the bottom? 

Thank you.

**Comment by vladsavelyev** [comment]
We do not place the legend on the bottom anymore, as the new backend (Plotly) doesn't work well with it when you resize plots vertically, and we want to support interactivity.

However, we can add it a config option, see: https://github.com/MultiQC/MultiQC/pull/2397

```yaml
barplot_legend_on_bottom: true
```

<img width="1136" alt="Screenshot 2024-02-27 at 22 21 46" src="https://github.com/MultiQC/MultiQC/assets/1575412/be4283e7-2c36-4205-ac36-61d7dbffdc6d">

**Comment by rarthur-eicc** [comment]
Cool about the interactivity thing, but often in science things have to be shrunk to fit onto “paper” eg a manuscript in Word or a PDF. Then, having a legend on the right distorts the graph and makes it shrunken along the X axis and less legible. Some extra white space vertically isn’t a deal breaker, but distorted graphs kind of is for publications. It isn’t just about digital analysis or html files as this is science after all.

Thanks for the toggle flag being eventually added though. Does one just need to place that line anywhere in the config?
