### ISSUE TITLE
[question]: How to obtain separate sample-wise table with Picard in MultiQC 1.21

### ISSUE THREAD

**Issue by tamuanand** [MultiQC/MultiQC#2416]
Hi @ewels  and @vladsavelyev 

https://github.com/MultiQC/MultiQC/releases/tag/v1.21 says this for Picard

```
add a separate sample-wise table instead of general stats
```

I do not see this feature on this example either  under the Picard tab - https://multiqc.info/example-reports/whole-genome-seq/

How do I get this feature with a `multiqc 1.21 run` 

I ran this below on a folder with Picard MarkDuplicates files  (duplicates_metrics) - the files have the content `## METRICS CLASS        picard.sam.DuplicationMetrics` 
- I could not see a separate sample-wise table for Picard. I could see all the Picard related stats in the General stats table and they were reported sample-wise (which has been the case all along)

Do I need to do anything different to be able to see the sample-wise table? Or am I misreading something on the release notes?
```
docker run -t -v `pwd`:`pwd` -w `pwd` quay.io/biocontainers/multiqc:1.21--pyhdfd78af_0 multiqc .  --force --interactive 
```

Thanks

**Comment by vladsavelyev** [comment]
Hi @tamuanand, that's just for the `CrosscheckFingerprints` tool. Other picard tools keep the same tables and plots as in 1.20.
