### ISSUE TITLE
Null value for Median Autosomal Coverage

### ISSUE THREAD

**Issue by fsharifi** [MultiQC/MultiQC#2423]
### Description of bug

Hello! 

Thank you so much for developing this great tool 

I noticed that when I use Multiqc v1.21 there are 31 null values (when I used  v1.17 on the same Dragen outputs, I got 28 null values.). The 3 extra values are "autosomal_median_coverage", "x_median_coverage" and "y_median_coverage". 

The Dragen Coverage Metrics has Median autosomal coverage over **genome**, but it seems that Coverage_metrics.py only recognizes over **region**

 I'd appreciate it if you'd fix this or help me to fix it on my end. 
 

### MultiQC Error log

```console
$ multiqc .
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Hi! It would be helpful if you could share a reproducible example. DRAGEN is a giant toolset with so many options and commands, so we could have easily missed some scenario, or there might be some configuration option to enable what you want. Without an example, it's hard to tell.

**Comment by fsharifi** [comment]
Apologies for my late response. I added a sample input (it's not real data, but generates similar output).

I noticed that the missing values belong to the ploidy estimation, not the coverage metrics.
I think it's related to this commit; because ploidy estimation was empty, all the ploidy estimation outputs were excluded (e.g. autosomal median coverage): 

https://github.com/MultiQC/MultiQC/pull/2341

**V1.21:**

grep "ploidy" multiqc_data/multiqc_data.json 

            "ploidy_estimation_metrics": {

                "Sample": "/work_dir/test/Sample.ploidy_estimation_metrics.csv"

        "dragen_ploidy": {

**V1.17:** 

    "ploidy_estimation_metrics": {

                "Sample": "/work_dir/test/Sample.ploidy_estimation_metrics.csv"

                "description": "Sex chromosome ploidy estimation (XX, XY, X0, 00, etc.)",

                "rid": "mqc-generalstats-dragen_ploidy_estimation-Ploidy_estimation",

        "dragen_ploidy": {

                "DRAGEN: Ploidy estimation_mqc-generalstats-dragen_ploidy_estimation-Ploidy_estimation": ""

[Sample.ploidy_estimation_metrics.csv](https://github.com/MultiQC/MultiQC/files/14705481/Sample.ploidy_estimation_metrics.csv)

**Comment by fsharifi** [comment]
Could you please kindly re-open this issue?

**Comment by fsharifi** [comment]
Hi vladsavelyev, 

When I use v1.21, and the ploidy estimation is missing, the "report general stats data" in multiqc_data.json is empty. A few days ago, I changed if stat.strip() == "": in the ploidy_estimation_metrics.py to if stat.strip() == "asdfghjkl": (a condition that never satisfies so that the code outputs the ploidy_estimation even if it's missing). With this minor change, I was able to output all the data (e.g. Median autosomal coverage) from Sample.ploidy_estimation_metrics.csv  in "report general stats data". 

Original code: 
<img width="194" alt="IgnoreNullPloidy " src="https://github.com/MultiQC/MultiQC/assets/16109055/c39b1e23-9a1a-4ab2-b74a-016122147aac">

After changing line 62: 
<img width="345" alt="OutoutNullPloidy" src="https://github.com/MultiQC/MultiQC/assets/16109055/fa241f52-586c-4ff0-bacd-7c8c89c951bd">
