### ISSUE TITLE
Exported deseq2 PCA plots and datasets do not include sample labels

### ISSUE THREAD

**Issue by vmkalbskopf** [MultiQC/MultiQC#2439]
### Description of bug

As you can see below, the exported plot and data from the deseq2 PCA is not usable because none of the samples are labelled.  This should perhaps be a feature request, and not a bug report though..

![star_salmon_deseq2_pca-plot](https://github.com/MultiQC/MultiQC/assets/22935643/11fa19b4-ee41-4e35-9cde-493a1246019a)

```
"PC1"	"Series 1"
-102.467271206518	27.923708398388
-4.23130544001009	-12.6205829130423
0.455709768139468	-35.4279624016899
2.23438188038342	-12.1784084187019
11.9217517635194	-17.7115257418383
12.6585279095652	-41.3035085323039
38.6164160215699	64.5209702222353
40.811789303351	26.7973093869531
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
I don't think we have a built-in module for DESeq2? I wonder if you are using a custom plug in, a custom MultiQC fork, or custom content. Would be great if you could help reproduce the issue!

**Comment by vmkalbskopf** [comment]
This is a plot produced by the nf-core/rnaseq pipeline. You can see [example output](https://nf-co.re/rnaseq/3.17.0/results/rnaseq/results-00f924cf92a986a842bb352b3c4ae379c773c989/aligner_star_salmon/multiqc/star_salmon/) and steps to reproduce using [the pipeline](https://nf-co.re/rnaseq/3.17.0/).
