### ISSUE TITLE
Custom Content Table is not Table

### ISSUE THREAD

**Issue by erinyoung** [MultiQC/MultiQC#2440]
### Description of bug

I have a csv file that I'd like to add as a table to a multiqc report. Since this is custom content, I've added lines to the top of the files for multiqc. This file, however, is getting rendered as a type of plot.

This is the plot that gets generated, which is not a table.
![fastani-plot](https://github.com/MultiQC/MultiQC/assets/28793649/67b41682-b04f-468f-9293-5cf08f2b92b6)

Is there something wrong with my headers?

### File that triggers the error

[fastani_mqc.csv](https://github.com/MultiQC/MultiQC/files/14591969/fastani_mqc.csv)

### MultiQC Error log

```console
/// MultiQC 🔍 | v1.21

|           multiqc | Search path : /Volumes/IDGenomics_NAS/Bioinformatics/eriny/testing_grandeur/2024-03-12/work/11/d7480f2f6e19297c0301888be06fa0
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 110/110  
|    custom_content | drprg: Found 1 samples (table)
|    custom_content | circulocov: Found 1 samples (table)
|    custom_content | elgato: Found 1 samples (table)
|    custom_content | emmtyper: Found 1 samples (table)
|    custom_content | mash: Found 1 samples (bargraph)
|    custom_content | fastani: Found 1 samples (table)
|    custom_content | shigatyper_hits: Found 1 samples (table)
|    custom_content | shigatyper: Found 1 samples (table)
|    custom_content | amrfinderplus: Found 1 samples (table)
|    custom_content | kaptive: Found 1 samples (table)
|    custom_content | kleborate: Found 1 samples (table)
|    custom_content | mlst: Found 1 samples (table)
|    custom_content | pbptyper: Found 1 samples (table)
|    custom_content | plasmidfinder: Found 1 samples (table)
|    custom_content | seqsero2: Found 1 samples (table)
|    custom_content | serotypefinder: Found 1 samples (table)
|    custom_content | mykrobe: Found 1 samples (table)
|             bbmap | Found 7 reports
|             fastp | Found 7 reports
|            fastqc | Found 14 reports
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by erinyoung** [comment]
Never mind! I found the error that said that my table was too large.

Is there documentation somewhere that indicates how large a table can be?

**Comment by vladsavelyev** [comment]
@erinyoung, it's documented here: https://multiqc.info/docs/getting_started/config/#tables--violin-plots

The `max_table_rows` config option controls at what about of samples a table will be replaced with a violin plot (which unfortunately in your case looks ugly because it doesn't expand for long non-numeric ticks, but that's something we we'll fix eventually).

So to revert to a table, consider setting `max_table_rows` to a high value, e.g.

```yaml
max_table_rows: 1000
```

In `multiqc_config.yaml`

Or 

```sh
multiqc --cl-config "max_table_rows: 1000"`
```

See https://multiqc.info/docs/getting_started/config/#configuring-multiqc for all configuration options
