### ISSUE TITLE
Regression: BUSCO Coloring

### ISSUE THREAD

**Issue by schorlton** [MultiQC/MultiQC#2450]
### Description of bug

The colors were made very pretty in https://github.com/MultiQC/MultiQC/pull/1817

I do appreciate that the hex codes were simply copied over with the plotly update (MultiQC v1.20); however, there appears to be a regression where they don't actually match what we had before and the colors are not discernible nor reflect the spirit of the original coloring.

v1.19:
![image](https://github.com/MultiQC/MultiQC/assets/10245822/16ecd03b-ddfb-47c1-ba01-bf4b96930604)

v1.20:
![image](https://github.com/MultiQC/MultiQC/assets/10245822/069a3672-b4d8-4d5c-a573-7edb00dd63cf)

Thanks for your help in investigating!

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Sorry about this issue, and thanks for reporting!

It's a pretty elusive one as it seems to appear rarely. Fixed with https://github.com/MultiQC/MultiQC/pull/2453

**Comment by schorlton** [comment]
Awesome, thanks!
