### ISSUE TITLE
A method for a generic table

### ISSUE THREAD

**Issue by lskatz** [MultiQC/MultiQC#2459]
### Description of feature

Many tools just output a simple tab separated values (TSV) file. I wanted to see if I could just have a custom table or set of tables in my MultiQC report. For example, I could give a table with E. coli serogroup values like so

```
sample       O     H
SRR28368091  O26   H11
SRR28368090  O100  H30
```

Could I have this table imported? I understand that one of the neat parts of MultiQC is that it automatically finds results files, but maybe this could be an extra option like

```
multiqc metrics_dir --tsv table1.tsv --tsv table2.tsv --tsv table3.tsv...
```

And I think it could be understandable that there needs to be some restrictions, like if the first field must have a header `sample`. Please let me know if this already exists or if it is a useful feature. Thank you for this software!

**Comment by ewels** [comment]
Hi @lskatz,

This is already possible - just rename your file `table1_mqc.tsv` and it should "just work". It's also possible to do it without renaming if you use a MultiQC config to say where to find these files. 

This feature is called "Custom Config". See the docs here: https://multiqc.info/docs/custom_content/

Phil

**Comment by lskatz** [comment]
Thank you for highlighting this! I am excited to try it out!

**Comment by ewels** [comment]
Great! Shout on the community.seqera.io forum if you need any help :)
