### ISSUE TITLE
mosdepth module: allow representing in full coverages < 1X in the General Stats table

### ISSUE THREAD

**Issue by lbeltrame** [MultiQC/MultiQC#2468]
### Description of feature

While it may seem a non-sense at first, shallow whole genome sequencing (sWGS) has coverages that range between 0.1 and 1X. At this time, MultiQC will report a mean coverage of 0.0X if the coverage is below 1X, although the summary file from mosdepth provides correctly values < 0 (from 0.5 to 0.35 with the samples I've tested it with). 

If this is already possible, at best the documentation should be amended.

Picard has the same problem, but the issue there lies in the software, not in MultiQC.

**Comment by vladsavelyev** [comment]
Thanks for reporting the issue @lbeltrame. Do you happen to have an example of mosdepth output with shallow coverage handy?

**Comment by lbeltrame** [comment]
I can produce one from data I published myself which is already public. Would the summary suffice?

**Comment by vladsavelyev** [comment]
I created a toy bam file with the 0.4x average coverage. MultiQC seems to report that correctly. The general stats and the Cumulative coverage distribution plot make sense too.

I noticed that the "Coverage distribution" with absolute coverage values skips the first data point so it doesn't work on my toy example, but I fixed that. It makes sense to me too:

[shallow_cov_mosdepth.zip](https://github.com/MultiQC/MultiQC/files/14981076/shallow_cov_mosdepth.zip)

![CleanShot 2024-04-15 at 17 22 48@2x](https://github.com/MultiQC/MultiQC/assets/1575412/be1d4c02-8caf-4855-855a-8910e37f731b)

**Comment by lbeltrame** [comment]
The median in the table seems a bit off to me (0.0X) though. I have attached a file here with the summary data (which reports the fractional coverage: I made these back in the days for a publication (now out, so no problem with that). I also have the coverage distribution if required.. 
[106.mosdepth.summary.txt](https://github.com/MultiQC/MultiQC/files/14987454/106.mosdepth.summary.txt)

**Comment by vladsavelyev** [comment]
The median is calculated from the coverage distribution, and in my toy example 0.0 _is_ the median coverage.

In your example, the module can only calculate mean, and it looks correct'ish?

![CleanShot 2024-04-16 at 21 14 05@2x](https://github.com/MultiQC/MultiQC/assets/1575412/49c31389-f75f-48fa-94f4-3a4b88fdd0bd)

Feel free to send a pull request for the mosdepth module, if you believe it miscalcualtes something or rounds things up incorrectly.
