### ISSUE TITLE
Exporting plots not working

### ISSUE THREAD

**Issue by jedpe-ucla** [MultiQC/MultiQC#2470]
### Description of bug

When using the --export flag, the plots are not being saved as static images. I was also led to believe by the comments [here](https://github.com/MultiQC/MultiQC/issues/717) that the raw data used for these plots would be saved on the multiqc_data folder which is also not happening.

### File that triggers the error

I tested this using the data for the RNA-Seq sample report.

[data.zip](https://github.com/MultiQC/MultiQC/files/14842759/data.zip)

### MultiQC Error log

```console
$ multiqc --export --data-format tsv .
  /// MultiQC � | v1.21

|           multiqc | Search path : /u/scratch/j/jorpena/data
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 121/121
|    feature_counts | Found 8 reports
|              star | Found 8 reports
|          cutadapt | Found 16 reports
|            fastqc | Found 32 reports
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | Plots       : multiqc_plots
|           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by jedpe-ucla** [comment]
This seemed to have been introduced with v1.20 since this worked for me on v1.19

**Comment by vladsavelyev** [comment]
Good catch! Sorry about this issue and thanks a lot for reporting. Fixed now with https://github.com/MultiQC/MultiQC/pull/2489

Note that `--export` and `--data-format` are two independent options:

* `--export` makes MultiQC write static versions of plots in png, svg and pdf format, and puts them into `multiqc_plots`. This is disabled by default.
* `--data-format` controls the format used for exporting plot data (`tsv`, `csv` or `json`). This is enabled by default and defaults to `tsv` (though the output files have the `.txt` extension).

Both options can be combined.

(that above is the desired behavior which was broken, but restored with https://github.com/MultiQC/MultiQC/pull/2489)
