### ISSUE TITLE
use JSON format for config file

### ISSUE THREAD

**Issue by stevekm** [MultiQC/MultiQC#2471]
### Description of feature

Instead of using YAML for the MultiQC Config File, it would be really helpful if we could instead use JSON.

The reason for this is that indentation errors are a common problem with any complex datastructure representation in YAML. That is the cause of this issue here; https://github.com/MultiQC/MultiQC/issues/2156

I just spent several hours debugging MultiQC only to get hit by this YAML indentation issue again. The problem being of course that "valid YAML" indentation ends up not actually being accepted and recognized by the program, leading to silent errors such as the config directives being ignored.

This is not an issue inherent to MultiQC; I have experienced it many times in the past with other frameworks that rely on YAML format documents.

This is an issue that does not happen with JSON, where indentation does not matter. If JSON had been available, it would have saved me many hours of headaches just now, and likely saved lots of headaches for others. 

Thanks.

**Comment by vladsavelyev** [comment]
Hi @stevekm - I see, that makes sense. I'd rather look into supporting [TOML](https://toml.io/en/) as the more popular format for configurations, which is more human-friendly than JSON but doesn't suffer from indentation issues like YAML.

**Comment by vladsavelyev** [comment]
Closing for now as low-priority, but will look into supporting TOML long-term.
