### ISSUE TITLE
Add "ge" and "le" comparisons to conditional formatting rules

### ISSUE THREAD

**Issue by briankegerreis** [MultiQC/MultiQC#2481]
### Description of feature

It would be nice to have "greater than or equal" to or "less than or equal to" comparisons when doing conditional formatting. Not too hard to force that behavior with a combination of comparisons, but it's ugly:
```
cond_formatting_rules:
  pass: [lt: 5]
  warn: [eq: 5, gt: 5]
```

**Comment by vladsavelyev** [comment]
Thanks for the suggestion! Added with https://github.com/MultiQC/MultiQC/pull/2494
