### ISSUE TITLE
Could you please add DRAGEN gvcf metrics to the general stats? 

### ISSUE THREAD

**Issue by fsharifi** [MultiQC/MultiQC#2482]
### Description of feature

I'm using a tool called TidyMultiqc to convert multi_data.json to multi_data.csv, but it seems that TidyMultiqc only outputs the general stat metrics from multiqc_data.json, so it would be helpful if gvcf metrics would be added to general stat also.  

https://github.com/MultiQC/MultiQC/pull/2327
https://github.com/multimeric/TidyMultiqc

**Comment by ewels** [comment]
If you just need a CSV file, can you not use some of the outputs MultiQC itself generates within the `multiqc_data` directory? There should be a file (or files) for DRAGEN there which include this metric already.

**Comment by fsharifi** [comment]
Hi Phil, I just looked at those files, and it seems that I can use the dragen_gvcf_metrics.txt separately or combined with other text files (or combined with TidyMultiqc output). Thank you so much for the suggestion.
