### ISSUE TITLE
ignore pass/fail/warning from FastQC module

### ISSUE THREAD

**Issue by a-frantz** [MultiQC/MultiQC#2483]
### Description of feature

Within each analysis, the FastQC module tags each sample as pass, fail, or with warning(s). Our team would prefer to make those determinations ourselves, as we frequently disagree with the status labelled by FastQC. We find these labels at best unhelpful and at worst misleading. We'd prefer it if these statuses could just be wholesale ignored when MultiQC is parsing the data. This would also render the "Status Checks" heatmap useless.

Thanks.

**Comment by vladsavelyev** [comment]
Thanks for the suggestion, @a-frantz. 

That makes sense - however I wouldn't want the status checks to be ignored by default, so I added it as an option: https://github.com/MultiQC/MultiQC/pull/2486. After this PR is merged, if you add this section into a [config](https://multiqc.info/docs/getting_started/config/#configuring-multiqc), MultiQC will ignore all stats checks from FastQC:

```yaml
fastqc_config:
  status_checks: false
```

**Comment by a-frantz** [comment]
Thank you @vladsavelyev ! I appreciate the speedy response :)
