### ISSUE TITLE
qc3c unable to recognize the sample name

### ISSUE THREAD

**Issue by Rohit-Satyam** [MultiQC/MultiQC#2500]
### Description of bug

Multiqc is unable to identify the sample name from the qc3c output files and gives "." in the table and graphs

### File that triggers the error

[multiqc_data.zip](https://github.com/MultiQC/MultiQC/files/15076518/multiqc_data.zip)

### MultiQC Error log

```console
multiqc -f --fullnames .

  /// MultiQC 🔍 | v1.21

|           multiqc | Not cleaning sample names
|           multiqc | Search path : /data/coursework2024/exam/output
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 6/6  
|              qc3C | Found 1 reports
|           multiqc | Report      : multiqc_report.html   (overwritten)
|           multiqc | Data        : multiqc_data   (overwritten)
|           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Sorry about this issue!

Fixing with: https://github.com/MultiQC/MultiQC/pull/2502

The context: the `qc3C` module takes the sample name from the parent folder name. See, for example at https://github.com/MultiQC/test-data/tree/main/data/modules/qc3C/bam_out/DRR177157

```
- DRR177157/
    - report.qc3C.json
```

The sample name would be `DRR177157`

However, that works if you pass the directory by name:

```
multiqc -fv DRR177157
```

And doesn't work if you pass the cwd:

```
cd DRR177157
multiqc -fv .
```

Fixed that now.
