### ISSUE TITLE
Add ngs-bits SampleGender output to MultiQC

### ISSUE THREAD

**Issue by peterpru** [MultiQC/MultiQC#2507]
### Name of the tool

ngs-bits SampleGender

### Tool homepage

https://github.com/imgag/ngs-bits

### Tool description

ngs-bits is a collection of tools. SampleGender determines the gender of a sample from the BAM/CRAM file.

### Tool output

[sample_ngsbits_sex.tsv.zip](https://github.com/MultiQC/MultiQC/files/15107146/sample_ngsbits_sex.tsv.zip)

### Before submitting

- [X] I have included example data (zipped, not pasted) that can be used to write the module.

**Comment by peterpru** [comment]
PR opened here: https://github.com/MultiQC/MultiQC/pull/2854

**Comment by peterpru** [comment]
Completed

**Comment by bounlu** [comment]
There is a bug in parsing the NGSbits SampleGender output by MultiQC. For the default 'xy' method, there is a gray area where the gender cannot be called with confidence, and this is parsed as string rather than numeric values for "reads_chrx/y" columns. See below for an example:

```
Sample	gender	reads_chry	reads_chrx	ratio_chry_chrx
Sample1	female	2534.0	86850.0	0.0292
Sample2	female	2184.0	77990.0	0.028
Sample3	female	2748.0	95368.0	0.0288
Sample4	female	2440.0	86396.0	0.0282
Sample5	unknown	(ratio	in	gray
Sample6	unknown	(ratio	in	gray
Sample7	unknown	(ratio	in	gray
Sample8	unknown	(ratio	in	gray
Sample9	unknown	(ratio	in	gray
```

**Comment by ewels** [comment]
Please open this as a new issue, using the issue template for reporting bugs. Thanks!
