### ISSUE TITLE
Could not figure out read 2 length from RunInfo.xml

### ISSUE THREAD

**Issue by nick-youngblut** [MultiQC/MultiQC#2508]
### Description of bug

Running MultiQC on bcl-convert output.

The error:

```
    /// MultiQC 🔍 | v1.21

  |           multiqc | Search path : /home/nickyoungblut/tmp/auto-demux/work/20240424_SspArc0134/98/59d4ff8cb59bcad571ae8e5cb0cad5
  |         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 12/12
  |        bclconvert | Could not figure out read 2 length from RunInfo.xml
  |           multiqc | No analysis results found. Cleaning up..
  |           multiqc | MultiQC complete
```

The top of the RunInfo.xml file:

```
<?xml version="1.0"?>
<RunInfo Version="6">
	<Run Id="240425_VH00848_69_AACGH3VHV" Number="69">
		<Flowcell>AACGH3VHV</Flowcell>
		<Instrument>VH00848</Instrument>
		<Date>2024-04-25T00:14:06Z</Date>
		<Reads>
			<Read Number="1" NumCycles="100" IsIndexedRead="N" IsReverseComplement="N"/>
			<Read Number="2" NumCycles="22" IsIndexedRead="N" IsReverseComplement="N"/>
		</Reads>
		<FlowcellLayout LaneCount="2" SurfaceCount="2" SwathCount="6" TileCount="14">
			<TileSet TileNamingConvention="FourDigit">
				<Tiles>
					<Tile>1_1101</Tile>
					<Tile>1_1102</Tile>
					<Tile>1_1103</Tile>
```

The RunInfo.xml file clearly shows the read 2 length, so it appears that MultiQC has a bug, or at least is generating a misleading error message.

### MultiQC Error log

```console
`multiqc -f -n multiqc_report.html -o . .`


    /// MultiQC 🔍 | v1.21

  |           multiqc | Search path : /home/nickyoungblut/tmp/auto-demux/work/20240424_SspArc0134/98/59d4ff8cb59bcad571ae8e5cb0cad5
  |         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 12/12
  |        bclconvert | Could not figure out read 2 length from RunInfo.xml
  |           multiqc | No analysis results found. Cleaning up..
  |           multiqc | MultiQC complete
```
```


### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by nick-youngblut** [comment]
It appears that the bcl-convert module of MultiQC is making the assumption that there are at least 3 `<Read/>` entries in the `<Reads>` block (the [code](https://github.com/MultiQC/MultiQC/blob/196c9738f5d12549ef787f7f03b22af2c8e62113/multiqc/modules/bclconvert/bclconvert.py#L248)).

**Comment by vladsavelyev** [comment]
Thanks a lot for the bug report @nick-youngblut! 

This should fix it: https://github.com/MultiQC/MultiQC/pull/2511 (and potentially other bugs related to uncommon combination of index and non-index reads).

Before I merge, can you please add your test example to https://github.com/ewels/MultiQC_TestData to make sure the fix works?

**Comment by nick-youngblut** [comment]
> Before I merge, can you please add your test example to https://github.com/MultiQC/test-data to make sure the fix works?

I'm not sure where to put the file or how to name it. Should it go in https://github.com/MultiQC/test-data/tree/main/data/modules/bclconvert/3.9.3? 

The RunInfo.xml file is simply:

```
<?xml version="1.0"?>
<RunInfo xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="2">
  <Run Id="240426_M08192_0060_000000000-LDGFF" Number="60">
    <Flowcell>000000000-LDGFF</Flowcell>
    <Instrument>M08192</Instrument>
    <Date>240426</Date>
    <Reads>
      <Read NumCycles="514" Number="1" IsIndexedRead="N" />
      <Read NumCycles="86" Number="2" IsIndexedRead="N" />
    </Reads>
    <FlowcellLayout LaneCount="1" SurfaceCount="2" SwathCount="1" TileCount="19" />
  </Run>
</RunInfo>
```

...or any other RunInfo.xml file that just includes:

```
    <Reads>
      <Read NumCycles="XXX" Number="1" IsIndexedRead="N" />
      <Read NumCycles="XXX" Number="2" IsIndexedRead="N" />
    </Reads>
```

...will result in the same MultiQC error:

```
/// MultiQC 🔍 | v1.21

|           multiqc | Search path : /home/nickyoungblut/tmp/auto-demux/work/20240426_SspArc0132/ea/6004aadcfc537522af64ea0646fcf0
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 12/12
|        bclconvert | Could not figure out read 2 length from RunInfo.xml
|           multiqc | No analysis results found. Cleaning up..
|           multiqc | MultiQC complete
```

**Comment by vladsavelyev** [comment]
The location doesn't matter, you can even attach them here to a comment. 

I really just wanted to test on a real life output with this set up, to see if other files would break as well (e.g. Quality_Metrics.csv, Adapter_Metrics.csv).

Also, not relevant for Xml, but generally it's better to attach files as is, rather than copy the contents into a comment, because GitHub messes with spacing, and for many file types the concrete form of indentation matters.

**Comment by nick-youngblut** [comment]
@vladsavelyev any idea when the new release of MultiQC will be published? I am using the MultiQC biocontainer for my Nextflow pipeline, and I'd rather use the biocontainer versus creating a custom Docker container with the most recent version of MultiQC.
