### ISSUE TITLE
Cannot run multiqc

### ISSUE THREAD

**Issue by sjclare** [MultiQC/MultiQC#2514]
### Description of bug

Similar to https://github.com/MultiQC/MultiQC/issues/2198

I have tried different installs (conda, pip), brand new environments, older versions (1.17)and I get the same error. I've also tried `--interactive`, `--flat` and `--no-report`. I am not sure what has happened since multiqc has always worked for me

### File that triggers the error

Example file: [RAPiD-Genomics_F279_VAC_155003_P001_WA01_i5-19_i7-59_S2489_L002_R1_001.fastp.json](https://github.com/MultiQC/MultiQC/files/15155841/RAPiD-Genomics_F279_VAC_155003_P001_WA01_i5-19_i7-59_S2489_L002_R1_001.fastp.json)

### MultiQC Error log

```console
/// MultiQC 🔍 | v1.21

|           multiqc | Search path : /mnt/e/VacCAP_155003_Cranberry/ForManuscript/qc
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 384/384
|             fastp | Found 192 reports
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
Traceback (most recent call last):
  File "/home/barlex/anaconda3/envs/multiqc/bin/multiqc", line 8, in <module>
    sys.exit(run_multiqc())
             ^^^^^^^^^^^^^
  File "/home/barlex/anaconda3/envs/multiqc/lib/python3.11/site-packages/multiqc/__main__.py", line 23, in run_multiqc
    multiqc.run_cli(prog_name="multiqc")
  File "/home/barlex/anaconda3/envs/multiqc/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/barlex/anaconda3/envs/multiqc/lib/python3.11/site-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/barlex/anaconda3/envs/multiqc/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/barlex/anaconda3/envs/multiqc/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/barlex/anaconda3/envs/multiqc/lib/python3.11/site-packages/multiqc/multiqc.py", line 299, in run_cli
    multiqc_run = run(**kwargs)
                  ^^^^^^^^^^^^^
  File "/home/barlex/anaconda3/envs/multiqc/lib/python3.11/site-packages/multiqc/multiqc.py", line 1084, in run
    shutil.copytree(
  File "/home/barlex/anaconda3/envs/multiqc/lib/python3.11/shutil.py", line 573, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/barlex/anaconda3/envs/multiqc/lib/python3.11/shutil.py", line 527, in _copytree
    raise Error(errors)
shutil.Error: [('/tmp/tmp3snv69_d/multiqc_data', '/mnt/e/VacCAP_155003_Cranberry/ForManuscript/qc/multiqc_data', '[Errno 1] Operation not permitted')]
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
The error says it can't write to `/mnt/e/VacCAP_155003_Cranberry/ForManuscript/qc/multiqc_data`. Have you checked if `/mnt` is read-only?

**Comment by sjclare** [comment]
I have full permissions:
`(snp) barlex@DESKTOP-VDKQE0G:/mnt/e/VacCAP_155003_Cranberry/ForManuscript$ ls -ld qc
drwxrwxrwx 1 root root 4096 Apr 29 17:32 qc`

Also multiqc makes the multiqc_data directory with txt files and a json file

**Comment by vladsavelyev** [comment]
Hey @sjclare - MultiQC works for me correctly on your file:

```
multiqc RAPiD-Genomics_F279_VAC_155003_P001_WA01_i5-19_i7-59_S2489_L002_R1_001.fastp.json
```

The error has unlikely anything to do with MultiQC, but rather with the file system, which doesn't let MultiQC recursively copy '/tmp/tmp3snv69_d/multiqc_data' into '/mnt/e/VacCAP_155003_Cranberry/ForManuscript/qc/multiqc_data':

```
shutil.Error: [('/tmp/tmp3snv69_d/multiqc_data', '/mnt/e/VacCAP_155003_Cranberry/ForManuscript/qc/multiqc_data', '[Errno 1] Operation not permitted')]
```

Check if for some reason the file system doesn't allow copying from `/tmp` into `/mnt`. Try changing the `/tmp` location by setting `TMPDIR`, like this:

```
TMPDIR=/mnt/... multiqc ...
```

Or try a different output location.

**Comment by sjclare** [comment]
Wasn't able to fix the permissions issue but running with sudo worked
