### ISSUE TITLE
Reduce MultiQC memory consumption

### ISSUE THREAD

**Issue by rhpvorderman** [MultiQC/MultiQC#2517]
### Description of feature

See #1961 for the issue. 

I have done a lot of memory profiling over the last few days and identified the issue. Rampant memory usage is caused by the modules mostly. MultiQC core itself is fairly ok with memory. 

The core problem is that MultiQC uses global variables and does not use an iterative module to generate the report. All the modules are executed and put in a list. Then the report is build. This means all the modules stay in scope all the time after execution. 
The problem then arises not from the MultiQC plots, but from the data structures that are added to the modules itself in a `self.data[sample_name] = all_data_i_just_parsed` pattern. This `self.data` variable contains a lot of data which uses a lot of memory, but the Garbage Collector can't clean it up. 

The primary means of fixing this is executing the modules lazily this will bring the memory usage down from `multiqc_mem_usage + sum(per_module_mem_usage)` to `multiqc_mem_usage + max(per_module_mem_usage)`. 

The following steps need to be taken:

- [x] Reduce MultiQC core memory usage (#2510, #2515) 
- [x] Refactor MultiQC so only one module remains in scope at module run time. Report sections should immediately be generated and the module discarded before the next module is run. 
- [x] Reduce memory usage of modules that load a lot of data in memory
    - [x] FastQC (https://github.com/MultiQC/MultiQC/pull/2552)
    - [x] Sequali (https://github.com/MultiQC/MultiQC/pull/2516)
    - [x] mosdepth (https://github.com/MultiQC/MultiQC/pull/2748, https://github.com/MultiQC/MultiQC/pull/2749)
    - [x] kraken (https://github.com/MultiQC/MultiQC/pull/2756)
    - [x] Other modules... (please add other modules to the list)
 
I have done the things I could easily do. I feel the refactoring needs to be done by a seasoned core MultiQC developer. Ping @vladsavelyev @ewels .

**Comment by vladsavelyev** [comment]
> Refactor MultiQC so only one module remains in scope at module run time. Report sections should immediately be generated and the module discarded before the next module is run.

Cannot agree more! I started getting rid of module-level fields like `self.data` in some modules, and was planning to complete it after some bigger refactoring in https://github.com/MultiQC/MultiQC/pull/2442. 

Modules also write into `report.saved_raw_data`, which we don't really need to keep for the entire run, unless the users requested that explicitly (e.g. for interactive use case).

That's something on my radar, and I'll priority it.

> Reduce memory usage of modules that load a lot of data in memory

Absolutely. There are a bunch of modules that can be improved. `mosdepth` is another example.

Thanks for creating this issue! Super helpful to have this in such a structured way.

**Comment by rhpvorderman** [comment]
That is a very interesting roadmap! I am looking forward to see that come to fruition. 

As regards to the multithreading. MultiQC executes in roughly a minute on my machine on the production data you have provided to me (with thousands of reports!). That means that longer execution times on clusters are usually caused by storage and memory bottlenecks. Multithreading is not going to mitigate those bottlenecks. While it may bring some performance improvements locally, I doubt they will materialize on clusters and cloud computing.

**Comment by rhpvorderman** [comment]
I fixed FastQC. It turned out to be a **two-liner fix** (with one additional comment line explaining the two lines. 

How did I find out? I used a tip from the great Mike Acton. If you want to get a feel of what data you are handling: just use print. So I used print, and I found a lot of similar lines. This all turned to be out from the same section in the FastQC report, that is not used by MultiQC. So these lines are now skipped.

**Comment by vladsavelyev** [comment]
Wow, great find 😮 

I suspected unzipping or HTML parsing, but I wouldn't guess it would have to do with something as simple as that. In retrospect, it makes sense given how unreasonably much memory FastQC is using compared to other modules.

Thanks a lot, Ruben!

**Comment by vladsavelyev** [comment]
> Refactor MultiQC so only one module remains in scope at module run time. Report sections should immediately be generated and the module discarded before the next module is run.

This is mostly done by cleaning modules raw data and temporary objects: https://github.com/MultiQC/MultiQC/pull/2551

By the time the module's code finished running, its memory footprint should not be larger than its corresponding JS runtime footprint - which includes just the plot traces and metadata. For whatever large underlying dataset, all required downsampling and summarization would be done by module code and plot object initializers, so the resulting plot data would look exactly as it would be dumped to be loaded in JavaScript. So there is no reason to render modules one by one as the bottleneck in terms of memory is still going to be the browser runtime.

That being said, the `config.preserve_module_raw_data` option is disabled by default because it's used to add the `saved_raw_data` section in multiqc_data.json. We should be able to write it sequentially and remove from memory as modules run - I'll do that and we can hopefully close this ticket for now!
