### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'int'.

### ISSUE THREAD

**Issue by ngctkk** [MultiQC/MultiQC#2522]
When I try to use multiqc, I get the following error:
AttributeError: module 'numpy' has no attribute 'int'. `np.int` was a deprecated alias for the builtin `int`.

It seems that (np.int, "int"), (np.int8, "int") used in GraphML is the problem.
File "/usr/lib/python3/dist-packages/networkx/readwrite/graphml.py", line 346, in GraphML
    (np.int, "int"), (np.int8, "int"),

I downgraded numpy from 1.26.4 to 1.23.5. Then this error disappeared.
I thought it would be good to report this issue.

**Comment by vladsavelyev** [comment]
The error seems to be coming from `networkx`, not MultiQC. Could you look into upgrading `networkx`? Or try installing MultiQC in a clean environment.
