### ISSUE TITLE
Unit testing for core library

### ISSUE THREAD

**Issue by ewels** [MultiQC/MultiQC#2531]
We should add unit tests for code functionality, especially the new interactive functions in https://github.com/MultiQC/MultiQC/pull/2442 which are currently untested in our CI tests.

Related to https://github.com/MultiQC/MultiQC/issues/2046

**Comment by vladsavelyev** [comment]
Partially addressed with https://github.com/MultiQC/MultiQC/pull/2570

Key core features are now tested, including some interactive functions.

Will work on completing the test set.
