### ISSUE TITLE
New `multiqc_data.json` has a diminished `.report_saved_raw_data`

### ISSUE THREAD

**Issue by rorynolan** [MultiQC/MultiQC#2585]
### Description of bug

In `1.21`, for the attached file `.summary` file (I had to zip it), `jq '.report_saved_raw_data'` would give me

```json
{
  "multiqc_featureCounts": {
    "RD0533NC": {
      "Total": 13632,
      "Assigned": 3033,
      "Unassigned_Unmapped": 3697,
      "Unassigned_Read_Type": 0,
      "Unassigned_Singleton": 0,
      "Unassigned_MappingQuality": 0,
      "Unassigned_Chimera": 0,
      "Unassigned_FragmentLength": 0,
      "Unassigned_Duplicate": 0,
      "Unassigned_MultiMapping": 4638,
      "Unassigned_Secondary": 0,
      "Unassigned_NonSplit": 0,
      "Unassigned_NoFeatures": 2214,
      "Unassigned_Overlapping_Length": 0,
      "Unassigned_Ambiguity": 50,
      "percent_assigned": 22.24911971830986
    }
  },
  "multiqc_general_stats": {
    "RD0533NC": {
      "featureCounts_mqc-generalstats-featurecounts-percent_assigned": 22.24911971830986,
      "featureCounts_mqc-generalstats-featurecounts-Assigned": 3033
    }
  }
}
```

but in `1.22.1` I get 

```json
{
  "multiqc_general_stats": {
    "RD0533NC": {
      "None_mqc-generalstats-featurecounts-percent_assigned": 22.24911971830986,
      "None_mqc-generalstats-featurecounts-Assigned": 0.0030329999999999997
    }
  }
}
```

I was using `multiqc` for the great report but also as a data aggregator; I was parsing this JSON. I couldn't find this intention in the release notes. Did I miss something?

I see similar things with other tools e.g. `fastp` but am trying to give you a minimal example.

### File that triggers the error

[RD0533NC_gene_counts.summary.zip](https://github.com/MultiQC/MultiQC/files/15421154/RD0533NC_gene_counts.summary.zip)

### MultiQC Error log

```console
/// MultiQC 🔍 | v1.21

|           multiqc | MultiQC Version v1.22.1 now available!
|           multiqc | Search path : /Users/rnolan/Downloads/x
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1
|    feature_counts | Found 1 reports
|           multiqc | Existing reports found, adding suffix to filenames. Use '--force' to overwrite.
|           multiqc | Report      : multiqc_report_3.html
|           multiqc | Data        : multiqc_data_3
|           multiqc | MultiQC complete


/// MultiQC 🔍 v1.22.1

       file_search | Search path: /Users/rnolan/Downloads/x
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1
    feature_counts | Found 1 reports
     write_results | Existing reports found, adding suffix to filenames. Use '--force' to overwrite.
     write_results | Data        : multiqc_data_2
     write_results | Report      : multiqc_report_2.html
           multiqc | MultiQC complete

```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Sorry about this issue! We started cleaning some memory in modules to avoid the tool consuming too much of it, and as a consequence, we didn't keep the raw parsed data by default. It's controlled by the `preserve_module_raw_data` option in config, but I'm going to make it `true` by default to keep the compatibility with the previous versions.
