### ISSUE TITLE
Issue installing multiqc from bioconda

### ISSUE THREAD

**Issue by SuhasSrinivasan** [MultiQC/MultiQC#2587]
### Description of bug

Hi,

Thank you for developing and maintaining multiqc!

There is currently a reproducible issue with installing multiqc from bioconda.

OS: Ubuntu 22.04.4 LTS
conda 24.4.0
Python 3.12.3

```
conda install bioconda::multiqc
Channels:
 - defaults
 - bioconda
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: / warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides python 3.4* needed by multiqc-0.4-py34_0

Could not solve for environment specs
The following packages are incompatible
├─ multiqc is installable with the potential options
│  ├─ multiqc [0.4|0.5|...|0.9a] would require
│  │  └─ python 2.7* , which can be installed;
│  ├─ multiqc [0.4|0.5|...|0.9a] would require
│  │  └─ python 3.4* , which does not exist (perhaps a missing channel);
│  ├─ multiqc [0.4|0.5|...|0.9a] would require
│  │  └─ python 3.5* , which can be installed;
│  ├─ multiqc [1.0|1.1|...|1.9] would require
│  │  └─ lzstring, which does not exist (perhaps a missing channel);
│  └─ multiqc 1.22.1 would require
│     └─ pyaml-env, which does not exist (perhaps a missing channel);
└─ pin-1 is not installable because it requires
   └─ python 3.12.* , which conflicts with any installable versions previously reported.
```

However, installing from pip is a workaround

```
pip install multiqc
Collecting multiqc
  Downloading multiqc-1.22.1-py3-none-any.whl.metadata (45 kB)
.
.
.
Successfully installed MarkupSafe-2.1.5 Pillow-10.3.0 annotated-types-0.7.0 certifi-2024.2.2 charset-normalizer-3.3.2 click-8.1.7 
coloredlogs-15.0.1 colormath-3.0.0 humanfriendly-10.0 humanize-4.9.0 idna-3.7 importlib-metadata-7.1.0 jinja2-3.1.4 kaleido-0.2.1 
markdown-3.6 markdown-it-py-3.0.0 mdurl-0.1.2 multiqc-1.22.1 networkx-3.3 numpy-1.26.4 packaging-24.0 plotly-5.22.0 
pyaml-env-1.2.1 pydantic-2.7.1 pydantic-core-2.18.2 pygments-2.18.0 pyyaml-6.0.1 requests-2.32.2 rich-13.7.1 rich-click-1.8.2 
spectra-0.0.11 tenacity-8.3.0 tqdm-4.66.4 typeguard-4.2.1 typing-extensions-4.12.0 urllib3-2.2.1 zipp-3.19.0
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by ewels** [comment]
Thanks for reporting @SuhasSrinivasan ! @FranBonath is this the same error that you were talking about earlier today?

**Comment by FranBonath** [comment]
@ewels no, not the same. I will check what Multiqc version we are using and if it is the latest add an issue for my error.

**Comment by ewels** [comment]
@SuhasSrinivasan - I just tried locally with a new Python 3.12 environment and it worked fine.

One part of your log message stands out to me:

```
Channels:
 - defaults
 - bioconda
```

You're missing `conda-forge` there. Are you sure that you've configured conda properly for use with bioconda?

See the bioconda documentation [here](https://bioconda.github.io/#usage):

> Perform a one-time set up of Bioconda with the following commands. This will modify your `~/.condarc` file:
>
> ```bash
> conda config --add channels defaults
> conda config --add channels bioconda
> conda config --add channels conda-forge
> conda config --set channel_priority strict
> ```
>
> If you have used Bioconda in the past, note that the recommended configuration has changed over the years. You should run the above commands to ensure your settings follow the current recommendations.

**Comment by SuhasSrinivasan** [comment]
Hi @ewels 
Thank you for reviewing the issue, indeed, `conda-forge` is not in my channel list, especially with the strict priority.
This has caused issues in the past when creating environments with a mix of deep learning and bioinformatics packages.
Is `pip` the simplified method of installation for this?

Apologies if this was an inconvenience.

**Comment by ewels** [comment]
Gotcha 👍🏻  Yes unfortunately conda-forge is a requirement for bioconda, many packages there will need that in order to function properly.

Both `pip` and `conda` are very commonly used to install MultiQC, so if `pip` works in your case then that sounds like a sensible solution.

More generally speaking, I would encourage use of isolated environment using containerisation if you have multiple scripts with conflicting dependencies. For example, using Docker or Singularity. Those methods, and others, are described in the installation docs: https://multiqc.info/docs/getting_started/installation/
