### ISSUE TITLE
Start maintaining Spack distribution

### ISSUE THREAD

**Issue by ewels** [MultiQC/MultiQC#2595]
MultiQC is available via Spack: https://packages.spack.io/package.html?name=py-multiqc

We document it here: https://multiqc.info/docs/getting_started/installation/#spack

However, the recipe is well behind now and only updated to v1.15.

We should take over maintainance and keep it up to date as part of our release process.

Can add `maintainers("ewels", "vladsavelyev")` to the recipe to mark ourselves as maintainers.

👉🏻  Need to update [this file](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-multiqc/package.py).

**Comment by ewels** [comment]
If you want to be really freaked out, check out [python:multiqc](https://repology.org/project/python:multiqc/versions) and [multiqc](https://repology.org/project/multiqc/versions) on [Repology](https://repology.org/) 😅 

[![Packaging status](https://repology.org/badge/vertical-allrepos/python:multiqc.svg)](https://repology.org/project/python:multiqc/versions)

[![Packaging status](https://repology.org/badge/vertical-allrepos/multiqc.svg)](https://repology.org/project/multiqc/versions)

Arch Linux winning!

**Comment by vladsavelyev** [comment]
PR on Spack: https://github.com/spack/spack/pull/45325
