### ISSUE TITLE
Omissions due to sample name

### ISSUE THREAD

**Issue by YIGUIz** [MultiQC/MultiQC#2605]
### Description of bug

Hi,
    when I use the multiqc to summarize the results of qc. I noticed that there some results are omitted due to the word "of"  in the samples' name. how to solve this problem?
    The multiqc_general_stats.txt show the incomplete Sample:
<img width="815" alt="Screenshot 2024-06-02 105623" src="https://github.com/MultiQC/MultiQC/assets/64197852/f7cf4ad4-8d2b-4b91-9f0d-c196a6278434">

Here are samples' full name:
![image](https://github.com/MultiQC/MultiQC/assets/64197852/be5e183f-4d45-4c36-8079-b68dc1196691)

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by ewels** [comment]
Please can you attach some files that we can use to replicate the error 😊

> I have attached an input file (.zip if necessary) that triggers the error.
