### ISSUE TITLE
Copy search patterns YAML to markdown for module docs

### ISSUE THREAD

**Issue by ewels** [MultiQC/MultiQC#2634]
Currently, the website automatically renders the module search patterns for each tool.

For example:
* [Docs page](https://multiqc.info/modules/adapterremoval/)
* [Source markdown](https://github.com/MultiQC/MultiQC/blob/main/docs/modules/adapterremoval.md)
* [Search pattern YAML](https://github.com/MultiQC/MultiQC/blob/034e1c05867475d5643dd439555229410aae5f02/multiqc/search_patterns.yaml#L5-L8)
* [Website logic](https://github.com/MultiQC/website/blob/f4cce35160c8c62541a987872e6933f2231d2875/src/pages/modules/%5Bmodule%5D.astro#L31-L37)

We want to remove this docs <> website dependency, so we should instead have automation in the MultiQC repo to copy the search patterns YAML to the source markdown instead. And then check it to make sure that it's up to date.

We have previously talked about automating much of the module markdown document based on what's written in the module `init` (not sure if we already have an issue for that?). This could be done as part of the same effort, but doesn't have to be.

**Comment by ewels** [comment]
NB: Will need to update the website repo to remove the code to print this stuff once the change is made here, so that we don't double-print the search patterns. But that's just deleting a few lines of code so should be pretty trivial.

**Comment by vladsavelyev** [comment]
Linking the issue on generating markdown from source: https://github.com/MultiQC/MultiQC/issues/2008

**Comment by ewels** [comment]
Closed by https://github.com/MultiQC/MultiQC/pull/2765
