### ISSUE TITLE
Updating NanoStat/NanoPlot Quality Score thresholds from Q5-Q15 to Q10-Q30

### ISSUE THREAD

**Issue by sandratra-rab** [MultiQC/MultiQC#2640]
### Description of feature

Hi,

[Latest nanomath version (v1.4.0)](https://github.com/wdecoster/nanomath/commit/baa2ca7daee20cbbce1be63612f2a90459191047) updated the Q-score thresholds from Q5-Q7-Q10-Q12 to Q10-Q15-Q20-Q30 in NanoStat/NanoPlot output. The updated version of the nanostat MultiQC module should then produce the corresponding outputs in the General Statistics table and in the Reads by Quality Plot. I have made the corresponding pull request #2638 accordingly.

Thank you and have a nice!

**Comment by vladsavelyev** [comment]
Addressed with  https://github.com/MultiQC/MultiQC/pull/2645
