### ISSUE TITLE
s/gid lost when using shutil.copytree for data dir

### ISSUE THREAD

**Issue by paulstretenowich** [MultiQC/MultiQC#2644]
### Description of bug

Hi,

The error we are encountering is not making MultiQC failing itself but we get disk quota issues.

We are using an HPC as en environment with different quotas based on groups and so group ownership matters. MultiQC uses /tmp to first create the temp data dir (where the owner and the group is the $USER) and moves it to the final location with `shutil.copytree` which follows permissions (and ownership so group changes) of parent folder in destination except for the gid, so the `-s-` flag when checking with `getfacl` is missing in the copied MultiQC data dir even if it's there for its parent directory. That leads to a situation where files copied by the previous `shutil.copytree` are assigned to the right group but new files like `multiqc_data.json` for instance doesn't have the right group because the gid is missing on the MultiQC data directory.

As we have a very limited personal quota we can't always run a `chgrp` afterwards, and as we have integrated MultiQC within our pipeline suite ([GenPipes](https://genpipes.readthedocs.io/en/genpipes-v4.6.0/)) MultiQC can be run multiple times in a short amount of time leading to a disk quota issue.

A solution I can imagine would be to use /tmp only when stdout is requested by the user and otherwise use directly the final data dir location meaning to avoid having a `shutil.copytree`.

Let me know if there is any other information you might need or if I can help in any other way (like working on a PR).

Thanks in advance,

Paul

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by ewels** [comment]
> A solution I can imagine would be to use `/tmp` only when `stdout` is requested by the user and otherwise use directly the final data dir location meaning to avoid having a `shutil.copytree`.

Nice idea, but this isn't the only reason to write to the temporary directory. The main thing is that if we don't find any input files, we don't want to write anything to disk. It's irritating to have "no logs found" and then have a bunch of files that have to be cleaned up afterwards.

Is it possible for you to customise the temporary directory used by setting `$TMPDIR` - would that help?

**Comment by paulstretenowich** [comment]
Thanks for your answer!

Would it be via an argument or the env var `$TMPDIR`? And would the tmpdir be deleted at the end of MultiQC execution?

If you wish to make me test in a branch before merging to `main` I can do that.

**Comment by vladsavelyev** [comment]
`$TMPDIR` should be an env var: `TMPDIR=/my/dir multiqc ...`

`$TMPDIR` won't be deleted. MultiQC (rather, https://docs.python.org/3/library/tempfile.html) will create a subfolder with a random name inside `$TMPDIR`, and remove it after the execution (unless `--no-clean-up` is passed). It's a standard practice in UNIX systems.

**Comment by paulstretenowich** [comment]
Alright thanks for the answer. FYI when testing the content of the tmp folder gets erased but not the folder itself.
