### ISSUE TITLE
Custom content: Config not parsed for `_mqc.*` files

### ISSUE THREAD

**Issue by ewels** [MultiQC/MultiQC#2669]
If files have a `_mqc` file suffix, they are found by Custom Content, but any configuration specified for the custom config is ignored.

This can be seen in a minimal example that has a search pattern that should have the configuration apply to all TSV files, but it's ignored for those that have the suffix:

[mqc2.zip](https://github.com/user-attachments/files/16058046/mqc2.zip)

**Comment by vladsavelyev** [comment]
That had to do with the order of search patterns. The generic `custom_content` pattern got applied before the custom pattern, consuming the field first. Changed the order, making sure that custom patterns are applied first.
