### ISSUE TITLE
extra_series in custom content with multiple datasets

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [MultiQC/MultiQC#2679]
### Description of bug

I'm trying to include some custom data in the MultiQC report using the `custom content` functionality (very nice by the way!)

However, I run into an issue because I have multiple datasets in my custom content. Is there a way to:
1) Include the same extra_series in every dataset, in custom content that has multiple datasets
2) Include unique extra_series for every dataset in the custom content

I've found a way to include one or multiple extra_series in custom content for MultiQC, but the extra_series only show up in the figure for the first dataset.

If I use the interactive HTML button to switch to a different dataset, the extra_series disappears.

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Right, adding extra_series in the config with multiple datasets was broken - it was only applied to the first dataset. Should be fixed now with https://github.com/MultiQC/MultiQC/issues/2679

There are multiple scenarios that we aim to support, specifically:

1. Single dataset, `extra_series` is one series, or a list of series: should use those for the dataset.
2. Multiple datasets, `extra_series` is one series, or a list of series: should copy across datasets.
3. Multiple datasets, `extra_series` is a list of lists of series: should zip between datasets (i.e. the first list belongs to the first dataset, the second list belongs to the second dataset, etc).

You can see examples in the tests added here: https://github.com/MultiQC/MultiQC/pull/2684/files#diff-fc413b03c6b6d7ff6c704ab46aa50b4681c0e7ba80d13ff971cf6687c7d1d147R434-R532

Let me know if it still doesn't work for your case, and feel free to share your example that I could add into the test suit 👍
