### ISSUE TITLE
Loading config issues when running MultiQC as a python script

### ISSUE THREAD

**Issue by andvon** [MultiQC/MultiQC#2702]
### Description of bug

Hello,

When rendering MultiQC (v1.23) reports in a python script using `multiqc.write_report(...)`, information found in the `multiqc_config.yml` is not being processed. It appears that the config file is loaded, but in the example below there is no conditional formatting applied.

This issue does not occur when running MultiQC through the CLI with the standard `multiqc -n report.html -c multiqc_config.yml .`

Attached is a zip file where this is replicated. It contains the following:

- `run_analyses.log`: log file of stderr for each of the runs detailed below
- `run_multiqc_analyses.sh`: script to run all of the analyses
- `run_multiqc.py`: script for running multiQC through python.
- `environment.yml`: conda env containing multiqc=1.23
- `multiqc_config.yml`: yml file that should apply conditional formatting to the % Dups column in the general stats table.
- `data/`: folder containing a FastQC zip file from the RNA-seq pipeline
- `reports/`: The MultiQC report outputs after running through different methods
    - `cli_report/`: The output generated when running MultiQC normally. The % Dups column is properly highlighted.
   
![image](https://github.com/user-attachments/assets/ba3feae9-7e13-4735-aa86-5826158e2474)
    - `python_basic_report/`: The output generated when running MultiQC as a python script with minimal changes. The % Dups column is not highlighted.
![image](https://github.com/user-attachments/assets/0dd60081-7fb2-451d-9b50-c1e7ea6c4f1a)
    - `python_config_report/`: The output generated when running MultiQC as a python script, specifying the loading of the config file with `config.load_config_file("multiqc_config.yml")`. The % Dups column is not highlighted.
![image](https://github.com/user-attachments/assets/aa823e27-ab47-4564-801c-a9ed1f5e88ab)
    - `python_config2_report/`: The output generated when running MultiQC as a python script. The config file is specified in a list using `multiqc.write_report(config_files = [...])`. The % Dups column is not highlighted.
![image](https://github.com/user-attachments/assets/b9be0dc7-9c5f-464e-8ed8-133374f9fc9c)

As always, thanks for the hard work on an excellent tool!

### File that triggers the error

[multiqc_bug.zip](https://github.com/user-attachments/files/16255164/multiqc_bug.zip)

### MultiQC Error log

```console
/// MultiQC 🔍 v1.23

            config | Loading config settings from: multiqc_config.yml
       file_search | Search path: /multiqc_bug/data

            fastqc | Found 1 reports

     write_results | Data        : reports/cli_report/multiqc_cli_report_data   (overwritten)
     write_results | Report      : reports/cli_report/multiqc_cli_report.html   (overwritten)
           multiqc | MultiQC complete

/// MultiQC 🔍 v1.23

            config | Loading config settings from: multiqc_config.yml
       file_search | Search path: /multiqc_bug/data

            fastqc | Found 1 reports

/// MultiQC 🔍 v1.23


     write_results | Data        : reports/python_basic_report/python_basic_report_data   (overwritten)
     write_results | Report      : reports/python_basic_report/python_basic_report.html   (overwritten)
       run_multiqc | Running MultiQC with specifying the inclusion of multiqc_config.yml
            config | Loading config settings from: multiqc_config.yml

/// MultiQC 🔍 v1.23

       file_search | Search path: /multiqc_bug/data

            fastqc | Found 1 reports

/// MultiQC 🔍 v1.23


     write_results | Data        : reports/python_config_report/python_config_report_data   (overwritten)
     write_results | Report      : reports/python_config_report/python_config_report.html   (overwritten)
       run_multiqc | Running MultiQC with specifying the inclusion of multiqc_config.yml in the report command.

/// MultiQC 🔍 v1.23

            config | Loading config settings from: multiqc_config.yml
       file_search | Search path: /multiqc_bug/data

            fastqc | Found 1 reports

/// MultiQC 🔍 v1.23


     write_results | Data        : reports/python_config2_report/python_config2_report_data   (overwritten)
     write_results | Report      : reports/python_config2_report/python_config2_report.html   (overwritten)
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Thanks a lot for reporting this issue, and the detailed description and providing everything to reproduce 🙏 

Fixed it with: https://github.com/MultiQC/MultiQC/pull/2704
