### ISSUE TITLE
Picard InsertSizeMetrics missing data table output file

### ISSUE THREAD

**Issue by apregier** [MultiQC/MultiQC#2715]
### Description of bug

In a previous version of multiqc (1.17), the Picard InsertSizeMetrics module output a data file (e.g. `picard_insertSize.txt`) containing the sample summary data that is listed in the picard-style table (with column header row listed after the `## METRICS CLASS        picard.analysis.InsertSizeMetrics` line.  In the new version (both 1.22.1 and 1.23), that file is missing, and there is only the histogram outputs (e.g. `picard_insert_size_Counts.txt` and `picard_insert_size_Percentages.txt`.  I still see the metrics in the raw data json, but the data file is not output.  I searched documentation and release notes for some change, but didn't find anything.  From the code it still seems like the data file insertSize should be written (see https://github.com/MultiQC/MultiQC/blob/1bc5870bea2e76626265fc1e52cdda113340d044/multiqc/modules/picard/InsertSizeMetrics.py#L128).  Is there something I am missing?

### File that triggers the error

[test1_R1_001_dedup_fragmetrics.txt](https://github.com/user-attachments/files/16349832/test1_R1_001_dedup_fragmetrics.txt)

### MultiQC Error log

```console
% multiqc --outdir out .
/// MultiQC 🔍 v1.23

       file_search | Search path: /Users/ar/accounts/multiqc
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 39/39  
            picard | Found 1 InsertSizeMetrics reports
     write_results | Existing reports found, adding suffix to filenames. Use '--force' to overwrite.
     write_results | Data        : out/multiqc_data_1_2_3_4_5
     write_results | Report      : out/multiqc_report_5.html
           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Hey @apregier - you are absolutely right, the `module.write_data_file` function is expected to write that file, but it's not doing it. I fixed this bug with https://github.com/MultiQC/MultiQC/pull/2722 now and added a unit test - thanks a lot for spotting and reporting this!
