### ISSUE TITLE
Regression in sample highlighting for v1.23: sample highlighting no longer works in plots

### ISSUE THREAD

**Issue by TBradley27** [MultiQC/MultiQC#2720]
### Description of bug

In version v1.22.3 of multiqc, when highlighting samples, the highlighting works for plots:

<img width="933" alt="image" src="https://github.com/user-attachments/assets/fec88cbf-534a-4d84-a2df-727eb4695b1b">

in version v1.23 of multiqc, when highlighting samples, the highlighting does not work for plots:

<img width="931" alt="image" src="https://github.com/user-attachments/assets/af0a2f63-cfce-46a9-8dc1-1c8809be619f">

### File that triggers the error

[SLX-23260_HYCJMDSX5_GRCh37_g1kp2_idtUDP0255.picard_gc_bias_main.txt](https://github.com/user-attachments/files/16379562/SLX-23260_HYCJMDSX5_GRCh37_g1kp2_idtUDP0255.picard_gc_bias_main.txt)

### MultiQC Error log

```console
Activating conda environment: .snakemake/conda/d276954ef3a114c2f5d7d603183a476f_
Activating conda environment: .snakemake/conda/d276954ef3a114c2f5d7d603183a476f_

/// MultiQC 🔍 v1.23

            config | Loading config settings from: config/multiqc.yaml
            picard | Found 160 GcBiasMetrics reports
            picard | Found 160 InsertSizeMetrics reports
            picard | Found 160 WgsMetrics reports
          samtools | Found 160 stats reports
          samtools | Found 160 markdup reports

     write_results | Data        : results/reports/SLX-23260/SLX-23260_HYCJMDSX5_GRCh37_g1kp2.bwamem.post_alignment.multiqc_data
     write_results | Report      : results/reports/SLX-23260/SLX-23260_HYCJMDSX5_GRCh37_g1kp2.bwamem.post_alignment.multiqc.html
           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Thanks for reporting @TBradley27! Fixed it now with https://github.com/MultiQC/MultiQC/pull/2724

I should think of some unit test setup for the interactivity as well 🤔

**Comment by TBradley27** [comment]
Great, thank you very much!
