### ISSUE TITLE
No pdf output starting from version 1.22

### ISSUE THREAD

**Issue by fsandron** [MultiQC/MultiQC#2728]
### Description of bug

Starting from version 1.22, the option `--pdf` does not output a pdf file of the report

### File that triggers the error

[Summary_mapping_mqc.zip](https://github.com/user-attachments/files/16442824/Summary_mapping_mqc.zip)

### MultiQC Error log

```console
#1.21
$ multiqc --pdf . -o test-1.21

  /// MultiQC � | v1.21

|           multiqc | MultiQC Version v1.23 now available!
|           multiqc | --pdf specified. Using non-interactive HTML template.
|           multiqc | Search path : /env/export/v_bigtmp/test_new_version_lrqc_FS/bug_submit
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 2/2  
|    custom_content | Summary_mapping: Found 1 samples (bargraph)
|           multiqc | Report      : test-1.21/multiqc_report.html
|           multiqc | Data        : test-1.21/multiqc_data
|           multiqc | PDF Report  : /env/export/v_bigtmp/test_new_version_lrqc_FS/bug_submit/test-1.21/multiqc_report.pdf
|           multiqc | MultiQC complete

#1.23
$ multiqc --pdf . -o test-1.23

/// MultiQC � v1.23

       file_search | Search path: /env/export/v_bigtmp/test_new_version_lrqc_FS/bug_submit
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1  
    custom_content | Summary_mapping: Found 1 samples (bargraph)
   rendering plots | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1  
     write_results | Data        : test-1.23/multiqc_data
     write_results | Report      : test-1.23/multiqc_report.html
           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Thanks for reporting this issue and sorry that it was broken!

It was indeed broken and we never checked if it works since adding Plotly in 1.21. I addressed the issues now so `--pdf` now works; and made the plots narrow so they fit the PDF and it looks good.

Unfortunately, when the tables are too wide, they still don't look good - something to address in the future.

**Comment by fsandron** [comment]
Thanks !
