### ISSUE TITLE
Enable multiqc --export --data-format from existing multiqc_report.html

### ISSUE THREAD

**Issue by pbuendia** [MultiQC/MultiQC#2736]
### Description of feature

Is there a way to programmatically export a plot or all plots  in --data-format tsv format from an existing multiqc_report.html?
Like this: 
`multiqc --load  multiqc_report.html --export --data-format tsv `

?
If not, what do you recommend to do to extract the "General Statistics" plot programmatically from the multiqc_report.html file?

**Comment by vladsavelyev** [comment]
Extracting a TSV from the HTML report is not possible with MultiQC. But if you have aournd the auxiliary data output folder `multiqc_data`, you may wanna look at `multiqc_data/multiqc_general_stats.txt`.
