### ISSUE TITLE
anglerfish module - TypeError

### ISSUE THREAD

**Issue by j0n0curry** [MultiQC/MultiQC#2753]
Hello there, 

have been testing out multiQC with anglerfish output - anglerfish_stats.json in the below path. Version of anglerfish 0.6.1.
[anglerfish_stats.json](https://github.com/user-attachments/files/16564338/anglerfish_stats.json)

the multiqc.parse_logs(r'path/to/folder)

which then provides the following error...

C:\Users\Jonathan.Curry\GPU_test_anglerfish\anglerfish_2024_08_09_085810\anglerfish_stats.json                  │
│                                                                                                                 │
│ Traceback (most recent call last):                                                                              │
│   File "C:\Users\Jonathan.Curry\Anaconda3\lib\site-packages\multiqc\core\exec_modules.py", line 71, in exec_mod │
│     these_modules: Union[BaseMultiqcModule, List[BaseMultiqcModule]] = module_initializer()                     │
│   File "C:\Users\Jonathan.Curry\Anaconda3\lib\site-packages\multiqc\modules\anglerfish\anglerfish.py", line 32, │
│     self.parse_anglerfish_json(f)                                                                               │
│   File "C:\Users\Jonathan.Curry\Anaconda3\lib\site-packages\multiqc\modules\anglerfish\anglerfish.py", line 81, │
│     self.anglerfish_data[s_name][f"{key}_{index}"] = float(k[key])                                              │
│ TypeError: float() argument must be a string or a number, not 'NoneType'

**Comment by vladsavelyev** [comment]
Thanks for reporting the issue! The 0.6.1 format turns out to be different from the example we had for 0.4.1, so it's breaking the anglerfish's module assumptions. I added your example into our test dataset: https://github.com/MultiQC/test-data/commit/557b4d6e6f3fd7a398387b12f6478d6ad700cfc5 - thanks for sharing it! And adjusted the module accordingly in https://github.com/MultiQC/MultiQC/pull/2757, it works now on your example

**Comment by j0n0curry** [comment]
Thank you..  Will test this out.  Kind regards Jonathan Sent from Mail for Windows From: Vlad SavelyevSent: 12 August 2024 10:13To: MultiQC/MultiQCCc: j0n0curry; AuthorSubject: Re: [MultiQC/MultiQC] anglerfish module - TypeError (Issue #2753) Closed #2753 as completed via #2757.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
