### ISSUE TITLE
samtools stats incorrect reporting when omitting duplicates

### ISSUE THREAD

**Issue by pdimens** [MultiQC/MultiQC#2764]
### Description of bug

One could run `samtools stats`  with the option to omit duplicates from calculations. When multiqc aggregates that output into a report, it now produces two columns named "Reads Mapped" with two very disparate values:
![image](https://github.com/user-attachments/assets/6f2bf672-abcd-4379-ab7d-a2bb76dbfbba)
In addition, the "%" mapped is much lower than expected because I suspect it doesn't subtract the absent duplicates from the total. The %Mapped scales with the %duplication. The same data shows 100% reads mapped when including duplicates into `samtools stats`.

As an aside, there is also a strange duplication of rows. Not sure what that's about.

### MultiQC Error log

```console
there is no error log
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
It looks like MultiQC fines two sets of files, with and without the `_trimmed` suffix, thus two separate rows. And the "Reads mapped" might be coming from different submodules. What does it show if you hover over each header?

Would you be able to share the exact samtools command, and attach files that it generated, so we can reproduce and quickly adjust MultiQC for this case?

**Comment by pdimens** [comment]
It'll be a few hours until all my files finish processing to generate another report, but in the mean time here is some of the other information:

### samtools command
````bash
samtools stats -d {input.bam} > {output.stats}
```

### the samtools stats output file
[AW194_1.stats.txt](https://github.com/user-attachments/files/16627503/AW194_1.stats.txt)

**Comment by pdimens** [comment]
@vladsavelyev the file is ~0.5gb, so here is a link to it stored in my cloud:
https://mega.nz/folder/7VojkKRL#CSv1FmkHpgLHtZ0DAFnx4w

**Comment by vladsavelyev** [comment]
Please attach the outputs of `samtools stats`, not the BAM file.

**Comment by pdimens** [comment]
> It'll be a few hours until all my files finish processing to generate another report, but in the mean time here is some of the other information:
> ### samtools command
> 
> ```shell
> samtools stats -d {input.bam} > {output.stats}
> ```
> 
> ### the samtools stats output file
> 
> [AW194_1.stats.txt](https://github.com/user-attachments/files/16627503/AW194_1.stats.txt)

**Comment by vladsavelyev** [comment]
I need the files to reproduce the report that you screenshot above. I expect at least 2 `samtools stats` outputs and 2 outputs from some other module that generated the "Reads mapped" column, and probably also a `multiqc_config.yaml`. You shared just one file, it makes this report as expected:
<img width="1718" alt="Screenshot 2024-09-05 at 17 53 40" src="https://github.com/user-attachments/assets/dadbfb86-66ad-40ce-8723-32417da7aa23">

**Comment by vladsavelyev** [comment]
Will close for now

**Comment by pdimens** [comment]
I will try to provide these other files later today (or this week). The only other output is from `samtools flagstat`, which I will provide as well. I do not have any custom configuration for multiqc, therefore I don't have any `multiqc_config.yaml` file to provide.

**Comment by pdimens** [comment]
Here are the files you requested. Two samples, and each has a `samtools stats` and `samtools flagstat` output file
[AW_194_1.flagstat.txt](https://github.com/user-attachments/files/16899326/AW_194_1.flagstat.txt)
[AW_194_1.stats.txt](https://github.com/user-attachments/files/16899327/AW_194_1.stats.txt)
[AW_205_2.flagstat.txt](https://github.com/user-attachments/files/16899328/AW_205_2.flagstat.txt)
[AW_205_2.stats.txt](https://github.com/user-attachments/files/16899329/AW_205_2.stats.txt)

**Comment by vladsavelyev** [comment]
Those are not the files that generated the report above. What is the command are you using? Please give exact instructions to reproduce the issue, otherwise I can't help.

```
multiqc -fv AW_205_2.stats.txt AW_205_2.flagstat.txt AW_194_1.stats.txt AW_194_1.flagstat.txt
```
<img width="1157" alt="Screenshot 2024-09-06 at 00 52 18" src="https://github.com/user-attachments/assets/d7c8fe8e-11ae-44cc-9215-cdb7e952a606">

**Comment by pdimens** [comment]
Ah, apologies. For the workflow in question, the `stats` files are in a folder called `stats` and the `flagstat` files are in a folder called `flagstat`. The triggering MultiQC command was:
```bash
multiqc ./stats ./flagstat --quiet --no-data-dir --filename report.html
```
