### ISSUE TITLE
`fn_clean_exts` splitting can cut large parts of sample name

### ISSUE THREAD

**Issue by jchorl** [MultiQC/MultiQC#2792]
### Description of bug

`fn_clean_exts` is very useful.

The way it works is well documented: https://multiqc.info/docs/getting_started/config/#cleaning-extensions

It works as documented.

However it performs poorly when one of the strings appears in the middle of a sample name. Take `mysample.trimmed-10-reads.foo.fastq`. Unexpectedly, I think the sample name would be `mysample` because the cleaning splits on `.trim` and everything right gets nuked. Imagine trying to analyze `mysample.trimmed-10-reads.foo` and `mysample.trimmed-5-reads.foo` - these would get merged in multiqc even though you're trying to compare both variants.

Given the config name (`ext`), I assume the intention is to trim extensions from the end of a string. However not all of these are file extensions, e.g. `_gopeaks` and `| stdin`. Those may appear at the suffix of samples, I'm not sure, but they're certainly not obvious "file extensions".

When processing many thousands of samples, people name them weird and wonderful things, which unfortunately is incompatible with the current extension cleaning algorithm.

I was wondering what it would take to convert many of these exts to suffix-trimming. Many of them could be converted a la `.fastq` --> `\.fastq$` regexes. We could move them into `extra_fn_clean_exts`.

Another option is to add a new type alongside `truncate`, `remove`, `regex`, etc: https://github.com/MultiQC/MultiQC/blob/a3df371122a0c2d8cb192b10d287ab6e1e202b83/multiqc/base_module.py#L493

I know I can just mangle `fn_clean_exts` into `extra_fn_clean_exts` and achieve what I'm looking for, but I'm opening this issue to see if you have ideas on how to make sample cleaning behave more sanely, particularly as modules are added and the growing list of extensions becomes increasingly likely to appear in the middle of sample names.

### File that triggers the error

N/A

### MultiQC Error log

```console
N/A
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Yeah, I agree that it might overdo things, and we were thinking about this with Phil before. But we're afraid that changing this logic might break a lot of user configs. And it's pretty easy to override the exts in a custom config, so we wouldn't prioritize revisiting this.

**Comment by jchorl** [comment]
> Yeah, I agree that it might overdo things, and we were thinking about this with Phil before. But we're afraid that changing this logic might break a lot of user configs. And it's pretty easy to override the exts in a custom config, so we wouldn't prioritize revisiting this.

Agree the behaviour is pervasive so it's tough to change now.

FWIW, we have logic to generate mqc config like:
```
        [
            {"type": "regex", "pattern": fn.replace(".", "\.") + "$"}
            for fn in multiqc.config.fn_clean_trim
            if is_file_extension(fn)
        ],
```

This would be awesome to get rid of at some point, but I understand that it's hard to change. Anyway, I'll close as deprioritized and hopefully at some point we can come up with a better approach.
