### ISSUE TITLE
Incorrect section name for cellranger/vdj data source

### ISSUE THREAD

**Issue by Sxmple-DavidSchmidt** [MultiQC/MultiQC#2799]
### Description of bug

In `modules/cellranger/vdj.py` a data source is added with the `module.add_data_source`  Method.  Here the value for `section` is set to be `count` which I believe to be wrong. This is misleading when looking at the data sources of a report.

```
cellranger	multi	Sample_25	/.../web_summary.html
cellranger	count	Sample_P1	/.../web_summary.html
```

I stumbled across this while working on implementing a CellRanger Multi module, which is why it says “Found 1 Cell Ranger multi reports” in the MultiQC Error log.

### File that triggers the error

I generated a VDJ report following the [guide over at their website](https://www.10xgenomics.com/support/software/cell-ranger/latest/tutorials/cr-tutorial-vdj): [web_summary.zip](https://github.com/user-attachments/files/16783960/web_summary.zip)

### MultiQC Error log

```console
$ python3 -m multiqc /mnt/c/Users/david.schmidt/.../ --outdir ~/.../

/// MultiQC 🔍 v1.24.1

       file_search | Search path: /mnt/c/Users/david.schmidt/.../
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 4/4  
        cellranger | Found 1 Cell Ranger multi reports
        cellranger | Found 1 Cell Ranger VDJ reports
     write_results | Data        : /.../multiqc_data
     write_results | Report      : /.../multiqc_report.html
           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Thanks for spotting and reporting!
