### ISSUE TITLE
Bug in `multiqc/report.py`: All exclude keys in `search_patterns.yaml` are ignored

### ISSUE THREAD

**Issue by Sxmple-DavidSchmidt** [MultiQC/MultiQC#2800]
### Description of bug

The method `exclude_file` in `multiqc/report.py` takes the argument `sp` (Always an instance of `SearchPattern`) which is treated like a dictionary in the body of the method (Iterating over keys like: `for k in sp`, conditionals using in on `sp`: `if "exclude_fn" in sp`, etc.). This does not work properly, but just so happens to not throw an exception because of Python being “generous”. Because this method handles the exclude-keys from the `search_patterns.yaml` file, the keys are not actually taken into consideration and files that should usually be filtered out depending on any exclusion key are still kept as an input.

### File that triggers the error

You can replicate this bug by adding an exclusion key like `exclude_fn: '*'` to some module in `search_patterns.yaml` and then see if the module still matches the files it typically shouldn't, had `exclude_fn` done its job.

### MultiQC Error log

```console
Unrelated
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by Sxmple-DavidSchmidt** [comment]
I can't fork the project for a proper pull request because I forked the project already to work on a cellranger multi implementation. I'm not too Git/GitHub savvy, so I don't really know how to open a pull request separately for this. While I would love to do the contribution myself, I can't figure out how, so I'm just going to post my suggestion for the method here.

```python
def exclude_file(sp, f: SearchFile):
    """
    Exclude discovered files if they match the special exclude_
    search pattern keys
    """

    # Search by file name (glob)
    for pat in sp.exclude_fn:
        if pat and fnmatch.fnmatch(f.filename, pat):
            return True

    # Search by file name (regex)
    for pat in sp.exclude_fn_re:
        if pat and re.match(pat, f.filename):
            return True

    # Search the contents of the file
    for num_lines, line_block in f.line_block_iterator():
        if sp.exclude_contents:
            for pat in sp.exclude_contents:
                if pat and pat in line_block:
                    return True
        if sp.exclude_contents_re:
            for pat in sp.exclude_contents_re:
                if pat and re.search(pat, line_block):
                    return True
    return False
```

This works for fine for me and actually filters files using the exclude keys.

**Comment by vladsavelyev** [comment]
Sorry about this bug again, and so much appreciated a PR with a fix 🙏
