### ISSUE TITLE
samtools coverage: add include/exclude contigs option

### ISSUE THREAD

**Issue by matthdsm** [MultiQC/MultiQC#2802]
### Description of feature

Would it be possible to add contig inclusion/exlcusion based on config cfr Mosdepth module?

```
  include_contigs:
    - "chr*"
  exclude_contigs:
    - "*_alt"
    - "*_decoy"
    - "*_random"
    - "chrUn*"
    - "HLA*"
    - "chrM"
    - "chrEBV"
```

Thanks
Matthias

**Comment by vladsavelyev** [comment]
Certainly! Will do

**Comment by vladsavelyev** [comment]
Addressed with https://github.com/MultiQC/MultiQC/pull/2840
