### ISSUE TITLE
fastqc module - key error

### ISSUE THREAD

**Issue by laura-bankers** [MultiQC/MultiQC#2808]
### Description of bug

[ERROR  ]         multiqc : Oops! The 'fastqc' MultiQC module broke... 

Possibly related to Issue #2807?

### File that triggers the error

any .fastq.gz

### MultiQC Error log

```console
Module fastqc raised an exception: Traceback (most recent call last):
  File "/usr/local/bin/multiqc", line 440, in multiqc
    output = mod()
  File "/usr/local/lib/python3.5/dist-packages/multiqc/modules/fastqc/fastqc.py", line 93, in __init__
    self.fastqc_general_stats()
  File "/usr/local/lib/python3.5/dist-packages/multiqc/modules/fastqc/fastqc.py", line 200, in fastqc_general_stats
    'avg_sequence_length': bs['avg_sequence_length'],
KeyError: 'avg_sequence_length'
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by ewels** [comment]
Hi @laura-bankers,

Please see the check list item:

> I have attached an input file (.zip if necessary) that triggers the error.

We can't do much without this sorry.

Note that Python 3.5 is not officially supported by MultiQC any more, it's pretty old. Though I doubt that this is causing your error.

Phil
