### ISSUE TITLE
Kraken2 report identified as Bracken

### ISSUE THREAD

**Issue by marchoeppner** [MultiQC/MultiQC#2825]
### Description of bug

I have had an issue with some Kraken2 reports being identified as Bracken by MultiQC. I do understand that these tools are fairly similar, so making that distinction is probably hard. 

Interestingly, this doesn't always happen - but I have now found a report where it is reproducible. 

This happens with both 1.23 and 1.24.1

### File that triggers the error

[SRR27145089.kraken2.report.txt](https://github.com/user-attachments/files/16906091/SRR27145089.kraken2.report.txt)

### MultiQC Error log

```console
singularity exec multiqc_1.24.1--pyhdfd78af_0.sif multiqc . 

/// MultiQC 🔍 v1.24.1

       file_search | Search path: /mnt/share/volume1/work/ngs/gabi/klebsiella_ont/results/samples/SRR27145089/taxonomy/kraken2
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 3/3  
            kraken | Bracken: Found 1 reports
     write_results | Existing reports found, adding suffix to filenames. Use '--force' to overwrite.
     write_results | Data        : multiqc_data_1
     write_results | Report      : multiqc_report_1.html
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
MultiQC assumes that Kraken reports the unclassified reads count as the first row:
https://github.com/MultiQC/MultiQC/blob/main/multiqc/search_patterns.yaml#L497-L499
Whereas Braken starts with `root`:
https://github.com/MultiQC/MultiQC/blob/main/multiqc/search_patterns.yaml#L194-L196

That's what we have in our examples repo:
https://github.com/MultiQC/test-data/blob/main/data/modules/kraken/issue_1428/GSR-SWIFT-2021-5-04-FF08511340.kraken2.report.txt
https://github.com/MultiQC/test-data/blob/main/data/modules/bracken/v2.6.0/bracken_report.txt

Is this assumption wrong? 🤔
