### ISSUE TITLE
Fastp module lacks on after trimming represention when fastp command runs with the `-m/--merge` option

### ISSUE THREAD

**Issue by Daniel-VM** [MultiQC/MultiQC#2826]
### Description of feature

When Fastp is run with the `-m/--merge option`, the output JSON changes the key from `read1_after_filtering` to `merged_and_filtered`, causing MultiQC to lose the visualization of after-trimming metrics, as the expected key is no longer present.

I noticed that the parseable keys are hardcoded in the [MultiQC Fastp module](https://github.com/MultiQC/MultiQC/blob/d1874e3f49043f024843e387956fa15fa5769f34/multiqc/modules/fastp/fastp.py#L63).

Is there a plan to implement a feature that supports the representation of merged reads metrics in MultiQC? Alternatively, is there a way to allow parsing the `merged_and_filtered` key by providing a custom configuration to MultiQC?

**Comment by vladsavelyev** [comment]
Would you be able to share an example of the fastp output that was run with the `--merge` option?

**Comment by Daniel-VM** [comment]
Sure, I am attaching the output example below. Thanks
[test.fastp.json](https://github.com/user-attachments/files/16936054/test.fastp.json)

**Comment by vladsavelyev** [comment]
Thank you for the example, really appreciated! Added support for it in https://github.com/MultiQC/MultiQC/issues/2826, will be a part of a release hopefully this or the next week.

**Comment by Daniel-VM** [comment]
Thanks @vladsavelyev 🙌🏾
