### ISSUE TITLE
Custom data for many samples as barplot

### ISSUE THREAD

**Issue by jd3234** [MultiQC/MultiQC#2835]
### Description of feature

Hi,

not sure if it is a feature request but it is not a bug :)

As part of a pipeline I am outputting tsv files looking like this for many samples

```bash
Range   Count
5801-6000       3559
5601-5800       134
601-800 127
1801-2000       109
801-1000        102
1401-1600       84
401-600 65
1001-1200       59
1601-1800       53
201-400 48
2201-2400       40
```
My initial idea was to group them all under one section using custom data. But i understand that is not possible when you have several files. If it is somehow possible I would be grateful if you could point me to an example. If I at least put some kind of description/text and a header line right above the first plot it would help.

I then played around with just naming the files with` _mqc.tsv`. That does kind of what I want.  However, I would like to customize the order on the y axis. Is there a way to do that? Or just switch off any kind of automatic sorting and the order comes from the tsv file.

![image](https://github.com/user-attachments/assets/a1bc8e6c-a6a3-4929-80c5-f382f439cb01)

**Comment by vladsavelyev** [comment]
Yes, sample sorting can be disabled with the `sort_samples` plot config flag, for example, it can be specified in the CSV/TSV file #-fenced header like this:

```
# plot_type: 'bargraph'
# pconfig:
#     sort_samples: false
Sample Name, Cat 1, Cat 2, Cat 3, Cat 4, Cat 5
Sample 1,1,6,2,4,6
Sample 3,2,5,3,4,5
Sample 4,12,16,18,13,15
Sample 2,3,2,5,7,3
```

Let me know if it works!
