### ISSUE TITLE
Add a py.typed file for downstream plugins to use MultiQC's type annotations

### ISSUE THREAD

**Issue by ccwang002** [MultiQC/MultiQC#2842]
### Description of feature

Currently, when using MultiQC in downstream plugins, type checkers like `mypy` report the following error:

```
Skipping analyzing "multiqc": module is installed, but missing library stubs or py.typed marker  [import-untyped]
```

According to the [official typing documentation](https://typing.readthedocs.io/en/latest/guides/libraries.html#how-to-provide-type-annotations), adding a `py.typed` file to a package indicates that the package includes type hints.

It seems that by adding an empty file at `multiqc/py.typed` (or at the submodules where typing annotations are available), this error will be fixed and mypy will be able to recognize and use MultiQC's type annotations in the plugins.

Thank you for making this extremely useful package.

**Comment by vladsavelyev** [comment]
Thanks for the tip! Added it with https://github.com/MultiQC/MultiQC/pull/2846
