### ISSUE TITLE
Barplot Data TSV/CSV Export Missing Sample Names

### ISSUE THREAD

**Issue by diderote** [MultiQC/MultiQC#2843]
### Description of bug

When exporting barplot data tabular files, the sample name is not exported and is left as 'undefined'.  

Using a response override with safari on the report.html, the sample name is correctly exported when `this.` is added before  `filteredSettings` (eg. `this.filteredSettings`) in the js related to this line: https://github.com/MultiQC/MultiQC/blob/ac817f62360742efc7ea4881e62bb68fed5015f4/multiqc/templates/default/assets/js/plots/bar.js#L106.

### File that triggers the error

There error can be replicated from the MultQC report hosted on the main multiqc.info page or at https://multiqc.info/example-reports/bisulfite-seq/.  Choose export toolbox, switch to 'Data' export, unselect all, then select any barplot (eg. bismark_alignment) for export.  Resulting tabular file will display 'undefined' for all samples. Also attaching here.
[MultiQC Report.html.zip](https://github.com/user-attachments/files/16998077/MultiQC.Report.html.zip)

### MultiQC Error log

```console
Input data from https://multiqc.info/example-reports/bisulfite-seq/. https://multiqc.info/examples/bs-seq/data.zip

$ multiqc .

/// MultiQC 🔍 v1.24.1

       file_search | Search path: /Users/xxxx/Downloads/data
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 88/88
           bismark | Found 8 alignment reports
           bismark | Found 8 dedup reports
           bismark | Found 8 methextract reports
          cutadapt | Found 8 reports
            fastqc | Found 8 reports
     write_results | Data        : multiqc_data
     write_results | Report      : multiqc_report.html
           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Thanks a lot for reporting this! Fixed with https://github.com/MultiQC/MultiQC/pull/2845, will be a part of a release on Monday.
