### ISSUE TITLE
pychopper module: add reads stats information

### ISSUE THREAD

**Issue by rabioinf** [MultiQC/MultiQC#2869]
### Description of feature

Currently only two stats are displayed in MultiQC. The read classification and the strand orientation of the identified full length transcripts.

It would be nice if you could add the read statistics as a bargraph as well. I am especially interested in the UMI detection stats.

Thanks in advance!

**Comment by vladsavelyev** [comment]
Can you please give more information - what kind of statistics you'd like to see? What values would you map to bar categories and values from here? https://github.com/MultiQC/test-data/blob/main/data/modules/pychopper/Sample01.txt That's the only example output that we have - if you have another example, please share!

**Comment by rabioinf** [comment]
Sure. In some of the current library kits, unique molecular identifiers (UMIs) are integrated during library preparation. Pychopper will detect UMIs and report them in the output files as well. The statistics file of Pychopper will then contain a row with "ReadStats" -> "Umi_detected_final". With this value, I would like to see the following plot:

Pychopper: UMI Detection

barplot with UMI detected / unknown. Where the reads with unknown UMIs will be calculated by:  (Primers_found + Rescue + Unusable) - Umi_detect_final

Here is an example test file:
[pychopper_test_sample.txt](https://github.com/user-attachments/files/18151360/pychopper_test_sample.txt)

Let me know if you need more information!

**Comment by vladsavelyev** [comment]
Thank you! Added here: https://github.com/MultiQC/MultiQC/pull/3024 let me know if it looks good
