### ISSUE TITLE
Kraken plot not displayed in MultiQC after version 1.23

### ISSUE THREAD

**Issue by nschcolnicov** [MultiQC/MultiQC#2876]
### Description of bug

After updating the MultiQC module in the nf-core/demultiplex pipeline, the MultiQC report no longer displayed the Kraken section. I originally created an issue for this https://github.com/MultiQC/MultiQC/issues/2801, where there was an error being raised by MultiQC. Now, that error is no longer being raised, but the MultiQC report still doesn't display the Kraken plots.

### File that triggers the error

Copying the full nextflow workdir of the MultiQC process:
[multiqc_wd.tar.gz](https://github.com/user-attachments/files/17118226/multiqc_wd.tar.gz)

I'm also attaching the same workdir, during the same pipeline execution, but changing MultiQC to 1.23 instead (this produces the correct MultiQC report that contains kraken plots):
[multiqc_wd_1.23.tar.gz](https://github.com/user-attachments/files/17118360/multiqc_wd_1.23.tar.gz)

Original MultiQC with version 1.23 (quay.io/biocontainers/multiqc:1.23--pyhdfd78af_0) report looks like this:
![image](https://github.com/user-attachments/assets/6bc9bcd8-9c33-4d19-8f07-244763d8b95c)

While running the same with version 1.25 (quay.io/biocontainers/multiqc:1.25--pyhdfd78af_0) it looks like this (it is missing, but you can see that kraken ran):
![image](https://github.com/user-attachments/assets/ab84eae3-3ed1-47f3-b08d-c812943c6cde)

### MultiQC Error log

```console
/// MultiQC 🔍 v1.25

            config | Loading config settings from: multiqc_config.yml
       file_search | Search path: /workspace/demultiplex/.nf-test/tests/de4760fccc143099e9ca653fac31a64a/work/28/f3165e62a48ea9f7963e5911297efb

       base_module | Tried to add data source for bcl2fastq, but missing file info
            fastqc | Found 1 reports
             fastp | Found 1 reports
    custom_content | HTML plot type found with more than one dataset in nf-core-demultiplex-summary
    custom_content | nf-core-demultiplex-summary: Found 1 sample (html)
    custom_content | HTML plot type found with more than one dataset in nf-core-demultiplex-methods-description
    custom_content | nf-core-demultiplex-methods-description: Found 1 sample (html)
            kraken | Found 1 reports
     write_results | Rendering plots. Export plots to formats png, svg, pdf is requested, so it might take a while. To disable plot export, set `export_plots: false` in config, or remove the `--export-plots` command line flag

     write_results | Data        : multiqc_data
     write_results | Report      : multiqc_report.html
     write_results | Plots       : multiqc_plots
           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
This is the edge case where Kraken report is essentially empty - all reads are unclassified. Agree that we still should add a section like pre-1.23, will take a look

**Comment by vladsavelyev** [comment]
Also, note that the tarballs you attached do not contain any files, they are only symlinks. In the previous issue https://github.com/MultiQC/MultiQC/issues/2801, I asked you to attach a file. Can you please attach one here?

**Comment by vladsavelyev** [comment]
Ah, reproduced this. The module runs, it just doesn't show the "Top taxa" plot because there is no data. Adding an "unclassified" tab like in previous version makes it re-appear - done with https://github.com/MultiQC/MultiQC/pull/2881

**Comment by vladsavelyev** [comment]
Would you be able to test it now from source? To make sure it does what's expected before we release.

```
git clone https://github.com/MultiQC/MultiQC/
pip install -e MultiQC
multiqc f3165e62a48ea9f7963e5911297efb
```

**Comment by nschcolnicov** [comment]
@vladsavelyev This seems to fix this issue, Thanks!
