### ISSUE TITLE
Picard HsMetrics module not storing corrrect file paths into source list 

### ISSUE THREAD

**Issue by ccwang002** [MultiQC/MultiQC#2877]
### Description of bug

MultiQC v1.25 does not track the Picard HsMetrics's data sources correctly. For any MultiQC run, all different samples show that they have the identical source file path in `multiqc_data.json`'s `report_data_sources`.

Here is an example using the official test data:

```json
{
    "report_data_sources": {
        "Picard": {
            "HsMetrics": {
                "TestSample": "/tmp/test_data/data/modules/picard/HsMetrics/alignment-hs_metrics.txt",
                "P553-002-1A_Sain": "/tmp/test_data/data/modules/picard/HsMetrics/alignment-hs_metrics.txt",
                "S1": "/tmp/test_data/data/modules/picard/HsMetrics/alignment-hs_metrics.txt",
                "alignment-hs_metrics_2samps: bait_intervals": "/tmp/test_data/data/modules/picard/HsMetrics/alignment-hs_metrics.txt",
                "alignment-hs_metrics_2samps: other_interval": "/tmp/test_data/data/modules/picard/HsMetrics/alignment-hs_metrics.txt",
                "PID_794": "/tmp/test_data/data/modules/picard/HsMetrics/alignment-hs_metrics.txt",
                "Sentieon_Example": "/tmp/test_data/data/modules/picard/HsMetrics/alignment-hs_metrics.txt",
                "E11642_umiFlt": "/tmp/test_data/data/modules/picard/HsMetrics/alignment-hs_metrics.txt",
                "VAL215_S15": "/tmp/test_data/data/modules/picard/HsMetrics/alignment-hs_metrics.txt",
                "alignment-hs_metrics": "/tmp/test_data/data/modules/picard/HsMetrics/alignment-hs_metrics.txt"
            }
        }
    },
}
```

It seems the error was due to `module.add_data_source(f, ...)` being called outside of the loop `for f in module.find_log_files(...`, so `f` is never updated for all the samples (note their indentation levels are the same):

https://github.com/MultiQC/MultiQC/blob/8c3fbc1b1b33ebf20006670518bffda836c300d5/multiqc/modules/picard/HsMetrics.py#L69-L70

https://github.com/MultiQC/MultiQC/blob/8c3fbc1b1b33ebf20006670518bffda836c300d5/multiqc/modules/picard/HsMetrics.py#L142

Thanks again for making this tool.

### File that triggers the error

MultiQC's official test data `data/modules/picard/HsMetrics` will trigger this error.

### MultiQC Error log

```console
$ multiqc -m picard --strict /tmp/test_data/data/modules/picard/HsMetrics/ -o /tmp/out -f

/// MultiQC 🔍 v1.25

              hook | Running INT E2E MultiQC Plugin v0.2.0
              hook | Use default search pattern for e2e_determined_sex
              hook | Use default search pattern for ngscheckmate
           multiqc | Strict mode specified. Will exit early if a module or a template crashed, and will give warnings if anything is not optimally configured in a module or a template.
       file_search | Search path: /tmp/test_data/data/modules/picard/HsMetrics
       file_search | Only using modules: picard
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 9/9  
            picard | Found 10 HsMetrics reports
       file_search | Only using modules: picard
     write_results | Data        : /tmp/out/multiqc_data
     write_results | Report      : /tmp/out/multiqc_report.html
           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Nice catch! Thanks a lot for reporting. Should be fixed with https://github.com/MultiQC/MultiQC/pull/2880
