### ISSUE TITLE
[not an issue] MultiQC v1.25 does not work with FastP output

### ISSUE THREAD

**Issue by mdtorohernando** [MultiQC/MultiQC#2878]
### Description of bug

Hi! I've been working with MultiQC for a long time and I have noticed that after doing FastP analysis, the new MultiQC v1.25 version does not work. I have tested with the v1.21 version and there it no problem. The MultiQC v1.25 is working properly on my conda env, as I have used just before with FastQC outputs without problems. 

### File that triggers the error

![image](https://github.com/user-attachments/assets/28345562-be4a-4a48-b72d-d3f3a3b04d41)
![image](https://github.com/user-attachments/assets/8f717c66-1d75-4e3b-8134-c513a0449c16)

### MultiQC Error log

```console
// MultiQC 🔍 v1.25

       file_search | Search path: /media/pgen/Disco_2/GEN00524_AliciaPou/2_Fastq_raw
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 150/150  
           multiqc | No analysis results found. Cleaning up…


 /// MultiQC 🔍 | v1.21

|           multiqc | MultiQC Version v1.25 now available!
|           multiqc | Search path : /media/pgen/Disco_2/GEN00524_AliciaPou/4_Fastq_clean
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 268/268  
|             fastp | Found 67 reports
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Hi! Sorry about the bug...

Would you be able to share the example of that fastp output, so we could reproduce and fix this quicker?

I also noticed that you ran MultiQC on different folders: `2_Fastq_raw` vs. `4_Fastq_clean`, is it still the same if you run both on the same one?

**Comment by mdtorohernando** [comment]
Yes of course! I send to you some of the fastp outputs (all of them too big for here). 
About the folders... sorry, I moved the fastp outputs from the folder 2 to folder 4, before running again MultiQC (v1.21). 

[fastp_out_part.tar.gz](https://github.com/user-attachments/files/17146813/fastp_out_part.tar.gz)

**Comment by vladsavelyev** [comment]
It worked for me:
<img width="640" alt="Screenshot 2024-09-26 at 12 39 56" src="https://github.com/user-attachments/assets/5add2707-5db0-43ea-ab19-ff6838db6e5f">

Can you double check please?

**Comment by mdtorohernando** [comment]
yep!! sorry... 
![image](https://github.com/user-attachments/assets/1255432e-cbd3-4b0a-9f46-881e3e627faa)
