### ISSUE TITLE
Regression: General Stats Custom Content Configuration No Longer Works in 1.25

### ISSUE THREAD

**Issue by schorlton-bugseq** [MultiQC/MultiQC#2900]
### Description of bug

Running v1.24 and v1.25 from bioconda in a micromamba container.

1.24 output:
![image](https://github.com/user-attachments/assets/11f8dcb1-9015-41d8-910e-351c9c314cdd)

1.25 output:
![image](https://github.com/user-attachments/assets/bdf562bf-26b4-46b2-bda3-bfecfcf302ab)

Note that none of the configuration was used in 1.25. Could a test have caught this?

### File that triggers the error

Input json:
```json
{"plot_type": "generalstats", "id": "Genome Info", "pconfig": {"Abundance": {"max": 100, "min": 0, "suffix": "%", "scale": "Blues", "description": "Abundance description"}, "Read Count": {"min": 0, "scale": "Blues", "description": "Read count description", "format": "{:,.0f}"}, "Rank": {"description": "Taxonomic rank.", "hidden": true}, "NCBI Tax ID": {"description": "NCBI taxonomy identifier.", "hidden": true}, "Lineage": {"description": "NCBI taxonomy lineage.", "hidden": true}}, "data": {"Mycobacteroides abscessus": {"Abundance": 2.934446384493557, "Read Count": 192, "NCBI Tax ID": 36809, "Rank": "Species"}}}
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://docs.seqera.io/multiqc/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Sorry about this! There was an error in the old code and in the documentation, the field name should be "headers", not "pconfig": 

```
{
   "plot_type":"generalstats",
   "id":"Genome Info",
   "headers":{
      "Abundance":{
         "max":100,
         "min":0,
         "suffix":"%",
         "scale":"Blues",
         "description":"Abundance description"
      },
      "Read Count":{
         "min":0,
         "scale":"Blues",
         "description":"Read count description",
         "format":"{:,.0f}"
      },
      "Rank":{
         "description":"Taxonomic rank.",
         "hidden":true
      },
      "NCBI Tax ID":{
         "description":"NCBI taxonomy identifier.",
         "hidden":true
      },
      "Lineage":{
         "description":"NCBI taxonomy lineage.",
         "hidden":true
      }
   },
   "data":{
      "Mycobacteroides abscessus":{
         "Abundance":2.934446384493557,
         "Read Count":192,
         "NCBI Tax ID":36809,
         "Rank":"Species"
      }
   }
}
```

I fixed the docs with https://github.com/MultiQC/MultiQC/pull/2901 and also added support for the incorrect key "pconfig" for back-compatilibity.

Thanks a lot for reporting and sorry about the issue 🙏
