### ISSUE TITLE
`cond_formatting_rules` fails in strict mode with numbers

### ISSUE THREAD

**Issue by schorlton-bugseq** [MultiQC/MultiQC#2902]
### Description of bug

Hi!

Running v1.24 from bioconda. I'm wondering if https://github.com/MultiQC/MultiQC/blob/9fa4cc6a969fff0c6cd0be09904e894bbee98558/multiqc/plots/table_object.py#L71 and/or https://github.com/MultiQC/MultiQC/blob/9fa4cc6a969fff0c6cd0be09904e894bbee98558/multiqc/config.py#L132 should be typed to also include  `floats` and `int`s, eg: `Dict[str, List[Dict[str, str | int | float]]]`? With the support of `ge` and `le` (https://github.com/MultiQC/MultiQC/pull/2494), it seems natural to put numbers in that configuration? I failed with `--strict` because of this and succeeded when I quoted my `int`s.

EDIT: also the docs show it with an `int`:
![image](https://github.com/user-attachments/assets/a910ff5c-1119-4c49-82af-5f16ed3e1ac2)

https://docs.seqera.io/multiqc/development/plots#conditional-formatting-of-data-values.

Thanks!

### Before submitting

- [X] I have read the [troubleshooting documentation](https://docs.seqera.io/multiqc/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
You are absolutely right! Sorry about this issue, and thanks for repoting
