### ISSUE TITLE
Kraken - incorrect counts for specific sample when reading multiple Kraken reports

### ISSUE THREAD

**Issue by marchoeppner** [MultiQC/MultiQC#2917]
### Description of bug

I have a bunch of "test" samples to develop a bacterial WGS pipeline against. Part of that is running Kraken2 to profile the taxonomic composition of the reads.

I found that for one sample (SRR5189060), the results differ depending on whether I run it "solo" or together with the other samples. 

When running "solo", I get ~23% Bacillus cereus and a low percentrage of other hits (which is also what is says in the Kraken report)
When running with the other samples, I get 99.5% "Other", and no B. cereus. 

This is true for both MultiQC v1.23 and v1.25

### File that triggers the error

[kraken.zip](https://github.com/user-attachments/files/17363372/kraken.zip)

### MultiQC Error log

```console
/// MultiQC 🔍 v1.25.1

   	file_search | Search path: /work_syn/ngs/pipelines/gabi/Bfr_Test/debug
     	searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 7/7  
        	kraken | Found 6 reports
 	write_results | Data    	: multiqc_data
 	write_results | Report  	: multiqc_report.html
       	multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://docs.seqera.io/multiqc/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
kraken module works by finding the top-5 species *across all samples* first, then calculates the percentages only of those 5 species, putting the rest into "others". Bacillus cereus is top-1 in SRR5189060, but it's below top-5 across all six samples, thus falling into "others".

Bacillus cereus is 6th, so if you change the `config.kraken.top_n` option to 6 or above, it will show up in the plots. See https://docs.seqera.io/multiqc/modules/kraken. E.g. in multiqc_config.yaml:

```yaml
kraken:
  top_n: 10
```

Or directly in command line:

```
multiqc /kraken --cl-config '{"kraken": {"top_n": 10}}'
```

**Comment by marchoeppner** [comment]
Thanks for the explanation. That design decision seems kinda problematic to be honest (but probably owed to limitations of how this can be displayed). I guess I'll have to live with that and find another solution to summarize that data then.
