### ISSUE TITLE
Better portability for flat plots on different systems

### ISSUE THREAD

**Issue by mahesh-panchal** [MultiQC/MultiQC#2918]
### Description of feature

I'm running MultiQC as a python package inside Quarto. One of the strengths of Quarto is that it can produce content in a variety of formats like HTML, Docx, Github Flavoured Markdown, etc. 

In order to correctly visualise the plots, I need to:

````markdown
:::: {.content-hidden when-format="html"}

```{python}
if "fastqc" in multiqc.list_modules():
    display(multiqc.get_plot("fastqc", "Sequence Duplication Levels").show(flat=True))
```

::::
````

I've built a container for this using Wave, but this is built for linux. 
- docker: `community.wave.seqera.io/library/quarto_pip_jupyter_multiqc_pruned:a0afd98904fa925c`
- singularity: `https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/27/27ad4fe625a7c22fb1c8c3ee83dda7276f0e27f68385991df88b330e46e1d930/data`
- conda:
  ```
  channels:
  - conda-forge
  - bioconda
  dependencies:
  - bioconda::multiqc=1.25
  - conda-forge::jupyter=1.1.1
  - conda-forge::pandas=2.2.3
  - conda-forge::papermill=2.6.0
  - conda-forge::quarto=1.5.57
  - conda-forge::tabulate=0.9.0
  ```
When I run this on my Mac though, I get an error:
```
                plot | 
  ===========================
  WARNING: Detected a Rosetta process, implying that MultiQC is running inside an x86_64 container, but hosted by Apple Silicon.
  
  Static plot export uses Kaleido - a tool that is unstable under conflicting architectures, so MultiQC will not save static PNG/PDF/SVG plots to disk. If you still need those, please use a container with a compatible architecture. The official Dockerhub image multiqc/multiqc:latest is available for both platforms, and can be pulled with:
  
  docker pull multiqc/multiqc:latest
  ===========================
  ------------------
```

It would be really nice not to have to build containers for each platform and have to detect what I'm running on.

**Comment by mahesh-panchal** [comment]
Just to add a bit of context, I'm making Docx to upload to Google Docs so I can get some collaborative feedback on the reports, and Github Markdown so I can store the reports in a private repo so I don't have to download or host html. If you have other ideas here, that would be appreciated.

**Comment by mahesh-panchal** [comment]
Actually I realise this isn't working ( running in Gitpod now )

The output in the docx is:
```
<IPython.core.display.HTML object>
```

Or if I change the code to:
````markdown
```{python}
if "fastqc" in multiqc.list_modules():
    multiqc.get_plot("fastqc", "Sequence Duplication Levels").show(flat=True)
```
````
nothing shows up again like in https://community.seqera.io/t/multiqc-plots-in-quarto-dont-display-generally/1252

**Comment by vladsavelyev** [comment]
The error you are getting is expected. You'd have to build an ARM image if you want to run it on ARM MacOS. 
MultiQC uses Plotly as an image backend, which is not fully portable, in particular when exporting static images.

**Comment by vladsavelyev** [comment]
Regarding your question about the `.show()` function - you are right that it's needed to be wrapped in Jupyter built-in `display`. The `show` function only outputs HTML, but it can’t tell Jupyter to display it - `display` needs to be called explicitly. Unless it's the last line in a cell, then Jupyter will call display automatically on the last output.

I updated the docs to make it a bit more clear here https://github.com/MultiQC/MultiQC/pull/2938
