### ISSUE TITLE
Missing an entire block when number of newlines is 0

### ISSUE THREAD

**Issue by achakkas** [MultiQC/MultiQC#2923]
### Description of bug

I am working on a new Cell Ranger ARC module and while testing I noticed that some of the HTML reports were skipped due to no match, but the search pattern string is present in the html files. 
Upon closer look, I noticed that the `count_and_block_tuple` is missing the one block which contains the pattern string.  
To me it looks like when the  `fp.readline()` is called after the `fp.read(block_size)` the file pointer is already moved forward by 4096 bytes, so the new block is missing those 4k bytes. This is `file_line_block_iterator` function in `report.py`

It worked fine when I changed the `block = fp.readline()` to `block = block + fp.readline()`. 

You can reproduce using the attached HTML file and maybe by adding the `Cell Ranger ARC` string to one of the existing cellranger sp. 

### File that triggers the error

[web_summary.html.gz](https://github.com/user-attachments/files/17428826/web_summary.html.gz)

### MultiQC Error log

```console
/// MultiQC 🔍 v1.26.dev0

       file_search | Search path: /reports
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 12/12  
    cellranger_arc | Found 10 Cell Ranger ARC reports
     write_results | Data        : multiqc_data   (overwritten)
     write_results | Report      : multiqc_report.html   (overwritten)
           multiqc | MultiQC complete

With verbose:
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 12/12  
[2024-10-18 01:21:33] multiqc.report                                     [DEBUG  ]  Summary of files that were skipped by the search: |skipped_module_specific_max_filesize: 12|, |skipped_no_match: 2|
[2024-10-18 01:21:33] multiqc.core.exec_modules                          [DEBUG  ]  Running module: cellranger_arc
[2024-10-18 01:21:34] multiqc.modules.cellranger_arc.cellranger_arc      [INFO   ]  Found 10 Cell Ranger ARC reports
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://docs.seqera.io/multiqc/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Good catch! Thank you 🙏 

I see you have it fixed in your PR, but I'll also add it in a separate PR.
