### ISSUE TITLE
nanostat: add metrics to general statistics table

### ISSUE THREAD

**Issue by sandratra-rab** [MultiQC/MultiQC#2928]
### Description of feature

Hi!

Is it possible to add all statistics of NanoStat module to the General Statistics table ?

Or at least the ones shown by default in NanoStat module: Read N50 (n50), Median length (median_read_length), Median quality (median_read_quality), Median identity (median_identity), Number of reads (number_of_reads), Total Bases (number_of_bases) and Total Bases Aligned (number_of_bases_aligned).

![Capture d’écran du 2024-10-23 15-52-25](https://github.com/user-attachments/assets/37dfed78-7793-48b7-ac2f-5f22ce9d78a2)

I have seen [this topic](https://community.seqera.io/t/adding-supported-tool-table-columns-to-generalstats-table/447/3) mentioning it but I don't think any issue was submitted.

Thank you

**Comment by vladsavelyev** [comment]
Addressed with https://github.com/MultiQC/MultiQC/pull/2961
Let me know if you have any feedback!
