### ISSUE TITLE
Violin plot from custom table error at 101 samples

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [MultiQC/MultiQC#2942]
### Description of bug

I have some custom content in MultiQC as a table, and I would like to use the violin plot to visualize the distribution. This appears to work for up to 100 samples, but fails at 101 samples.

At 100 samples, you get a violin and scatter plot (you see the dots) for each of the samples.
At 101 samples, you still get the violin plot, but only around ~5 dots per columns (it varies between columns).

### File that triggers the error

This file has 101 samples, and does not show sample dots in the violin plot mode. [merged_expression_forward_mqc.tsv.zip](https://github.com/user-attachments/files/17584895/merged_expression_forward_mqc.tsv.zip)

Simply delete one of the rows and re-run MultiQC to see the bug go away.

### MultiQC Error log

```console
multiqc --force --filename ~/tmp/multiqc_report.html .

/// MultiQC 🎃 v1.25.1

       file_search | Search path: custom-content/t
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1  
    custom_content | mqc_expression_forward: Found 101 samples (PlotType.TABLE)
     write_results | Data        : tmp/multiqc_report_data   (overwritten)
     write_results | Report      : tmp/multiqc_report.html   (overwritten)
           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://docs.seqera.io/multiqc/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
When the number of samples is >100, the violin plot will not show all data points for performance reasons, instead show only outliers. It can be customized however with a configuration option in `multiqc_config.yaml`:

```yaml
violin_min_threshold_outliers: 100
```
