### ISSUE TITLE
Scatter plot from custom table too zoomed in

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [MultiQC/MultiQC#2943]
### Description of bug

When creating a scatter plot from a custom table, the figure is too zoomed in, resulting in samples being clipped from the view. I have not confirmed if this bug occurs with all tables, or only custom tables.

A quick workaround is to double click the figure, this will re-size the figure and make all samples visible.

### File that triggers the error

[expression_forward_mqc.tsv.zip](https://github.com/user-attachments/files/17585166/expression_forward_mqc.tsv.zip)

Create a scatter plot of MT-ND3 vs MT-ND4L, notice how the green sample is missing.
![image](https://github.com/user-attachments/assets/5199b3b6-0c17-46cf-b259-c6fc7fcdad4d)

Double click the figure to resize:
![image](https://github.com/user-attachments/assets/bcf53293-4a5c-4087-af13-24c5d0fc4535)

### MultiQC Error log

```console
multiqc --force --filename ~/tmp/multiqc_report.html .

/// MultiQC 🎃 v1.25.1

       file_search | Search path: tmp/q
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1  
    custom_content | mqc_expression_forward: Found 3 samples (PlotType.TABLE)
     write_results | Data        : tmp/multiqc_report_data   (overwritten)
     write_results | Report      : tmp/multiqc_report.html   (overwritten)
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://docs.seqera.io/multiqc/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Thanks for reporting and for the reproducible example! Should be straightforward to fix - will take a look

**Comment by vladsavelyev** [comment]
Done with https://github.com/MultiQC/MultiQC/pull/2956
