### ISSUE TITLE
FastQC files with identical prefixes are not treated as separate files and can be mixed together in processing.

### ISSUE THREAD

**Issue by NickJD** [MultiQC/MultiQC#2950]
### Description of bug

Hi - I have tried to find examples of this being reported before but I can't seemingly find the correct definition of the problem.

Basically I have FastQC output for each sample as the following:
AT10_R1_001_fastqc.html
AT10_R1_001_fastqc.zip
AT10_R1_001.trimmed_fastqc.html
AT10_R1_001.trimmed_fastqc.zip
AT10_R2_001_fastqc.html
AT10_R2_001_fastqc.zip
AT10_R2_001.trimmed_fastqc.html
AT10_R2_001.trimmed_fastqc.zip

We can see that these files share the same prefix **AT10_R1_001**_fastqc.html and **AT10_R1_001**.trimmed_fastqc.html

So when I run multiqc it looks like it randomly selects one of the other and sometimes one from each and combines them into a single report.

` grep AT25 multiqc_data_1/multiqc_sources.txt `
FastQC	all_sections	AT25_R2_001	xx/FastQC/AT25_R2_001_fastqc.zip
FastQC	all_sections	AT25_R1_001	xx/FastQC/AT25_R1_001_fastqc.zip
`grep AT15 multiqc_data_1/multiqc_sources.txt `
FastQC	all_sections	AT15_R2_001	xx/FastQC/AT15_R2_001_fastqc.zip
FastQC	all_sections	AT15_R1_001	xx/FastQC/AT15_R1_001_fastqc.zip
`grep AT10 multiqc_data_1/multiqc_sources.txt` 
FastQC	all_sections	AT10_R2_001	xx/FastQC/AT10_R2_001.trimmed_fastqc.zip
FastQC	all_sections	AT10_R1_001	xx/FastQC/AT10_R1_001_fastqc.zip

The error log below shows that while it seems all 288 files are scanned, only 72 reports are generated (72*4==288).

I think the '-d' parameter sort of accounts for this issue if the FastQC files sit in different directories but in my case that are all together so not sure this is actually a [fix](https://docs.seqera.io/multiqc/getting_started/running_multiqc#directory-prefixes-in-sample-names).

Thanks in advance.

### MultiQC Error log

```console
multiqc .

/// MultiQC 🔍 v1.25.1

       file_search | Search path: xx/FastQC
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 288/288  
            fastqc | Found 72 reports
     write_results | Data        : multiqc_data
     write_results | Report      : multiqc_report.html
           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://docs.seqera.io/multiqc/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Hi @NickJD,

That's by design - the sample name is extracted from the file name by trimming the exts specified in the config (which includes `_trimmed` too: https://github.com/MultiQC/MultiQC/blob/main/multiqc/config_defaults.yaml#L347), so both files end up corresponding to the same sample and get overwritten in the report.

Possible solutions would be either:
- use `-d` or `--fullnames` options - see docs: https://docs.seqera.io/multiqc/getting_started/config#clashing-sample-names
- override `fn_clean_trim` using a [custom config](https://docs.seqera.io/multiqc/getting_started/config); 
- rename the FastQC files before passing them to MultiQC.

**Comment by NickJD** [comment]
Well, that's frustrating and embarrassing. 
I thought I had checked the docs but either I was looking at an older version or not close enough. 

Thank you for the confirmation
