### ISSUE TITLE
Critical bug: bcl2fastq module broken

### ISSUE THREAD

**Issue by sschmeier** [MultiQC/MultiQC#2964]
### Description of bug

I am seeing missing information in the output of the bcl2fastq module particularly the `multiqc_bcl2fastq_bysample.txt` file, where the `R*_yield`, and `R*_QC30` values are all zero. 

![image](https://github.com/user-attachments/assets/5445b516-c6b1-420d-857e-c5832ae63ac9)

Introduced in  [https://github.com/MultiQC/MultiQC/pull/2864](https://github.com/MultiQC/MultiQC/pull/2864).  Line [322](https://github.com/MultiQC/MultiQC/blame/29c2c1840167d2cb649cf30425501ae66dbb00a3/multiqc/modules/bcl2fastq/bcl2fastq.py#L322 )  and following 2 lines + Line [348](https://github.com/MultiQC/MultiQC/blob/29c2c1840167d2cb649cf30425501ae66dbb00a3/multiqc/modules/bcl2fastq/bcl2fastq.py#L348). mixes up variable `r` and `r_num`. all `r` at these lines should all be set to `r_num`.

Sorry not able to sent a PR right now to fix this. can do later.

### File that triggers the error

Any `Stats.json` file from bcl2fastq will reproduce this error.

### MultiQC Error log

```console
There is no information of importance in the logs as no warning or error is raised.
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://docs.seqera.io/multiqc/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [ ] I have included a full MultiQC log, not truncated.
- [ ] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Oh, this is bad... Sorry about this issue, thank you for reporting and very huge thanks for providing a follow up with the fix 🙏

**Comment by sschmeier** [comment]
You are welcome!
