### ISSUE TITLE
GTDB-Tk

### ISSUE THREAD

**Issue by harper357** [MultiQC/MultiQC#2971]
### Name of the tool

GTDB-Tk

### Tool homepage

https://ecogenomics.github.io/GTDBTk/index.html

### Tool description

Taxonomy classifier

### Tool output

[gtdbtk_summary.tsv.zip](https://github.com/user-attachments/files/17807196/gtdbtk_summary.tsv.zip)

### Log filename pattern

*summary.tsv

### Data suitable for MultiQC plot(s)

A table of some of the columns in the output

### Most interesting data for the General Stats table

Since it is about the MAGs/genomes and multiple MAGs can come from a genome, I am not sure if there are any without having other information

### Before submitting

- [X] I have included example data (zipped, not pasted) that can be used to write the module.

**Comment by harper357** [comment]
I just submitted a PR for this tool. #2970

**Comment by vladsavelyev** [comment]
PR is merged 👍
