### ISSUE TITLE
Duplicated reads (flagged), %

### ISSUE THREAD

**Issue by mtochilkina** [MultiQC/MultiQC#2972]
### Description of feature

Hello!

Could you please add the Qualimap metric `Duplicated reads (flagged), %`  to the General Statistics. This information is available in the Qualimap PDF report (screenshot below). 
![image](https://github.com/user-attachments/assets/4827fa4f-66ac-46b7-a769-9e099fba12b0)

**Comment by vladsavelyev** [comment]
Added in https://github.com/MultiQC/MultiQC/pull/2989

**Comment by mtochilkina** [comment]
Thank you very much!
