### ISSUE TITLE
Top Unknown Barcodes does not have a 'per-lane' option and only shows barcodes from lane 1

### ISSUE THREAD

**Issue by alexiswl** [MultiQC/MultiQC#2975]
### Description of bug

Hello, 

Running MultiQC version 1.25.1 I've noticed that the Undetermined Barcodes by lane shows only lane 1, and there is no option to view the other lanes.  

Steps to reproduce:

Unzip the reports folder below into a subfolder to emulate an instrument run output.  

```
unzip <run.zip>
docker run \
  --workdir "$PWD" \
  --volume "$PWD:$PWD" \
  ghcr.io/multiqc/multiqc:latest \
    multiqc \
      --outdir outputs \
      .
```

[outputs.zip](https://github.com/user-attachments/files/17824879/outputs.zip)

### File that triggers the error

[241114_A00130_0338_BH2NNHDSXF.zip](https://github.com/user-attachments/files/17824891/241114_A00130_0338_BH2NNHDSXF.zip)

### MultiQC Error log

```console
/// MultiQC 🔍 v1.25.1

       file_search | Search path: /tmp/tmp.9axvNvoC0g

        bclconvert | Found runs: 72, samples: 72

     write_results | Data        : outputs/multiqc_data
     write_results | Report      : outputs/multiqc_report.html
           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://docs.seqera.io/multiqc/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Good call! It shows the top 20 barcodes unsorted: https://github.com/MultiQC/MultiQC/blob/main/multiqc/modules/bclconvert/bclconvert.py#L1093
Should add sorting there before slicing
