### ISSUE TITLE
File pattern for DeDup is too broad

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [MultiQC/MultiQC#2979]
### Description of bug

The DeDup module matches any file that ends in "dedup.json", regardless of the content. This can cause it to 'capture' log files away from other modules, resulting in an incomplete MultiQC report.

### Before submitting

- [X] I have read the [troubleshooting documentation](https://docs.seqera.io/multiqc/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Good call - changed in https://github.com/MultiQC/MultiQC/pull/2988
