### ISSUE TITLE
Capturing log files from other modules

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [MultiQC/MultiQC#2980]
### Description of bug

It looks like MultiQC only passes each logfile to the first matching module, even if that module then gives an error because it cannot parse the log file. Would it be possible to pass the log files to each matching module, to prevent one module for 'capturing' the log files from another module? See https://github.com/MultiQC/MultiQC/issues/2979 for an example when this happens.

### Before submitting

- [X] I have read the [troubleshooting documentation](https://docs.seqera.io/multiqc/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
We don't do that for efficiency. But some modules use [a `shared` flag](https://docs.seqera.io/multiqc/development/modules#step-1---find-log-files) in search patterns to indicate that they don't consume the logs.

The DeDup module was a bad one, it should have looked into the file contents, or used `shared` if the file contents wasn't specific enough. I fix that now with another PR.

Note that you can also specify the list of modules you want to run with the `-m` option (e.g. `multiqc -m samtools -m fastqc .`, so unwanted modules don't trigger.
