### ISSUE TITLE
Qualimap BamQC: override --genome-gc-distr from config

### ISSUE THREAD

**Issue by serge2016** [MultiQC/MultiQC#2987]
### Description of feature

Hello! Thank you for a great tool!!!
Could you, please, add a config option to the `qualimap_config` section to override the setting in the qualimap report (if `--genome-gc-distr` was not provided or is not correct, like hg19 instead of hg38)?

**Comment by vladsavelyev** [comment]
This is parsed from QualiMap output. MultiQC doesn't have knowledge of GC distributions, so unfortunately can't override that
