### ISSUE TITLE
nan % in InterOp graphs

### ISSUE THREAD

**Issue by Stikus** [MultiQC/MultiQC#2991]
### Description of bug

If some values in InterOp summary file are `nan` it results graphs with `nan %` - we assume it is incorrect visualization:

![image](https://github.com/user-attachments/assets/ad24d8ba-1604-4409-a7b9-2f0a3b0fc89f)

### File that triggers the error

[TEST.interop_summary.csv](https://github.com/user-attachments/files/17931203/TEST.interop_summary.csv)

### MultiQC Error log

```console
root@e0dc2475a920:/outputs# multiqc inputs/

/// MultiQC v1.25.2

            config | Loading config settings from: /soft/MultiQC-1.25.2/local/lib/python3.10/dist-packages/multiqc_config.yaml
       file_search | Search path: /outputs/inputs
        searching | ████████████████████████████████████████ 100% 1/1
           interop | Found 1 reports
            violin | All values are NaN or Inf for metric: Error Rate (%)
            violin | All values are NaN or Inf for metric: Error Rate (%)
            violin | All values are NaN or Inf for metric: Error Rate 35 Cycles (%)
            violin | All values are NaN or Inf for metric: Error Rate 75 Cycles (%)
            violin | All values are NaN or Inf for metric: Error Rate 100 Cycles (%)
     write_results | Data        : multiqc_data
     write_results | Report      : multiqc_report.html
           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://docs.seqera.io/multiqc/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Thanks for reporting, addressed with https://github.com/MultiQC/MultiQC/pull/2995
