### ISSUE TITLE
Building Docker image from latest commit fails

### ISSUE THREAD

**Issue by jethror1** [MultiQC/MultiQC#2992]
### Description of bug

Attempting to build the Docker image locally from latest commit on fresh git clone of the repo fails:
```
Sending build context to Docker daemon  17.54MB
Step 1/17 : FROM python:3.12-slim
3.12-slim: Pulling from library/python
2d429b9e73a6: Already exists 
52a9b53e12bf: Already exists 
7fe47536e82b: Already exists 
ae157567daae: Already exists 
Digest: sha256:2a6386ad2db20e7f55073f69a98d6da2cf9f168e05e7487d2670baeb9b7601c5
Status: Downloaded newer image for python:3.12-slim
 ---> 668757ec60ef
Step 2/17 : LABEL author="Phil Ewels & Vlad Savelyev"       description="MultiQC"       maintainer="phil.ewels@seqera.io"
 ---> Running in ec57cb8e0962
Removing intermediate container ec57cb8e0962
 ---> f822ba4d94f1
Step 3/17 : RUN mkdir /usr/src/multiqc
 ---> Running in cd854654718f
Removing intermediate container cd854654718f
 ---> 0f1ca18d0817
Step 4/17 : COPY LICENSE /usr/src/multiqc/
 ---> b7972116d18f
Step 5/17 : COPY README.md /usr/src/multiqc/
 ---> d2f7bcf73de7
Step 6/17 : COPY docs /usr/src/multiqc/docs
COPY failed: file not found in build context or excluded by .dockerignore: stat docs: file does not exist
```

It looks to be an issue between the `COPY` step of copying in the docs and the `docs` directory being added into the `dockerignore` file from [this](https://github.com/MultiQC/MultiQC/commit/ee1f63e5660e237f8056a284156553ad4b6df8f8) commit.

### Before submitting

- [X] I have read the [troubleshooting documentation](https://docs.seqera.io/multiqc/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Thanks a lot for spotting and reporting this! Fixed with https://github.com/MultiQC/MultiQC/pull/2994
