### ISSUE TITLE
fastp: visualize overrepresented sequences

### ISSUE THREAD

**Issue by zoeward-nz** [MultiQC/MultiQC#2997]
The over represented sequences are present in the fastp html and json but not displayed in multiqc plots.
I have attached  files for one sample to demonstrate.
Have tried multiQC v1.19 and v1.21
[AA10-1_S9_L001_fastp_report.json](https://github.com/user-attachments/files/17984237/AA10-1_S9_L001_fastp_report.json)
[Uploading multiqc_data.json…]()

### Before submitting

- [X] I have read the [troubleshooting documentation](https://docs.seqera.io/multiqc/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
This feature was not implemented, so it's not expected to plot it. I'll take a look into adding it.

**Comment by vladsavelyev** [comment]
Addressed with https://github.com/MultiQC/MultiQC/pull/3000
