### ISSUE TITLE
multiqc 1.25.2 does not recognize samtools output

### ISSUE THREAD

**Issue by reshu23** [MultiQC/MultiQC#2998]
### Description of bug

Dear Team, 
I am using multiqc 1.25.2 singularity image(https://depot.galaxyproject.org/singularity/). multiqc is not recognizing samtools output. Here is the few lines of file. Size of my stats file is 34M. And name of file is:"Sample_alignedStats.tsv"
![image](https://github.com/user-attachments/assets/cf6c4d4b-20c5-40db-827e-4b852b1cb4f8)
multiqc .

### Before submitting

- [X] I have read the [troubleshooting documentation](https://docs.seqera.io/multiqc/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
34M sounds like a very large file. Is it expected?

Please run MultiQC in verbose mode: `multiqc -v .` and attach the log.

Please also attach the samtools file if possible.

**Comment by reshu23** [comment]
Thank you. Yes, size is expected. Please find attached log file as well as samtools stats.
[testAlignment.tar.gz](https://github.com/user-attachments/files/18032978/testAlignment.tar.gz)

**Comment by vladsavelyev** [comment]
The file attached is actually 100MB. MultiQC ignores files above 50MB.

To parse large files, adjust the `log_filesize_limit` configuration option:
https://docs.seqera.io/multiqc/usage/troubleshooting#big-log-files

**Comment by vladsavelyev** [comment]
And you can actually see that information in the log:

> [DEBUG  ]  Summary of files that were skipped by the search: |skipped_filesize_limit: 1|

**Comment by reshu23** [comment]
Can you please tell me, how to change config file inside the singularity image?

**Comment by reshu23** [comment]
Thank you. I managed to sort it out by declaring export MULTIQC_LOGFILE_SIZE_LIMIT=2000000000.
