### ISSUE TITLE
Barcode item sorting option

### ISSUE THREAD

**Issue by abattenhouse** [MultiQC/MultiQC#3004]
### Description of feature

I've got to the trouble of listing my barchart items (in a tsv file) in the order I want them to appear in the plot, but they appear alphabetically, and I have to provide altered item names to get them to sort as desired. It would be great to have a "sort_rows" option for barchart like there is for tables.

**Comment by vladsavelyev** [comment]
It exists as `sort_samples`

```
from multiqc.plots.bargraph import plot

plot(
    {
        "sample 10": {"A": 1, "B": 3, "C": 2, "D": 4},
        "sample 2": {"A": 1, "B": 3, "C": 2, "D": 4},
        "sample 1": {"A": 4, "B": 2, "C": 5, "D": 3},
    },
    pconfig={
        "id": "test",
        "title": "test plot",
        "sort_samples": False,
    }
).show()
```

<img width="663" alt="Screenshot 2024-12-11 at 12 16 42" src="https://github.com/user-attachments/assets/bc8c721d-e1c1-4d4f-ae13-cb0986aa2508">
