### ISSUE TITLE
{Question]: Is it possible to run MultiQC with data from previous run 

### ISSUE THREAD

**Issue by tamuanand** [MultiQC/MultiQC#3005]
Hi

I have used MultiQC 1.15 and I have a multiqc_data folder from my previous run. 

Is it possible to use that multiqc_data folder and run latest version of MultiQC on it.

Thanks in advance.

**Comment by vladsavelyev** [comment]
Hi,

Not on `multiqc_data` folder, unfortunately. You would need the original QC files that were passed into MultiQC.

That's something that we might work on to implement in the future though.
