### ISSUE TITLE
Add qualimap rnaseq metrics to general statistics

### ISSUE THREAD

**Issue by mtochilkina** [MultiQC/MultiQC#3015]
### Description of feature

Hello!

Could you please add the following Qualimap rnaseq metrics to the General Statistics: absolute values and percents for exonic, intronic,  intergenic and overlapping exon.
This information is available in the Qualimap txt report (screenshot below) and is used to construct graphics, but is not included in General Statistics.
![image](https://github.com/user-attachments/assets/52d17d34-693f-4bbb-9438-70f2d74723fc)

**Comment by vladsavelyev** [comment]
They are already a part of the barplot "Genomic origin of reads", but worth adding the "overlapping exon" as hidden
