### ISSUE TITLE
Mosdepth module: Axis order on "Average coverage per contig" plot

### ISSUE THREAD

**Issue by tstoeriko** [MultiQC/MultiQC#3032]
### Description of bug

The order of the categorical x-axis in the "Average coverage per contig" plot for the mosdepth module changes when a samples is missing one of the regions. It looks like regions shared by all samples are prioritized and regions only present in some samples are pushed to the end of the axis. 
In combination with the line plot this is an issue as the line itself is plotted in a different order leading to the line crossing over itself (see screenshot).
This is potentially a result of the solution to [this issue](https://github.com/MultiQC/MultiQC/issues/1568).
Supplying the files in inverted order does not change this behavior.

![grafik](https://github.com/user-attachments/assets/570b4365-7a0f-489a-ad3d-15e9d499c2df)

### File that triggers the error

[2M.mosdepth.global.dist.txt](https://github.com/user-attachments/files/18196455/2M.mosdepth.global.dist.txt)
[20K.mosdepth.global.dist.txt](https://github.com/user-attachments/files/18196456/20K.mosdepth.global.dist.txt)

### MultiQC Error log

```console
$ multiqc 20K.mosdepth.global.dist.txt 2M.mosdepth.global.dist.txt

/// MultiQC 🎄 v1.25.2

       file_search | Search path: 20K.mosdepth.global.dist.txt
       file_search | Search path: 2M.mosdepth.global.dist.txt
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 2/2
          mosdepth | Found reports for 2 samples
     write_results | Data        : multiqc_data
     write_results | Report      : multiqc_report.html
           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://docs.seqera.io/multiqc/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Great catch, thank you for reporting this bug! Will try to fix it asap.
