### ISSUE TITLE
Beeswarm plot ignores hidden table columns

### ISSUE THREAD

**Issue by vladsavelyev** [MultiQC/MultiQC#452]
Hi Phil, 

I ran MultiQC against 500+ samples, and I really like how the general table turned into a kind of a scatter plot that gives a comprehensive overview for the full project. However I got a couple issues with that. 
1. The metric names that wrap into two lines are slightly trimmed.
2. The table ignores the "hidden" property and seems to show all metrics. 

I'm wondering if there something wrong with my browser or that's a MultiQC issue?

![screen shot 2017-04-20 at 18 12 41](https://cloud.githubusercontent.com/assets/1575412/25238060/02973e38-25f5-11e7-83dd-d9a8c691c221.png)

**Comment by ewels** [comment]
Aha! Glad you like it. I'm still not totally happy with it, I've been meaning to rewrite it for a while, but it's pretty tricky - HighCharts doesn't support this plot type, so it's essentially hand-written by me in javascript. Hence the weird artefacts! I've vaguely been thinking of switching to [plot.ly](https://plot.ly/javascript/) instead, which has a lot more plot types and could also generate flat image plots, but it'd be a lot of work. We'll see..

1. It could be that I set a hard limit on the height of the plot? Not sure. But you should be able to drag the grey bar down to make it taller. I'll see if I can set a min-height for the rows to prevent this.
2. Apologies, it probably does ignore this. I'll have a look into it.

Phil

**Comment by ewels** [comment]
Hmm - I guess there's no interface to configure shown / hidden fields with the beeswarm plot. So if I hide them then they'll be gone for good. May need to write an entire configuration front-end for this, which will be a bigger job.

**Comment by vladsaveliev** [comment]
Regarding trimming, I removed the tool names from labels (those `QualiMap<br>` parts) in my MultiQC fork, and the beeswarm looks great for me now. I needed to share the report with others so just dragging the bar won't work. So I'm all good now, but if you plan to improve the plot in general in some future, that would be super awesome - we'll likely have more large-scale projects.
