### ISSUE TITLE
Bug/unexpected behavior of 'ylab' when using linegraph.plot with 'data_labels'

### ISSUE THREAD

**Issue by winni2k** [MultiQC/MultiQC#557]
**Description of bug:**
When multiqc generates a plot that specifies `data_labels` to the `pconfig` argument of `linegraph.plot` without specifying `ylab` to `pconfig`, then initially the y-axis title is not displayed.

A workaround for this problem is to specify `ylab` in the `pconfig` dict directly.  An example of this workaround can be seen in https://github.com/ewels/MultiQC/blob/master/multiqc/modules/fastqc/fastqc.py#L423. Note how 'Count' is specified twice: Once on line 423 and once at https://github.com/ewels/MultiQC/blob/master/multiqc/modules/fastqc/fastqc.py#L433.

I think the correct behavior is to raise an error when `ylab` is specified both in `pconfig` and `data_labels`, as `ylab` in `pconfig` is redundant in this case.

**Comment by wkretzsch** [comment]
Perhaps a warning might be more appropriate. I can't really judge. I'd just like instant feedback as a dev.

**Comment by ewels** [comment]
Ah yes, good spot. This is because `ylab` predates the `data_labels` option and is used when there are no data labels. I think it'd probably be fine to just set `ylab` to `data_labels[0]['ylab']` if it's not set. Can log a warning if you like - I suspect that quite a lot of plots may do it. I tend to not throw exceptions basically ever if I can avoid it, but I agree that warnings can be helpful when developing 👍 

Phil

**Comment by wkretzsch** [comment]
I agree.  `data_labels[0]['ylab']` is what should be used. 

On further reflection, I'm not sure how I feel about throwing a warning for devs. Defining both `ylab` and `data_labels[0]['ylab']` is confusing, so maybe to enforce style it would be useful to throw a warning.

**Comment by wkretzsch** [comment]
I have also noticed that overriding `yDecimals` and `tt_label` does not work in `data_labels`. It appears that [that is not supported](http://multiqc.info/docs/#switching-datasets)?

**Comment by ewels** [comment]
Nope, not yet - I have to add those in manually so I have just done them as-needed so far. Please add a new issue for that and I'll look into it.

**Comment by ErikDanielsson** [comment]
This should be solved as of https://github.com/ewels/MultiQC/commit/cbad169f2097705c146268f7a66397c686cb6766.
