### ISSUE TITLE
module htseq-count: misinterpretation of input?

### ISSUE THREAD

**Issue by antem** [MultiQC/MultiQC#624]
Hi Phil,

I just run the HTSeq-count module of MultiQC the first time and stumbled over the `% assigned`-calculation:
The count in the field `__alignment_not_unique` can account for the number of alignments rather than the number of reads. In this case a read mapping multiple times will increase this number also multiple times.

The `% assigned` would misleading in case of a lot multiple alignments.
AFAIK, this is issue is aligner-depending - whether it sets a the NH-field in the SAM/BAM-file or not. Therefore, it's not deducible from the HTSeq-count output itself. 

I'd suggest to include into the `% assigned calculation` next to the counted features, only `__no_feature` and `__ambiguous`. The `% assigned` would refer to the number of uniquely mapping reads.

Cheers,

Michael

**Comment by ewels** [comment]
Hi @antem,

I completely agree, this is a little misleading. I guess you're mostly talking about the columns in the General Statistics tables? At the very least all of the text from the module should say `alignments` instead of `reads`. We could also write a help text for the bar plot explaining each category.

I would prefer not to change the calculation unless we think that it's actually incorrect. Do any alignments in the BAM files end up in multiple categories?

Phil

**Comment by antem** [comment]
Hi @ewels ,
thanks for your quick response. 
Your question gets to the heart of the matter. It strongly depends on the aligner:
For instance Tophat2 generates perfect BAM files for HTSeq-count; Bowtie2 on the other hand does not.
The first one adds the `NH` tag to the alignment, stating for each alignment how often the read was mapped. If this is available, HTSeq-count will use this information.
Bowtie2 does not include the `NH` tag. In my experiments , this led to counting all alignments, even the multi-mapping ones. This could only be circumvented by setting the mapq-parameter accordingly.

I've checked HTSeq's documentation and they have included parameters for "non-uniqueness" in the newer versions. 

My point is that the HTSeq-count statistics especially the `__alignment_not_unique `depend strongly on the used aligner, its setting and the HTSeq-count settings. This information is not available in the result table. Therefore, I'd suggest to only include those features one can rely on.

Cheers,

Michael

**Comment by ewels** [comment]
Ok, so would you be happy if we drop `% Aligned` from the General Stats table, and add a caution about the counts above the bar plot?

Phil

**Comment by antem** [comment]
I'd be happy with it. Maybe @simon-anders or @iosonofabio from htseq can elaborate on this.

Best,
Michael

P.S.: Sorry for the delay, I've missed the email.

**Comment by iosonofabio** [comment]
There are relatively new options in `htseq-count` for this (I had the same issue):
`--secondary-alignments ignore --supplementary-alignments ignore`

**Comment by ewels** [comment]
Thanks @iosonofabio - so would you be happy with my [suggestion above](#issuecomment-343420772) for MultiQC? Presumably there's no way to know from the output file whether those flags were used?

Phil

**Comment by iosonofabio** [comment]
hi @ewels, let me add one thing that I think is important. Just because some statistics depend on the options used, this does not mean that "we cannot rely on them". Knowing the number of multimappers, unaligned, etc. is a key piece of quality control for many projects.

**The fact that the statistics depend on the settings is a power users should harness, not a bug they should avoid ;-)**

**Comment by ewels** [comment]
Sure, that’s my view too :) But we can try to be careful with wording and explicit warnings so that users are clear about where the numbers came from and what they mean.. MultiQC is a little special in some respects as those reading the reports are often not the same people who ran the analysis..

**Comment by iosonofabio** [comment]
Agreed, you know better ;-)

In any case, the reason I added those two options is exactly for this particular use, when you wanna make sure that *each read counts as 1*.

**Comment by antem** [comment]
Hi @iosonofabio , 
thanks for your input. I guess the point is collecting statistics using solely the htseq-count output - without information how the counts were generated - it is hard to impossible to generate universally valid statements.
