### ISSUE TITLE
Peddy: new sex_check plot

### ISSUE THREAD

**Issue by aledj2** [MultiQC/MultiQC#736]
Hi Phil,

Cheeky request but I saw you have an upcoming MultiQC hackathon and thought I'd suggest an extra plot which has been on my to-do list for a while now.

In peddy there is a sex_check.png (below) which would be a useful plot to add in.  ![sex_check.png](https://user-images.githubusercontent.com/5880128/38982218-2e76218a-43b9-11e8-9f32-c0316ff994e8.png) 

`ped_sex` and `predicted sex` are in the `sex_check.csv` and `sex_het_ratio` is in `peddy.ped`. 

The use case is a visual cue that sex mismatches have been identified correctly. 
On the attached plot one there are two samples with a sex-het ratio between 0.4 and 0.6.
The "male" with the sex-het ratio approaching 0.6 in this plot has been mislabelled as male but because the peddy cutoff is quite high it was identified as male so was not flagged as incorrect. Similarly the "female" had quite a low sex-het ratio so was identified as male and labelled as a sex mismatch.

Obviously we could/should reduce the peddy threshold but I think this plot would be very useful in highlighting issues regardless.

Thanks,
Aled

**Comment by ewels** [comment]
Hah, I should be more careful - you never know who's listening ;)

Sounds like a good idea! And the plot should be fairly easy to build I think. Thanks for the suggestion!

**Comment by aledj2** [comment]
Hopefully this doesn't spark a deluge of requests now! When/where is the hackathon?


Aled

________________________________

**Comment by ewels** [comment]
It's part of a meeting that's held at SciLifeLab called NASPM (_Nordic Association for Sequencing and Personalised Medicine_ I believe). I'm not sure of exactly how many people will be there - I don't think that it'll be huge and it's only an afternoon, but hopefully we can tick off a few tasks. Also depends on whether people turn up with their own MultiQC projects or not.

We had a nice MultiQC session at the codefest hackathon at BOSC last year which went really well. Sadly I can't be there this year. I will keep my eye out for any other opportunities though ;)

**Comment by ewels** [comment]
We have a nice new plot for this - however we're a bit confused about the x axis in your example plot. `predicted sex` seems to be binary string value, not continuous as shown in your example. Are you plotting something else here?

**Comment by ewels** [comment]
Aha, I had missed that `ped sex` and `predicted sex` were different and that the colour was important. And yes, I guess the x axis values could just be random.

**Comment by vladsavelyev** [comment]
Added the colors to the plot: https://github.com/MultiQC/MultiQC/issues/736 finally can close this one 😅
