### ISSUE TITLE
RSeqQC : parse read_quality graphics

### ISSUE THREAD

**Issue by drbecavin** [MultiQC/MultiQC#738]
* **Name of tool:**
    * RSeqQC - read_quality.py
* **Tool description:**
    * According to SAM specification, if Q is the character to represent “base calling quality” in SAM file, then Phred Quality Score = ord(Q) - 33. Here ord() is python function that returns an integer representing the Unicode code point of the character when the argument is a unicode object, for example, ord(‘a’) returns 97. Phred quality score is widely used to measure “reliability” of base-calling, for example, phred quality score of 20 means there is 1/100 chance that the base-calling is wrong, phred quality score of 30 means there is 1/1000 chance that the base-calling is wrong. In general: Phred quality score = -10xlog(10)P, here P is probability that base-calling is wrong
* **Tool homepage:**
    * http://rseqc.sourceforge.net/#read-quality-py
* **Complete log file output:**
    * 
[New_Am_IP_4_qual.qual.boxplot.pdf](https://github.com/ewels/MultiQC/files/1931306/New_Am_IP_4_qual.qual.boxplot.pdf)
[New_Am_IP_4_qual.qual.heatmap.pdf](https://github.com/ewels/MultiQC/files/1931307/New_Am_IP_4_qual.qual.heatmap.pdf)
* **Log filename pattern:**
    * _qual.qual.boxplot.pdf  and  _qual.qual.heatmap.pdf
* **Most interesting data for General Stats table:**
    * Phred quality score
* **Data suitable for MultiQC plot(s):**
    * Good boxplot and heatmap for MultiQC

**Comment by ewels** [comment]
Ah, MultiQC can’t process PDF files. Is there text output as well? I have a feeling that other RSeQC submodules get the numbers from R scripts that are dynamically generates by RSeQC (yuk 😔)

I don’t think that the heat map will work as there are too many dimensions of data to plot easily for multiple samples. I could take the median values from the boxplot and plot these as lines though (as with the FastQC phred score plot).

**Comment by drbecavin** [comment]
Ah yes I see... For this specific module there are only .pdf files and the r script used to generate the PDF (see attached). But you're right it will be hard to display these information for all datasets...
Although the R script is very simple and use no complicated package except the 'base' package and 'pdf'.

**Comment by ewels** [comment]
Thanks! MultiQC doesn't run the R scripts, it uses regular expressions to recognise and pull out the data values. So libraries etc. aren't important.

**Comment by ewels** [comment]
This R script is actually pretty horrible to parse. How much do you need this plot? I feel like it's pretty similar to the output from FastQC if I'm honest (which the majority of users run in addition anyway). I'm tempted to say that this one isn't worth the effort...
