### ISSUE TITLE
Add samtools flagstats % duplicates in general stats table

### ISSUE THREAD

**Issue by mfoll** [MultiQC/MultiQC#840]
The percentage of duplicated reads is not reported. Only the number of duplicated reads is reported in samtools flagstats module.

One needs to calculate it as `100*duplicates_passed/total_passed`, these two values being already processed by MultiQC. 

More generally, the samtools flagstats module could give the choice to view all the statistics as a percentage of the total number of reads (in this case having the % of duplicates in the general stat would still be useful).

![image](https://user-images.githubusercontent.com/3366818/46137459-f6928a00-c249-11e8-8455-5ae37ba7f729.png)

**Comment by vladsavelyev** [comment]
Dot plots were replaced with violin plots, and adding a switch was relatively easy:

<img width="1133" alt="Screenshot 2024-03-08 at 20 06 02" src="https://github.com/MultiQC/MultiQC/assets/1575412/756c743e-8a35-474d-96d7-4f006249f41b">
<img width="1153" alt="Screenshot 2024-03-08 at 20 06 07" src="https://github.com/MultiQC/MultiQC/assets/1575412/e7b5a2f4-0cde-46e3-a66b-c43fe811eecd">
