### ISSUE TITLE
Add plot scaling for command line export

### ISSUE THREAD

**Issue by jgesell-zz** [MultiQC/MultiQC#876]
We are working with the png images produced by MultiQC, and incorporating them into a report, however, when we do so, the default font size is far too small.  We were wondering if there is a way that we could increase or decrease the default font size, especially for the figure legends, from the command-line, if such a function does not already exist.

**Comment by ewels** [comment]
Hi @jgesell,

Does this have to be from the command line or can you use the HTML export feature? If you can use the HTML, then this feature already exists:

![image](https://user-images.githubusercontent.com/465550/50277108-e1418c00-0443-11e9-8d67-71dd8b280899.png)

Phil

**Comment by blavetn** [comment]
Hello, I have the same request but I cannot find in the doc if such feature has been implemented.

**Comment by ewels** [comment]
Plot scaling in the exported plots is not currently supported, no. The code that does this is totally separate from the code that generates the exported plots from the report in the browser.

Honestly, I can't see myself adding support for this any time soon I'm afraid. The matplotlib code took ages with a lot of trial and error to find various plot sizes / font sizes etc that generally work and look sensible and I do my best to avoid touching it if at all possible. 

If / when I switch to Plotly for MultiQC plots, then adding this functionality should be fairly trivial. But that switch will involve a major rewrite of MultiQC and I have no idea when I will have time for this project.

**Comment by vladsavelyev** [comment]
Addressed this with https://github.com/MultiQC/MultiQC/issues/876
